### ISSUE TITLE
Spindle pin, how to connect?

### ISSUE THREAD

**Issue by Dareblix** [grbl/grbl#1004]
Hello , i want to use a chicago eléctric drill and i want to set up the spindle and i was wondering how should i connect this, i'm using grbl shield.

**Comment by tklus** [comment]
considering the Chicago electric drill doesn't have pwm control, you will just have to connect the drill either to the wall power and just manually switch it on and off. Or, you could connect the drill to a relay and connect the relay to the arduino. This is more of a machine build question and not a firmware question... You might check this out, tons of info here for machine building. http://www.shapeoko.com/forum/
