### ISSUE TITLE
M5 M0 Command not being accepted GRBL 9g

### ISSUE THREAD

**Issue by Phoenix0805** [grbl/grbl#1006]
I've been battling with the M5 M0 command as the machine would stop, but not stop the spindle. I tried different permutations until I found G0 M5 M0 worked. Still need to upgrade the firmware to the latest and then will retest the command. Just thought I'd share.

**Comment by foto-boss** [comment]
M5

**Comment by chamnit** [comment]
Works in v0.9j.

**Comment by armozy** [comment]
i tried v0.9g, v0.9i, v0.9j and v1.1, spindle enable pin output always 5V, M5 not working. I used 1 year, it works but its broke, i dont understood.

**Comment by lalo-uy** [comment]
if you migrate fron 0.8 be aware of pin 11 & 12 swap on V0.9 onwards.


2017-05-14 7:42 GMT-03:00 armozy <notifications@github.com>:
