### ISSUE TITLE
Current version?

### ISSUE THREAD

**Issue by JetForMe** [grbl/grbl#1012]
Hi. I have 0.9g installed, more than a year ago. I've seen indications that a 0.9i exists. But there are no branches nor tags on github for 0.9, and the latest build is 0.9a.

What's the latest version of grbl, and is there a built binary?

Thanks.

**Comment by chamnit** [comment]
V0.9j is the most recent build version. It's on the front page. A link is also available for a hex there too.

**Comment by JetForMe** [comment]
Oh, sorry. I was led into the wiki and a list of downloads from some other links I followed, and even on the home page I didn't see that (needed to scroll). Thanks!
