### ISSUE TITLE
drawing paper with Grbl

### ISSUE THREAD

**Issue by jajiyiko** [grbl/grbl#1015]
Hi;
I have a usbcnc grbl shield with a4988 drivers. I made simple machine x and y (two stepper motors) axis.,
For example I want to draw a star on paper.But not good.

like following picture;
this shape i want
![sam1](https://cloud.githubusercontent.com/assets/19895853/15994386/ea4174cc-310b-11e6-872e-ce9479473696.jpg),
this is it is written
![sam2](https://cloud.githubusercontent.com/assets/19895853/15994385/ea408026-310b-11e6-98af-d1c23f558ecf.jpg)

sorry for my english

thanks

**Comment by milezdr** [comment]
What CAM program you use for generating the g code? or can you post the g code

**Comment by jajiyiko** [comment]
hi!
I use LX Easy G-code Tools software for gcode.
nc file is attached.
[star.zip](https://github.com/grbl/grbl/files/312480/star.zip)
thank you

**Comment by 109JB** [comment]
Your zip file won't open. At least not for me.
