### ISSUE TITLE
Question: grbl on reprap

### ISSUE THREAD

**Issue by MoonshineSG** [grbl/grbl#1025]
is there a document describing how to configure the pins for a RepRap compatible board (MKS_GEN with Atmega2560) to run grbl ? I'm trying to convert (temporarily) my 3D printer to run grbl for a small project. I'd prefer not to have to rewire all the stepper motors.

**Comment by chamnit** [comment]
@MoonshineSG : Grbl is not configurable to RepRap (RAMP) pins at the moment. It's due to the difference between how Grbl uses a single shared port for stepper pulse and directions. RepRap does not.
