### ISSUE TITLE
Scaling Issue for x-carve

### ISSUE THREAD

**Issue by dylanrankin2** [grbl/grbl#1027]
Hi I have a 1000 mm by 1000 mm x-carve.

The x-carve seems to be cutting the right shape but in a larger scale.
For example, I asked easel to cut a 20 mm by 20 mm square, instead it cuts a square that is approximately 150 mm by 150 mm.

I bought a used x-carve and had to switch out the old Arduino with a new one because the old one died.
I have the latest Grbl 0.9j on the arduino.
After I calibrate it (getting the right direction and homing sequence testes on easel) I tested it out with a simple square cut.
Thanks in advance for your help

**Comment by chamnit** [comment]
@dylanrankin2 : Your settings were probably reset to the Grbl defaults, which are conservative for getting up and running safely. You'll need to re-write your settings. See the defaults file for the X-carve for the values. If you are comfortable with altering a source code file, you can change the config.h file where it asks for what defaults to compile with. Change that to the X-carve name (in default file). Re-compile and flash. Connect to Grbl and send it '$RST=*' to restore the defaults.
