### ISSUE TITLE
HELP! 2 Motors to 1 Axis!

### ISSUE THREAD

**Issue by kennet67** [grbl/grbl#1028]
This is my situation:
i have 2 Stepper Motors Nema 17 And a steppermotor driver a4988 pololu.
So I tried to put 12V to the driver and the nema 17 doesnt have so much strength I dont know Why the VRef its 0.60 iF you ask.
And I have a threaded rod so when i put only 1 motor doesnt move my structure but i want to ask.. How i can put the another one in mirror mode... I mean Example The motor turns right And the another Have to turns left... I tried to put a 74ls04 to deny the output to step and dir... But sometimes works and sometimes No... Im using Gcodesender and an arduino UNO and grbl 0.8... Please Help

**Comment by chamnit** [comment]
@kennet67 : You have two options. Wire your steppers to the same driver with one of the motor windings leads switch to make it run the other direction. Or use two stepper drivers and place an inverter on the direction pin on one of them.

**Comment by langwadt** [comment]
@chamnit with two stepper drivers you can also just swap one of the windings and skip the inverter ;)

**Comment by chamnit** [comment]
@langwadt : You're totally right. That's an example of an utter failure of drinking enough coffee. Time to brew a new pot.

**Comment by kennet67** [comment]
@langwadt I didnt get it, Wich thin gi have to swap? Sorry my ignorance

**Comment by jahnj0584** [comment]
If the first motors cables are ab cd in the terminal, motor two goes cd ab

**Comment by lalo-uy** [comment]
I belive you have to  change from abcd to abdc


2016-06-28 15:02 GMT-03:00 jahnj0584 <notifications@github.com>:

**Comment by kennet67** [comment]
the pololu goes from 
------> 1b, 1a, 2a, 2b
------> green, black, red, blue

so i have to put it in this order?

----->1b, 1a, 2a, 2b
------>blue, red, black, green?
??? 
and i have to use a NOT inverter? 7404 to deny the Direction pin? and its only the dir pin? leave the step pin normally?

thnaks ofr the help

**Comment by chamnit** [comment]
@kennet67 : Just make sure you are connecting the coils correctly. It's easy to know if two motor wires belong to the same coil by checking for near-zero resistance between them. The wire numbers and letters often swap between motor spec sheets and stepper drivers, so don't trust them. As long as you connect the two ends of a motor coil to where the driver wiring diagram expects a coil, you're good. If you want the stepper to switch directions, swap the two ends of one coil on the driver (NOT BETWEEN COILS). That's it. Wire everything else normally into Grbl.

**Comment by kennet67** [comment]
@chamnit i got it Thanks but i have another problem... the nema 17 motor doesnt have strength it has a minimal strength im using a super heavy duty power supply 17V and 10 amps but stills the same =( 
still using the a4988 driver (i'm not using a shield) ...how to fix it =(

**Comment by chamnit** [comment]
@kennet67 : Increase motor driver voltage as high as you can. This increases stepper motor torque. Otherwise get a Nema23.

**Comment by kennet67** [comment]
@chamnit sorry for bother you but i have a nema 17 42BYGH47-401A i bought it from here:

https://www.amazon.com/Nema17-Stepper-Motor-4-lead-Connector/dp/B00QEXSCE8?ie=UTF8&keywords=nema17&qid=1465484715&ref_=sr_1_4&sr=8-4 

and How much VREF do i have to regulate? i have 0.60V BUT STILLS CRAP! =( No strength

**Comment by lalo-uy** [comment]
Are you sure the current liimit in the a4988 is set right?


2016-06-29 13:11 GMT-03:00 kennet67 <notifications@github.com>:

**Comment by kennet67** [comment]
@lalo-uy How to know if it's right? the voltaje between the screw and the gnd its 0.60V now but wich volatge i need to regulate it?

**Comment by lalo-uy** [comment]
Check this  http://reprap.org/wiki/Pololu_stepper_driver_board

But also check the value of the Rs in your board to be sure.

Nema 17 shuld handle 1 to 1.2 A

2016-06-29 14:01 GMT-03:00 kennet67 <notifications@github.com>:

**Comment by pth3k** [comment]
0.6v comes to 1.5a / coil using the formula from the riprap wiki  I_TripMax= Vref/(8*Rs) 

Rs = Sense Resistor on Pololu = 0.05 ohms

Amps = 0.6 / ( 8 x 0.05 ) = 1.5A

You probably want to set Vref to 0.8v to get the 2A MAX of your steppers

Be warned, they will probably be pretty hot at that current.

You probably should move up to NEMA 23’s. You can double or triple the torque for the same amount of current, 
depending on the brand/model of the NEMA 23.

Ty Hoeffer

**Comment by jahnj0584** [comment]
nema 17s arent good for much besides light weight 3D printers.
