### ISSUE TITLE
movement not creating straight lines

### ISSUE THREAD

**Issue by smremde** [grbl/grbl#1033]
If I execute
G1 X0 Y0;G1 X100 Y100

I get a triangular movement. Consistently the head moves straight to 0,0, the to approx 5,0 then straight to 100,100. 

Using the latest source. Feed rate and acceleration do not make any difference. Any clues? No good for laser cnc..

**Comment by chamnit** [comment]
@smremde : That's very unusual. Can you provide your Grbl '$$' settings? And more details on how you are running the g-code (hopefully on separate lines)?

**Comment by smremde** [comment]
Grub not tight.. sorry.
