### ISSUE TITLE
Minor bug in GRBL 0.9j and 10.d (settings_restore)

### ISSUE THREAD

**Issue by usbcnc** [grbl/grbl#1036]
This is found while playing with the WIn32 simulation and STM32 port. When parameters does not exist in EEPROM, the first time it will try to restore the parameters and the code 
  if (restore_flag & SETTINGS_RESTORE_STARTUP_LINES) {
	#if N_STARTUP_LINE > 0
	eeprom_put_char(EEPROM_ADDR_STARTUP_BLOCK, 0);
	#endif
	#if N_STARTUP_LINE > 1
	eeprom_put_char(EEPROM_ADDR_STARTUP_BLOCK+(LINE_BUFFER_SIZE+1), 0);
	#endif
  }
  
  if (restore_flag & SETTINGS_RESTORE_BUILD_INFO) { eeprom_put_char(EEPROM_ADDR_BUILD_INFO , 0); }

Will not properly set the values and caused another round of EEPROM error the next time it runs. The reason is that it EEPROM_ADDR_STARTUP_BLOCK and EEPROM_ADDR_BUILD_INFO needs checksums.

The code I changed was 
  if (restore_flag & SETTINGS_RESTORE_STARTUP_LINES) {
      line[0] = 0;
	#if N_STARTUP_LINE > 0
	settings_store_startup_line(0,line);
	#endif
	#if N_STARTUP_LINE > 1
	settings_store_startup_line(1,line);
	#endif
  }
  
  if (restore_flag & SETTINGS_RESTORE_BUILD_INFO) { settings_store_build_info(line); }

**Comment by chamnit** [comment]
@usbcnc : Completely forgot about this. I applied this fix to v1.0 by writing an additional 0 (checksum value) to EEPROM.
