### ISSUE TITLE
Explain why variable float 'value' isn't initialized

### ISSUE THREAD

**Issue by doppelhub** [grbl/grbl#1038]
Howdy, I'm certain this is my own misunderstanding, but can you explain why the variable 'value' (gcode.c, line 108) isn't initialized before sending its address ('&value', gcode.c, line 118) via function 'read_float' (gcode.c, line 118)?  Over in nuts_bolts.c, function 'read_float' dereferences the address, which isn't initialized.

I've found myself down this rabbit hole while trying to determine why grbl sometimes doesn't recognize M03 commands at the beginning of a file.  For example, I get issues with the following code:
`M03        (spindle on)
S5000        (start spindle)
G4 P2        (delay)
S10000        (spindle full speed)
G4 P180        (warm up spindle)`

but if I simply change 'M03' to 'M3', the code always works:
`M3        (spindle on)
S5000        (start spindle)
G4 P2        (delay)
S10000        (spindle full speed)
G4 P180        (warm up spindle)`

  I've looked over the code ('gcode.c') and it handles the leading zero... I was worried maybe the interpreter with treating the leading zero to signify octal, but you convert the data type to float so this isn't an issue.

Any thoughts on either my question or issue greatly appreciated.

**Comment by langwadt** [comment]
there's no reason to initialize a variable if you are going to write a new value to it before reading it.  
the variable 'value' exist so it has an address, you get that address with & , no initialization involved
