### ISSUE TITLE
Error on make

### ISSUE THREAD

**Issue by tom4tom** [grbl/grbl#1045]
grbl/system.c: In function ‘system_convert_corexy_to_x_axis_steps’:
grbl/system.c:294:18: error: ‘A_MOTOR’ undeclared (first use in this function)
   return( (steps[A_MOTOR] + steps[B_MOTOR])/2 );
                  ^
grbl/system.c:294:18: note: each undeclared identifier is reported only once for each function it appears in
grbl/system.c:294:35: error: ‘B_MOTOR’ undeclared (first use in this function)
   return( (steps[A_MOTOR] + steps[B_MOTOR])/2 );
                                   ^
grbl/system.c: In function ‘system_convert_corexy_to_y_axis_steps’:
grbl/system.c:298:18: error: ‘A_MOTOR’ undeclared (first use in this function)
   return( (steps[A_MOTOR] - steps[B_MOTOR])/2 );
                  ^
grbl/system.c:298:35: error: ‘B_MOTOR’ undeclared (first use in this function)
   return( (steps[A_MOTOR] - steps[B_MOTOR])/2 );
                                   ^
grbl/system.c: In function ‘system_convert_corexy_to_x_axis_steps’:
grbl/system.c:295:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
grbl/system.c: In function ‘system_convert_corexy_to_y_axis_steps’:
grbl/system.c:299:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:53: die Regel für Ziel „build/system.o“ scheiterte
make: *** [build/system.o] Fehler 1

**Comment by chamnit** [comment]
@tom4tom : My bad. It's fixed now.
