### ISSUE TITLE
Is a smaller BLOCK_BUFFER_SIZE better?

### ISSUE THREAD

**Issue by cspwcspw** [grbl/grbl#1066]
My GUI can pause/resume its sender.  But because GRBL can have multiple cached lines of code in the RX buffer, and up to 18 queued linear motions in its planner buffer, it can take some minutes before the machine becomes idle.   (Yes, I can feed hold and resume if I want immediate responsiveness.)  But with faster serial communication in v0.9 and just allowing only one line of send-ahead RX buffering, I have not found any realistic situations in which the consumer outpaces the producer, and linear motion block "starvation" occurs.  So for me, fewer queued block buffers means things become "increasingly responsive".   (I concede, I'm mainly debugging / playing around, rather than in a production situation, so Your Mileage May Vary!)

Since the code says "The vast majority of RAM that Grbl uses is based on this buffer size", would it be a good trade-off to reduce this (free up memory for even more ambitious features)?   Or, asked differently, are there machines or situations that really benefit from a linear planning block buffer as big as 18?

Has anyone tried to reduce this a lot?  How low can we go?

Thanks
Peter

**Comment by chamnit** [comment]
@cspwcspw : The block buffer gauges how many blocks Grbl will look ahead to plan out an optimal time tool path. If lessen the size, you decrease the distance for which Grbl can plan. This can be problematic with motions that have lots of very small line segments, like arcs, but this requires a machine with fairly low accelerations to become noticeable at the current setting. Typically though, the plan is optimal in the first handful of blocks, except in the noted case.
