### ISSUE TITLE
Bad UBRR calculation?

### ISSUE THREAD

**Issue by coco243** [grbl/grbl#1078]
I don't think that the UBRR formula is correct in the serial.c

uint16_t UBRR0_value = ((F_CPU / (8L \* BAUD_RATE)) - 1)/2 ;

it shouldn't be?

uint16_t UBRR0_value = ((F_CPU / (16L \* BAUD_RATE)) - 1) ;

**Comment by gerritv** [comment]
The code is/has been working fine for years with those settings. What makes you think it is wrong?
A very very long discussion in baud rates didn't raise this either https://github.com/grbl/grbl/issues/837

**Comment by langwadt** [comment]
the second equation is the one show in the datasheet, as far as I can tell it comes down to rounding vs. truncating  

((16M / (8 * 115200)) - 1)/2 = 8.18
((16M / (16 * 115200)) - 1)  = 7.68

if you round they both result in the correct 8 ( 111111 baud)
if you truncate the second equation is 7 (125000 baud)
