### ISSUE TITLE
grbl for polar drawing robots?

### ISSUE THREAD

**Issue by mattvenn** [grbl/grbl#108]
Hi all,

I've been working on some polar drawing robots for a while (http://www.mattvenn.net/2011/09/19/polargraph-energy-monitoring/) for fun/interesting/beautiful realtime energy monitoring. We're looking at posting the energy (or any other environmental data) to the internet and then running the drawing algorithms on a server before sending back drawing commands to the robot.

I'm presently working on some dedicated hardware for controlling the robots (a bit like grblshield but with an atmega32u4 on board). I've put all the direction and step pins on one port for grbl. Instead of using a z axis we use a servo to lift the pen.

So, I wanted to know if anyone is interested in helping us out with adding a "polar translation layer" or similar to grbl? The fundamental difference is that we use gravity to pull the pen down, then move the pen around by winding string on bobbins. 

I'll admit I haven't looked at the code yet, I'm interested to see if people think this is possible or would like to help out. I could trade a controller board... 

Other people also use these types of robots for drawing lovely pics (see http://www.polargraph.co.uk/)

Cheers, 
Matt

**Comment by brennanag** [comment]
I'm curious if this got anywhere? I'm trying to use a grbl to drive a v-plotter type machine.

**Comment by mattvenn** [comment]
I'm using linuxcnc now: https://github.com/mattvenn/linuxcnc-bipod/

On 18 June 2016 at 03:29, brennanag <notifications@github.com> wrote:

> I'm curious if this got anywhere? I'm trying to use a grbl to drive a
> v-plotter type machine.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/grbl/grbl/issues/108#issuecomment-226914085>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAmtbNFTLCR6iNnfnvTQhZJbw3scg0sLks5qM0nhgaJpZM4ADw17>
> .
>



-- 
Matthew Venn
web mattvenn.net twitter @matthewvenn <https://twitter.com/matthewvenn>

**Comment by brennanag** [comment]
Thank you for responding I'm trying to wrap my head around the maths to
convert the two types of instruction sets.
On Sat, Jun 18, 2016 at 11:13 AM matt venn <notifications@github.com> wrote:

> I'm using linuxcnc now: https://github.com/mattvenn/linuxcnc-bipod/
>
> On 18 June 2016 at 03:29, brennanag <notifications@github.com> wrote:
>
> > I'm curious if this got anywhere? I'm trying to use a grbl to drive a
> > v-plotter type machine.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/grbl/grbl/issues/108#issuecomment-226914085>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AAmtbNFTLCR6iNnfnvTQhZJbw3scg0sLks5qM0nhgaJpZM4ADw17
> >
> > .
> >
>
>
>
> --
> Matthew Venn
> web mattvenn.net twitter @matthewvenn <https://twitter.com/matthewvenn>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/grbl/grbl/issues/108#issuecomment-226956806>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AASHk50NN3mz_3EFMk585BY3uNJjGjsEks5qNDVegaJpZM4ADw17>
> .
>
-- 
*Brennan Aitken-Gantz*
Portland State University :: AIAS President
541-612-8553
brennan.ag@gmail.com

**Comment by mattvenn** [comment]
I still think it's worth doing, especially if it could get ported to the
esp8266 or something with cheap wifi. I've always ended up pairing the
micro with a pi to get it on the internet. That's why I ended up with
linuxcnc (on beaglebone).
Matt

On 18 June 2016 at 20:35, brennanag <notifications@github.com> wrote:

> Thank you for responding I'm trying to wrap my head around the maths to
> convert the two types of instruction sets.
> On Sat, Jun 18, 2016 at 11:13 AM matt venn <notifications@github.com>
> wrote:
>
> > I'm using linuxcnc now: https://github.com/mattvenn/linuxcnc-bipod/
> >
> > On 18 June 2016 at 03:29, brennanag <notifications@github.com> wrote:
> >
> > > I'm curious if this got anywhere? I'm trying to use a grbl to drive a
> > > v-plotter type machine.
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/grbl/grbl/issues/108#issuecomment-226914085>, or
> > mute
> > > the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AAmtbNFTLCR6iNnfnvTQhZJbw3scg0sLks5qM0nhgaJpZM4ADw17
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Matthew Venn
> > web mattvenn.net twitter @matthewvenn <https://twitter.com/matthewvenn>
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/grbl/grbl/issues/108#issuecomment-226956806>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AASHk50NN3mz_3EFMk585BY3uNJjGjsEks5qNDVegaJpZM4ADw17
> >
> > .
> >
> --
> *Brennan Aitken-Gantz*
> Portland State University :: AIAS President
> 541-612-8553
> brennan.ag@gmail.com
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/grbl/grbl/issues/108#issuecomment-226958080>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAmtbJB6jSGO4ncQyG4c8R8gEsmY0TUUks5qNDptgaJpZM4ADw17>
> .
>



-- 
Matthew Venn
web mattvenn.net twitter @matthewvenn <https://twitter.com/matthewvenn>

**Comment by Chicodarave** [comment]
Trying this in 2018... Cant find a solution :(

**Comment by Abd9** [comment]
Hy !
Can any body tell me how to make changes in grbl files to convert the Arc or circle X,Y points into Radius,Angle and use these valuse and convert them into motor steps to move the motor

**Comment by Abd9** [comment]
Hy this stuff was useful ,but i am actually working on cnc mobile robot
with steerable wheel mechanism like golaith but they have used omniwheels
Can u help me how to make changes in grbl for steerable wheel mechanism

**Comment by Abd9** [comment]
Hy this stuff was useful ,but i am actually working on cnc mobile robot with steerable wheel mechanism like golaith but they have used omniwheels
Can u help me how to make changes in grbl for steerable wheel mechanism

**Comment by jacobevans** [comment]
@ununbium Did you ever get the piece of software you were talking about working?  I'm trying to do something similar, but I can't quite see how the math works out
