### ISSUE TITLE
Change settings ($$) before uploading to Arduino

### ISSUE THREAD

**Issue by matthewhertel** [grbl/grbl#1089]
Hello Sonny,

Can you tell me how to change the settings ($$) before I flash the Arduino?

Thanks,
Matt

**Comment by chamnit** [comment]
@matthewhertel : Alter the defaults.h file. It'll write the settings to EEPROM upon power up.

If you previously installed Grbl on the Arduino, it'll more than likely not do that. You'll need to connect to Grbl a `$RST=*` command to manually restore it.

**Comment by matthewhertel** [comment]
Thanks,
I will try that out!

-Matt
