### ISSUE TITLE
How to create buttons for manual control Z-axis?

### ISSUE THREAD

**Issue by stajor81** [grbl/grbl#1093]
Hi!
Please redirect me if this is wrong place for such question:
I need to control Z-axis manually.  i.e. I need two new buttons: Z+ and Z-
Is there a simple solution?
Thx!

**Comment by jahnj0584** [comment]
use a control software.....

**Comment by stajor81** [comment]
it is inconvenient in my case

**Comment by 109JB** [comment]
Grbl is meant to take commands by serial stream. 

You could set up another arduino to respond to a button press by sending a serial command to the arduino with GRBL installed.

**Comment by stajor81** [comment]
Is it possible to override Hold and Resume buttons to Z+ and Z-?

**Comment by chamnit** [comment]
@stajor81 : There is no configuration option to do what you are asking. You'll need to hack the source code.
