### ISSUE TITLE
Question...Settings backup

### ISSUE THREAD

**Issue by DOUG888** [grbl/grbl#1096]
Is there a way to dump the GRBL settings into a text file for safe keeping or what file should i backup on the computer...windows7 latest GRBL
Thanks

**Comment by Protoneer** [comment]
I use Tera term to connect and save settings.

To restore it you will need to clean the saved file by making sure only the
$?=? Is left per line.

Tera term can play back files to a serial port.

**Comment by DOUG888** [comment]
Only gave me the top line then hung up...thanks anyway :-)

**Comment by DOUG888** [comment]
You put me on the correct path tho ...got Coolterm to work....thanks
