### ISSUE TITLE
Steppers not working, everything else seems to work

### ISSUE THREAD

**Issue by Combatir** [grbl/grbl#1097]
Dear Grbl experts,

When I use G code sender or Chillipeppr to let my stepper motors move it does not work. But on screen it seems to work so I dont know what I am doing wrong hehe.

For example, I use a Arduino UNO with a CNC shield V3, I have the drivers connected on the shield and the shield connected to the arduino. Connected to my computer with usb and the power supply connected for the steppers. 
I flashed GRBL to the arduino and that seems to work, it says Grbl 0.8c ['$' for help] when connecting. (or 0.9 when testing it with that version).

When I use the machine control it says this:>>> G91 G0  X-1
ok
etc, so that seems to work, however the motors don't move a bit.
When I try to run with chillipeppr they also seem to work on screen but they do not.

Did I do something wrong with the wiring?
Would love to hear your ideas!

Combatire

**Comment by jahnj0584** [comment]
Do the motors make noise (a hum) when you turn the power supply on?

**Comment by Combatir** [comment]
Dear Jahnj,
They do not, they make no sound or anything.
Btw I use nema 17 stepper motors.

**Comment by jahnj0584** [comment]
Wired wrong. Find out which is a coil pair and look at the diagram again
from protneer

**Comment by Combatir** [comment]
Thanks Protneer I will try to rewire and post the results.

**Comment by Combatir** [comment]
I have found a diagram for how to connect the wires to the stepper motor and those are connected like they should. I also found the pairs, for example the gray and green are a pair and yellow/red are one. I try to look it up but cant find it for sure so maybe you know. Do you just put the pairs together in the pin and then connect to the shield?

**Comment by Combatir** [comment]
![gcodesender](https://cloud.githubusercontent.com/assets/22530466/18973329/4062a844-869d-11e6-8c41-075fb8cc1122.png)
![20160929_233245](https://cloud.githubusercontent.com/assets/22530466/18973335/43e8b72e-869d-11e6-809b-7b053d33ab0f.jpg)

**Comment by Encarnacao** [comment]
from what you discribe it seems that you have the wiring wrong or that your adjustment of the vref trim pot of drivers might not be correctly adjust

**Comment by Combatir** [comment]
Yes I think so too, tried to change the wires but did not work. By the way I saw that when I open it up on Gcode sender the UNO begins blinking a red light, dont know what that means. I will continue tomorrow. If anyone has anything that might help me much appreciated.

**Comment by Encarnacao** [comment]
did you check with a multimeter to see if you got voltage on the VMOT and gnd pins?

**Comment by Combatir** [comment]
Encarnacao, I did not check that I do not have a multimeter quite a noob I am lol.

**Comment by Encarnacao** [comment]
you see the blue conectors on the cnc shield, they arent powered

**Comment by Combatir** [comment]
Yes but I do have the black cable plugged in from a power source, is that okay or do I still need to power the blue connectors?

**Comment by Encarnacao** [comment]
all you doing is powering the arduino, you need to power the motors externaly and yes on the blue connectors, thats why isnt working

**Comment by Encarnacao** [comment]
also remeber that you using the CNC shield V3 that was made for the grbl 8, and that if you use the grbl 9 you will need to swap the pins 11 and 12 , go on the grbl github and you will see, you can do that by soldering 1 wire in the pin 11 and 1 wire in pin 12 on the back of the arduino and then bend those pins on the shield and swap them if you gonna use the grbl 9, but this isnt the reason why isnt working, just to let you know how to proper conect the grbl9 with the shield you have

**Comment by Combatir** [comment]
Thanks for your advice, tomorrow I will continue to solve my problem. I will need to get a power supply then hahaha

**Comment by Encarnacao** [comment]
you can always get a 12v power supply from a old comp just to test it out things :)

**Comment by Combatir** [comment]
So Just to be sure,
http://www.elecrow.com/12v2a-acdc-power-adapter-with-cable-p-683.html Will only Power the arduino itself but cannot Power the steppermotors Right ?
Thanks for the Help!

**Comment by Encarnacao** [comment]
to plug the motors you would need to cut the end of the 12v adapter to connect to the shield or get some adapter, now that 12v adapter is only 2 amps so assuming you will use 3 motors  and assuming  they will spend 1 Amp eatch that would be 3 Amps, if you could find some old computer you could remove the power supply and use the yelow ans black wire to supply you with 12v and alot of amps, just a idea lol

**Comment by Encarnacao** [comment]
also one thing from picture i see you have there 3 drivers and only one motor, always remove the drivers that dont have the motor on (load) you shouldnt never plug the shield with drivers with out a load on it, that will damage the drivers

**Comment by Combatir** [comment]
Thanks for all the advice, when I come home I will look for such a power supply. 
I think I maybe already damaged all the drivers. If I attach only one driver with one motor applied, connected with usb and the 2 amp plug, it won't work, so I think that means the shield are damaged. 
I will later try with a bigger power supply.

**Comment by electrokean** [comment]
Usually the drivers are only damaged if you plug or unplug the motors while they are powered on, so they're probably still OK if you didn't have any power connected to the shield.  But it is probably a good idea to leave off any drivers that aren't in use till you get the basics working.

**Comment by Combatir** [comment]
Yes I will do that, but suppose I have the 2 amp power supply and only one motor and driver connected it should work right?

**Comment by electrokean** [comment]
Yes, it should.
Your issue isn't really with Grbl, so you might want to read/use the CNC Shield forums at http://forum.protoneer.co.nz/

**Comment by Combatir** [comment]
Will do thanks for the help.

**Comment by matiasgonzalez90** [comment]
HI I'm having the same problem as you. Did you solve it?? Could you tell me how? 

Thanks!

**Comment by madbuster** [comment]
I have made a  cnc router with grbl arduino and drv8825 ...some days ago it was working well then first problem come that all axis move in same direction for +ve and -ve command ...then second problem was y-axis stopped working at all ...and now whole electronic part stopped working...

**Comment by Rob2029** [comment]
did you check everything with a multimeter??

**Comment by mikypolice** [comment]
Hey guys, you have an idea for this?
https://www.dropbox.com/s/t4up3aelpswlmlg/20180915_150257.mp4?dl=0
I changed the board with Arduino uno clone and the driver with 3 tb6560 with same result!!!! I've tried 0.9j and 1.1 with my clone but the result is the same!
I used a 12v 20A power supply with my wiring, the tb6560 are setup to 1.2A for nema 17 (1.33A). Is only Y axis...
It's possible to be a feed rate setting? $111?

**Comment by mikypolice** [comment]
solved! it was the wiring from the motor Y to driver!

**Comment by Pappagoran** [comment]
Can I ask how you wired it? I seams to have the same problem.

**Comment by mikypolice** [comment]
The controller have 4pin jst plug for each stepper motor, but each motor have 6pin jst plug. The wire are only 4. So you check wire by wire the position and the color if are plugged corrected into jst plug.
Motor side (6pin jst plug) the correct sequence of wire are:
black---not connected---green---blue---not connected---red.
In my case the problem was in that sequence:
black---green---blue---not connected---not connected---red...
So check the wire of jst!!
Sorry for my bad english..

**Comment by Pappagoran** [comment]
Thank you. Was this Only för the Y?

Goran

Den ons 31 okt 2018 12:22mikypolice <notifications@github.com> skrev:

**Comment by mikypolice** [comment]
Yes, because the other axis worked fine.
I discovered the problem only by doing cross-tests between engines and drivers. in the end I isolated the problem on the cable, comparing it with the others, it was badly wired.

**Comment by Pappagoran** [comment]
Ok, can I just  change order on the wire?
[image: 20181031_165124-1 copy.jpg]


Den ons 31 okt. 2018 kl 16:53 skrev mikypolice <notifications@github.com>:

**Comment by mikypolice** [comment]
Yes, but the order must ne like this...
https://www.dropbox.com/s/viwy9utdk8vuqwf/SmartSelect_20181031-193642_Samsung%20Internet.jpg?dl=0
and side controller like this
https://www.dropbox.com/s/a8oclk4hj1ok54s/woodpeckercnc.png?dl=0

**Comment by Pappagoran** [comment]
I see you are using a woodpeeker. So do I with this wiring (see pictures)
and it works great. The problem whit that card is it loosing connection to
the port all the time. Have you expired the same problem?

I had no success trying rewiring the Arduino. Must be something els.
[image: 20181031_204732.jpg]
[image: 20181031_204732-1.jpg]

Den ons 31 okt. 2018 kl 20:01 skrev mikypolice <notifications@github.com>:

**Comment by mikypolice** [comment]
have you tried to load grbl 1.1j with xloader? that controller if it shows the writing rev 0.9 is also compatible with the fw grbl 1.1j

I've uploaded that using xloader.

The speed of the USB port to be set is 115200.

Try changing usb cable.

**Comment by Pappagoran** [comment]
After turning the wifi of it seams to work. Also it seams to be very
important to click the reset before every new work/tool.

Den ons 31 okt. 2018 kl 21:34 skrev mikypolice <notifications@github.com>:

**Comment by mikypolice** [comment]
So you use USG to control your cnc? And you turning ON (switch from usb to wifi) or turning OFF (switch from wifi to usb) the wifi?

**Comment by Shahid-lateef** [comment]
> Dear Grbl experts,
> 
> When I use G code sender or Chillipeppr to let my stepper motors move it does not work. But on screen it seems to work so I dont know what I am doing wrong hehe.
> 
> For example, I use a Arduino UNO with a CNC shield V3, I have the drivers connected on the shield and the shield connected to the arduino. Connected to my computer with usb and the power supply connected for the steppers.
> I flashed GRBL to the arduino and that seems to work, it says Grbl 0.8c ['$' for help] when connecting. (or 0.9 when testing it with that version).
> 
> When I use the machine control it says this:>>> G91 G0 X-1
> ok
> etc, so that seems to work, however the motors don't move a bit.
> When I try to run with chillipeppr they also seem to work on screen but they do not.
> 
> Did I do something wrong with the wiring?
> Would love to hear your ideas!
> 
> Combatire

I have a same problem tell me how you can solve it

**Comment by MeJasonT** [comment]
Hi Shahid-lateef
Lateef ? (is that your first name, i know some countries the surname is first)
It sounds like you stepper drivers have an enable signal and nothing is connected, or the enable signal may need inverted in the config.ini.
It is probably best if you ask your question here
[https://github.com/gnea/grbl/issues](url)  

 As this Git branch is no longer being supported, you will most certainly have more luck there.
I understand how frustrating it is when someone re directs you, hopefully this does not offend but its been a long time since members used this site and i would relly like to see you get help with your question.
