### ISSUE TITLE
h-bridge support - merge request

### ISSUE THREAD

**Issue by supagu** [grbl/grbl#1098]
Hi,

I've added in h-bridge support to the latest grbl code, based on the h-bridge code from v0.7,
There is a define to enable this in config.h (which is enabled in my code, it probably should be commented out be default!)

from config.h:

// Use a H-BRIDGE stepper driver
#define USE_HBRIDGE // Comment to disable

The modified source is available from my google drive:
https://drive.google.com/open?id=0B_nQZvJoqbFmTHF5MGtHT2JQNHM

Ta,
Fabian

**Comment by chamnit** [comment]
@supagu : Thanks. I downloaded it, but I'll have to take a look at it later when I have some time. H-bridge isn't something that is very common anymore, so this will likely get buried in my long priority list. But at least I'll have this on hand as reference if I find that I need to add this. In the meantime, it might be a good idea to post this code on your own github repo (it's free), so those people that need to find a solution for H-bridges can search and find your code easier.
