### ISSUE TITLE
I have normally-closed limit switches.  What do I change in the header files?

### ISSUE THREAD

**Issue by PeterGrace** [grbl/grbl#1111]
I'm looking for some feedback on what I need to configure for my normally closed limit switches.

I see in the config headers:

```
// Inverts pin logic of the control command pins. This essentially means when this option is enabled
// you can use normally-closed switches, rather than the default normally-open switches.
// NOTE: If you require individual control pins inverted, keep this macro disabled and simply alter
//   the CONTROL_INVERT_MASK definition in cpu_map.h files.
// #define INVERT_ALL_CONTROL_PINS // Default disabled. Uncomment to enable.

```

I'm wondering whether this also inverts the logic for the probe pin?  If so, I probably don't want that.

Then I see:

```
// Inverts select limit pin states based on the following mask. This effects all limit pin functions,
// such as hard limits and homing. However, this is different from overall invert limits setting.
// This build option will invert only the limit pins defined here, and then the invert limits setting
// will be applied to all of them. This is useful when a user has a mixed set of limit pins with both
// normally-open(NO) and normally-closed(NC) switches installed on their machine.
// NOTE: PLEASE DO NOT USE THIS, unless you have a situation that needs it.
// #define INVERT_LIMIT_PIN_MASK ((1<<X_LIMIT_BIT)|(1<<Y_LIMIT_BIT)) // Default disabled. Uncomment to enable.
```

This looks like a winner, but it says "PLEASE DO NOT USE THIS", making me think that instead I should be modifying cpu_map.h, OK!  I'll go have a look there.  I'm thinking this line is what I need:

`#define LIMIT_MASK       ((1<<X_LIMIT_BIT)|(1<<Y_LIMIT_BIT)|(1<<Z_LIMIT_BIT)) // All limit bits
`

So I guess my TL;DR is -- which of these settings should I change if I only have NC switches for X,Y,Z?

**Comment by chamnit** [comment]
@PeterGrace : Nothing. You need to change the Grbl `$` setting to invert the limit pins when connected to Grbl.
