### ISSUE TITLE
Arduino+L293D motors act weird

### ISSUE THREAD

**Issue by pajamac** [grbl/grbl#1114]
Hey grbl community.Recently I was trying to get into cnc magic with homemade (old cd rom drives) cnc.
I have this setup.
Arduino Uno,2 L293D H bridges,grbl v0.8 flashed on arduino with xloader,grbl controller

When I send "G0 z-1" command using grbl controller my z motor goes up but when I want to move it down(tryed many combinations of z) nothing happens.

Another example is that when I upload file generated from makercam.com all motors go on 1 side and stays there forever even tho I cant hear them trying to move.

Any help please ? :)

**Comment by chamnit** [comment]
@pajamac : Grbl does not support H-bridges, nor does it plan to. It requires a stepper driver that accepts a step pulse input and a direction input. If you are using a hacked version of Grbl that adds H-bridges, please contact that project developer for help.
