### ISSUE TITLE
 2 wire motor + grbl = what shield to use

### ISSUE THREAD

**Issue by pajamac** [grbl/grbl#1115]
Hey guys,Im trying to make very basic 3 axis machine.I use cd rom motors.I have used h bridge to control my motors which have only 2 pins and all worked well.Then I got informed that grbl dont support h bridge.
Im looking for shield that can step controll 3x 2 pins motors.
Could I use motor driver A3967?There is problem that i have 2 wire motor and this is for 4 wired motors?
Can someone help me please ?

**Comment by whitetd** [comment]
Sounds like your trying to use plain DC motors. Not suitable for cnc. Needs
stepper motors or servos to give position  control.

On Oct 18, 2016 12:46 PM, "pajamac" <notifications@github.com> wrote:

Hey guys,Im trying to make very basic 3 axis machine.I use cd rom motors.I
have used h bridge to control my motors which have only 2 pins and all
worked well.Then I got informed that grbl dont support h bridge.
Im looking for shield that can step controll 3x 2 pins motors.
Could I use motor driver A3967?There is problem that i have 2 wire motor
and this is for 4 wired motors?
Can someone help me please ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/grbl/grbl/issues/1115>, or mute the thread

**Comment by pajamac** [comment]
Thank you for reply :)
Well Im getting into controlling motors(Even tho I made robot that was driving around) and I dont know how to know what that motor is :( Any kind of arduino code that would work only if its stepper motor ?

**Comment by whitetd** [comment]
It needs to be a stepper so it can be controlled precisely in position or
be a servo that has feedback to control position.  A DC motors just turns
continues as long as power is applied. No position control. Do some
research on stepper motors.

**Comment by pajamac** [comment]
Alright now I understand that I need stepper,is there any way I can test if that motor is stepper ? I dont have cd rom number or anything and motors are clean too :(

**Comment by whitetd** [comment]
Look for 4 plus wires to motor. Old floppy drives used them for head
position. Cd roms possibly.

**Comment by splitn2** [comment]
a 2 wire motor won;t be a stepper sorry to tell you. If it had 4 or 6 or 8 it might be a stepper and then you need to use identifying marks and wiring colors etc and/or a multimeter to work out what is the correct wiring. This 2 wire motor sounds like a simple free running dc motor. You do need to do some googling about "stepper motor vs dc motor" which will help define the differences

https://www.modmypi.com/blog/whats-the-difference-between-dc-servo-stepper-motors is a good example

hope this helps

cheers
Richard

**Comment by pajamac** [comment]
Well thats negative.Only 2 wires here.
Ok RIP me.
But why does then Stepper.h work with this kind of motor ?

**Comment by pajamac** [comment]
I have this code 
`#include <Stepper.h>

const int stepsRevolution = 200;  
Stepper myStepper(stepsRevolution, 6, 3);

int stepCount = 0;  // number of steps the motor has taken

void setup() {
  Serial.begin(9600);
  // nothing to do inside the setup
}

void loop() {
  int motorSpeed = 1;
  if (motorSpeed > 0) {
    Serial.println(stepCount);
    myStepper.setSpeed(motorSpeed);
    myStepper.step(stepsRevolution / 100);
    stepCount = stepCount + 1;
  }
}`
Would this work on normal dc motors ?

**Comment by whitetd** [comment]
DC motors will not work.

**Comment by pajamac** [comment]
Then I have stepper motor :D

**Comment by whitetd** [comment]
A stepper will only rotate a small amount when you apply power to a set of
Leads, then sequence that switching to different  set of Leads, to continue
rotating. This gives control to how far it moves. DC motors will not work
that way.

**Comment by chamnit** [comment]
This issue isn't Grbl-related so I'm closing this thread. @pajamac: There are lots of online resources explaining how stepper motors work. Please take the time to read these. Thanks.
