### ISSUE TITLE
How to control cooler?

### ISSUE THREAD

**Issue by stajor81** [grbl/grbl#1118]
Hi!
I connected 12v cooler to CNC shild (CoolEn pin). But grbl does not understand M245 and M246 g-codes. (Unknown command).

**Comment by chamnit** [comment]
@stajor81: Grbl uses standard gcode commands found on LinuxCNC and other major CNC manufacturers. 3D printer gcode dialect is a lot different and specific to 3D printing. See the Grbl front page or wiki for a list of supported gcode command.

**Comment by jahnj0584** [comment]
thats for coolant, not cooler. Use a M9 command instead.
