### ISSUE TITLE
Laser OFF on pause

### ISSUE THREAD

**Issue by DOUG888** [grbl/grbl#1129]
Confirmation please

with the latest version of GRBL,   Laser mode $32 YES.....will the laser change power to S0 when the PAUSE command/button is pressed?? and revert back to S___ when the start button is pressed... I would think that this would be the case as you don't want the laser on with no movement. I just don't see anything in the posts/wiki about this.
thanks 
Doug

**Comment by chamnit** [comment]
@DOUG888 : First, this is the wrong place to post a question about Grbl v1.1. Please place future questions on that at the v1.1 repo.

Second, laser mode is still being worked out based on user and OEM feedback. Grbl v0.9 does not support lasers officially. Ask questions to the vendor that supplied your hacked Grbl, if you are using one.

Third, v1.1 documentation is a work in progress. It is all currently available in the /doc/markdown folder. Please take a read. The Wiki is not online yet and will be when Grbl v1.1 goes to master. Please be patient.

To answer your question, v1.1 laser mode does not disable the laser during a feed hold. However, I am playing with an experimental config.h option called LASER_CONSTANT_POWER_PER_RATE. It will scale the laser power based on how fast the machine is traveling to provide a constant amount of energy per mm traveled. If the machine is in a feed hold, it should turn the spindle off. Keep in mind that I've enforced this special mode to work only with G1,G2,G3 motion modes. G0 should keep the laser power constant even if it's stopped as a way to focus the laser prior to starting a job.
