### ISSUE TITLE
$1=255 noise

### ISSUE THREAD

**Issue by Radiu** [grbl/grbl#1132]
when i set my motors to always be on with the command $1=255 the motors makes noise is there anyway to remove the noise?

also i have the drivers DRV8825 what would be the correct setting for $0 = 10    (Step pulse time, microseconds)?

thanks

**Comment by Protoneer** [comment]
:) that is the noise of the stepper drivers staying on and keeping the
steppers in position at all time.

This is normal for chopper type stepper drivers.

**Comment by jahnj0584** [comment]
yes this is normal. You can close this issue now.

**Comment by Fosforitofercho** [comment]
I had the same problem, not the sound, electromagnetic noise, the solution, all the cables used in your machine must be shielded,includes the limits , for me it worked, even when my router turns on the machine. Whit shielded cables all problems disappeared.
