### ISSUE TITLE
Grbl Depth Probe

### ISSUE THREAD

**Issue by kosme** [grbl/grbl#115]
I built a depth probe and am trying to code the behavior for it on the Grbl. I want to use Analog pin 0 of the Arduino (PORTC pin 0) but haven't been able to make it work. The code is:

DDRC =0X00;
PORTC=0X00;

In gcode.c the code is:

if(PORTC&1==true)
      gc.status_code = STATUS_DEPTH;

That should send a message when the probe touches the pcb. I connect Analog0 to GND through an external pull-down resistor and the pcb is connected to Vcc.

Any ideas what I am missing/doing wrong?

**Comment by 13ct709** [comment]
When i short A5 pin to GND,for use a probe then nothing happens.
Is there a $-command where this funktion must be enabled?
thx
