### ISSUE TITLE
8bit resolution variable Spindle

### ISSUE THREAD

**Issue by adibiut** [grbl/grbl#1156]
Hi everybody. My CAM software for Laser engraving, generates 0-255 spindle speed, but grbl has a 0-1000 range. which part of code should be changed in to have a 8bit Spindle enable output?

**Comment by chamnit** [comment]
@adibiut : Grbl maps 0-1000 rpm to 8-bits. The rpm values are arbitrary and only there to associate an rpm to voltage.

**Comment by adibiut** [comment]
I know that. I want to have a 5v voltage when S255 and 0v voltage where S0
but current version sends out 5v when S1000

**Comment by langwadt** [comment]
change the max_rpm setting to 255, I think it is $30

**Comment by adibiut** [comment]
I'm using 0.9j and there is not such setting

**Comment by chamnit** [comment]
@adibiut : It can be changed in the config.h file. Otherwise use v1.1, which has $30 available as an rpm max setting.

**Comment by mayhem2408** [comment]
If you want to change the default range to be between 0-255 instead of 0-1000, you can change the defaults.h file and modify DEFAULT_SPINDLE_RPM_MAX which will be 1000 by default.
