### ISSUE TITLE
Frequency of variable spindle

### ISSUE THREAD

**Issue by adibiut** [grbl/grbl#1163]
Hi everybody. I have a question. what's the frequency of varibale spindle PWM wave?

**Comment by tasiv** [comment]
As stated in the documentation:

By default, the spindle PWM frequency is 1kHz, which is the
recommended PWM frequency
for most current Grbl-compatible lasers system. If a different frequency is
required, this may be altered by editing the `cpu_map.h` file.

I imagine this is the same outside of laser mode.

**Comment by chamnit** [comment]
@adibiut : Correction. In v0.9, the default PWM frequency is 7.8 kHz. In v1.1, it was updated to 1 kHz.
