### ISSUE TITLE
Mirror axis

### ISSUE THREAD

**Issue by sigifre** [grbl/grbl#1171]
There are any way to mirror the Y step pulse to another Arduino pin for  2 motors in the same axis? (having one as slave)

**Comment by chamnit** [comment]
Connect your stepper driver to the same pin.

**Comment by sigifre** [comment]
that does not work good...
In other platforms they use slaves for that reason, they use axis A and u can configure it as slave of any other.

**Comment by vMeph** [comment]
Just put in paralel the enable, dir and step on the drivers and will work

**Comment by 109JB** [comment]
As said, just wire the drivers in parallel and if one if the motors turns the wrong direction the just switch the wires for one coil going to the motor. For example move A+ to A- and vice versa.

**Comment by sigifre** [comment]
it is in that way but the max speed is reduced, so in a moderate speed it works good. I just want to try a mirror axis to see if the speed can be higher.

**Comment by jahnj0584** [comment]
The driver's decide that, not grbl. I can do 30m/min with two Y motors

**Comment by electrokean** [comment]
As said above you can definitely slave an axis just by paralleling the step & direction outputs.
Many drivers have opto-isolated inputs, and it may be possible that paralleling driver inputs could put too much load on the ATmega328 output pins affecting signal integrity and limiting may pulse rate.  In this case it may be necessary to insert some signal buffering.

**Comment by sigifre** [comment]
Thats why Im looking another pulse signal pin, it seems that the only way is modifying the library.
