### ISSUE TITLE
G38.2 Probing giving different speeds on different axes

### ISSUE THREAD

**Issue by razeh** [grbl/grbl#1183]
I am seeing different speeds when I issue a G38.2 X10 F1 vs G38.2 Y10 F1 commands. When I issue G38.2 X10 F1 my spindle moves faster than when I issue the G38.2 Y10 F1 command. I tried slowing down the speed by sending G38.2 X10 F.1 but that didn't move any slower than G38.2 X10 F1.
I am running GRBL 1.0c on an Inventables X-Controller.
My setup is a little unusual in that I have different settings for my X and Y axis (they have different size motors, microstepper settings, and belts). My X-axis is set to 11.111 steps per mm, and my Y-axis is set to 20 steps per mm.

I'm attaching by setup just in case it helps:
Grbl 1.0c ['$' for help]
>>> $$
>>> $G
$0 = 10    (step pulse, usec)
$1 = 255    (step idle delay, msec)
$2 = 0    (step port invert mask:00000000)
$3 = 6    (dir port invert mask:00000110)
$4 = 0    (step enable invert, bool)
$5 = 0    (limit pins invert, bool)
$6 = 0    (probe pin invert, bool)
$10 = 3    (status report mask:00000011)
$11 = 0.020    (junction deviation, mm)
$12 = 0.002    (arc tolerance, mm)
$13 = 0    (report inches, bool)
$20 = 0    (soft limits, bool)
$21 = 0    (hard limits, bool)
$22 = 0    (homing cycle, bool)
$23 = 3    (homing dir invert mask:00000011)
$24 = 25.000    (homing feed, mm/min)
$25 = 750.000    (homing seek, mm/min)
$26 = 250    (homing debounce, msec)
$27 = 1.000    (homing pull-off, mm)
$30 = 12000.    (rpm max)
$31 = 0.    (rpm min)
$100 = 11.111    (x, step/mm)
$101 = 40.000    (y, step/mm)
$102 = 320.000    (z, step/mm)
$110 = 8000.000    (x max rate, mm/min)
$111 = 8000.000    (y max rate, mm/min)
$112 = 500.000    (z max rate, mm/min)
$120 = 500.000    (x accel, mm/sec^2)
$121 = 500.000    (y accel, mm/sec^2)
$122 = 50.000    (z accel, mm/sec^2)
$130 = 740.000    (x max travel, mm)
$131 = 790.000    (y max travel, mm)
$132 = 100.000    (z max travel, mm)
ok
[G0 G54 G17 G21 G90 G94 M0 M5 M9 T0 F0. S0.]

**Comment by chamnit** [comment]
@razeh : Grbl's AMASS step smoothing algorithm is limited to around 200 steps per second. It can't go slower than that. At 1mm/min and 11 steps/mm, you asking Grbl to move at a super slow rate of 0.2 steps per sec. 

If you need to move at a super slow rate consistently, you can disable AMASS in config.h. You can go as slow as 4 steps/sec in this mode.
