### ISSUE TITLE
Visualization doesn't work - Win10 Intel(R) Q45/Q43 Express Chipset (MS Corp - WDDM 1.1)

### ISSUE THREAD

**Issue by rkreiple** [grbl/grbl#1184]
2 PC's, no visualization.

3rd same PC with NVidia GT610 works.

Apparently the Intel(R) Q45/Q43 Express Chipset (Microsoft Corporation - WDDM 1.1) driver won't handle it, Driver is the latest.

**Comment by gerritv** [comment]
This has nothing to do with Grbl itself, it is a GUI problem. You should post your issue in the relevant GUI Github

**Comment by rkreiple** [comment]
Can you point me to the 'relevant GUI Github'?

**Comment by gerritv** [comment]
You haven't provided any information to help you. Look at the name of the program you are using to 'visualize' and search for its web page. It is certainly not Grbl.

**Comment by rkreiple** [comment]
My apologies if I am in the wrong place, I thought this is the correct place.

I am using grblControl0.8, this is the screen shot of it running on system with the display problem.

![2017-02-20](https://cloud.githubusercontent.com/assets/25903233/23133542/b65b272a-f74e-11e6-8374-05cf0b569b02.png)

**Comment by gerritv** [comment]
You can find that  on github.com.
