### ISSUE TITLE
grblControl report  "Setting disabled"

### ISSUE THREAD

**Issue by vyuke** [grbl/grbl#1185]
Hi：The machine is currently working properly。But When I use the software: “grbl Control” When the HOME button is clicked, the software sends "$ H" to the machine and the machine returns “Setting disabled” How to solve this problem？pls help me！
![image](https://cloud.githubusercontent.com/assets/18086671/23214491/d36a8aca-f949-11e6-8840-b3702492357b.png)

**Comment by gerritv** [comment]
You should read the wiki pages on Configure Grbl. It tells you what you need to know.

**Comment by kamlesh613** [comment]
Hi GitHub faimaly 
When i press home button , software  is howing “Setting disabled” How to solve this problem？pls help me！
