### ISSUE TITLE
Homing direction

### ISSUE THREAD

**Issue by vyuke** [grbl/grbl#1188]
hello,I use the grbl version number is 0.9j, the GUI software is grblControl 0.8.4, i encountered a problem and i can not fix it in the homing function when the axis motion is wrong and i am modifying the direction of the code but The direction of movement does not change, please help me
![image](https://cloud.githubusercontent.com/assets/18086671/23332713/1475d86e-fbb9-11e6-9c0c-3f5e58878462.png)

**Comment by electrokean** [comment]
Don't change the default in the source code, change the configuration parameter $3
See https://github.com/grbl/grbl/wiki/Configuring-Grbl-v0.9

**Comment by electrokean** [comment]
Sorry, I mean $23

**Comment by chamnit** [comment]
You need to change settings with $ commands. Not the defaults file. This sets the EEPROM upon first flashing or a forced EEPROM reset. As usual, please try reading the wiki. This all covered there.
