### ISSUE TITLE
Need Grbl v0.8c please!

### ISSUE THREAD

**Issue by daruco** [grbl/grbl#1195]
Hi, can anyone help me please? i have some troubles with mi stepper motors on cnc machine and i need to download grbl v0.8c in order to discard reasons of the problem, but I don´t find it anymore! if someone could give me the link or send me that source code i will appreciate very much. thanks!

**Comment by chamnit** [comment]
Look at the commit history in the v0.8 branch. But it's highly advised to use the current master. Not old buggy versions.
