### ISSUE TITLE
The voltage in laser mode 

### ISSUE THREAD

**Issue by YExh00** [grbl/grbl#1201]
The maximum voltage of my laser engraver is 12v. And I don't know how to change the configuration in grbl of the maximum voltages from 5v to 12v. Could anyone help me?

**Comment by lalo-uy** [comment]
The arduni never works above 5v. You need an amplifier , a hexfet or power
transistor to drive the laser.

2017-03-15 12:03 GMT-03:00 Ye Xiaohua <notifications@github.com>:

**Comment by chamnit** [comment]
Wire in a circuit to convert Grbl's 0V to 5V signal to 0V to 12V, or whatever the voltage range of your laser is. This is not a Grbl problem, so I'm closing this issue.
