### ISSUE TITLE
Inverting limit switches should not disable internal pull-up

### ISSUE THREAD

**Issue by Harvie** [grbl/grbl#1219]
Hi,
i've understood that inverting logic of limit switches using $5=1 also leads in disabling internal pullup. I think this does not make any sense. You should physicaly read switch state same way for NC and NO switches. Only difference is that you should invert how you interpret that state in code.

I don't see how disabling internal pullup helps. Especially when most people go for NC setup because of noise, which can be partialy alleviated by using internal pullup.

**Please make inverting limit switch logic and disabling/enabling pullup a separate setting. I am sure people might want to set it independently.**

 Also there's no really need to use external resistor to prevent frying something. I don't know how this statement got into the documentation:

> NOTE: If you invert your limit pins, you will need an external pull-down resistor wired in to all of the limit pins to prevent overloading the pins with current and frying them.

it just doesn't make any sense... if connecting NC switch to arduino would fry something it would also be fried by NO switch as soon as it was triggered for the first time. I think you need to understand that there is no real electrical difference between NC and NO switches. the only difference between NC and NO is purely mechanical. they only differ in what mechanical motion makes them conduct electricity... but in the end all switches (no matter if NO or NC) are just two wires that sometimes touch and sometimes don't.

**Comment by chamnit** [comment]
@Harvie : Please don't double post. It's a waste of time for everyone.

**Comment by Harvie** [comment]
@chamnit sorry, i wasn't sure which repo is active. maybe you can disable issue tracker on inactive forks?

**Comment by chamnit** [comment]
@Harvie : No problem, but this site isn't a secondary fork. It's the repo for the older versions of Grbl v0.x. Grbl v1.1+ is at the gnea repository. It also clearly states that this site will be deprecated soon on the front page, as well as on the wiki. For reference, I monitor both sites closely for different reasons. So posting to one is sufficient.
