### ISSUE TITLE
Grbl Robot Arm

### ISSUE THREAD

**Issue by Molonky500** [grbl/grbl#1224]
Hello Im new to grbl,I hope this is the right place to post this, Im already making a CNC laser machine with it .But, I was wandering if GRBL can be used to make robot arms? If so is there any tutorials out there for me to follow? 
Thanks

**Comment by chamnit** [comment]
Robotic arms involve completely different and significantly more expensive math than what Grbl uses. Primarily due to mechanically dependent axes. CNCS usually assume independent to simplify the problem.
