### ISSUE TITLE
something is wrong  with safety swuches , ALARME: Homing fail  

### ISSUE THREAD

**Issue by cuchara** [grbl/grbl#1230]
Hello everyone

I just finished to installing the safety swuches, And I activate the parameters: 
```
$20=0 (soft limits, bool)
$21=0 (hard limits, bool)
$22=0 (homing cycle, bool)

```
But when I send the command $H , the Z axis begins to rise  antil it touches the safety swich, the axis stops
Console:
```
Grbl 0.9j [`$´for help]
[`$H´l`$ X´ to unlock]
ALARME: Homing fail
ok
```

No matter what I do, message repeated and I do not regain control of the machine. till I turn off and disconnect everything
Then I move the  Z axis with the hand to unlock the swich then I connect everything back

Console:
```
Grbl 0.9j [`$´for help]
[`$H´l`$ X´ to unlock]
ALARME: Homing fail
>>>>44
error:Alarm lock
```
And I restore the control when I turn off the alarm $X   

Try the homing many times and touched the switch with my finger to see what happens and nothing happens just stops but if I loose the swich it continues with its path till it blocks itself

What is wrong?

![captura de pantalla 2017-05-14 a la s 11 26 24](https://cloud.githubusercontent.com/assets/21206828/26032833/25565e30-389d-11e7-85bc-1f23e91a631a.png)

**Comment by vMeph** [comment]
to do only homing try with out soft limits and hard limits at 0 and do homing see what happens might work but for the hard limits sound like you have noise issues in your switches that will trigger a alarm, you might want to take a look at 
https://github.com/gnea/grbl/wiki/Wiring-Limit-Switches

**Comment by jahnj0584** [comment]
Sounds like it's wired backwards. Use a volt meter to test the continuity
and make sure it's behaving properly

**Comment by cuchara** [comment]
Hello
Thank you very much for the help
This is the way I connect the swiches https://okelectronic.files.wordpress.com/2015/07/mycnc_connections.jpg

Then what is the appropriate form or which do you recommend?

  I do not have the

**Comment by cuchara** [comment]
> to do only homing try with out soft limits and hard limits at 0 and do homing see what happens might work<

I did what you recommend and  happens the exact same thing

`>>>$H
ALARME: Homing fail`

**Comment by vMeph** [comment]
first make sure all switches wired correctly do a test like  @jahnj0584 suggested if all is ok
most like you have a noise problem witch is very common problem around here to fix noise issue problems there is many things you can do like shielded cables to you motors, proper groundings, and add pullp up resistors and capacitor to filter noise on switches read the link i sent you before is there alot information in how to approach this problem

**Comment by chamnit** [comment]
Soft limits and hard limits should not effect homing. Both are disabled when it runs. There are only a few things that would throw a homing fail alarm. Use Grbl v1.1 instead. It has better error codes to tell exactly what failed. Link to dv1.1 site on front page.

**Comment by cuchara** [comment]
That sounds good...  because at the moment I do not have capacitors . 
I'm going to try the Grbl v1.1 

  Thank.👍

**Comment by cuchara** [comment]
I already passed to GRBL V1.1  And my problems are other 

 I not only change the Grbl v.1.1  but also I change the steppers drivers  and I do not seem to achieve an optimal configuration,  I try changing everything

My motors Nema32
Specification:
For Motor Length 45mm:
Rotor Inertia
180 g.cm2
Step Angle
1,8°
Motor Length
45mm
Holding Torque
0.8N.m
Rated Current/phase
2A
Phase Resistance
2.1Ω±10%
Rated Voltage
4,2V DC
Inductance/Phase
5mH±20%(1KHz)


My drivers 4A TB6600
http://www.ebay.com/itm/Newest-4A-TB6600-Single-Axis-Stepper-Motor-Driver-Controller-for-57BYG250H-Motor/162217753430?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649
I have them set to:  

MicroStep  2/B  400

Current(A)  2.0

My  parameters
![screen shot 2017-08-28 at 17 39 34](https://user-images.githubusercontent.com/21206828/29788132-d1815fc4-8c31-11e7-87f1-c8b37a99d8cc.png)
![screen shot 2017-08-28 at 17 39 27](https://user-images.githubusercontent.com/21206828/29788131-d180c29e-8c31-11e7-9ad2-3a08689fc31a.png)
 The most common problem that occurs to me is that when the machine is cutting, automatically enter in  into pause and it automatically relaunches
 
Also when I change the speed of the spindle  manually grbl is enter into pause

But the one that puts in pause is not serious that bad...The worst problem is when he sends me error this is what is driving me crazy I have not been able to cut a piece without error. And to solve the error I have to restart everything from zero


![screen shot 2017-08-19 at 16 09 26](https://user-images.githubusercontent.com/21206828/29788108-b9a865be-8c31-11e7-8228-a9edc83a7e6d.png)


 Which means that I lose the position of the machine and it is very difficult to find the point 0 again manually

 This cost me many badly cut pieces and carbon plates in the trash
 What can it be?
 For now I have not tried the safety limits

**Comment by chamnit** [comment]
Something is triggering a soft-reset command mid-job, based on your `Alarm:3` code. Given you are running large NEMA32s, this likely means that there is electrical noise effecting the soft-reset pin A0. Place an RC filter on the A0 soft reset and any other control pins you have connected.

**Comment by cuchara** [comment]
Can you please give me an example of how to add an RC filter to the pins?
thanks in advance

**Comment by lalo-uy** [comment]
Check this

https://www.allaboutcircuits.com/uploads/articles/filtered-signal-v2.jpg

4k7 Rpull-up, 100 ohms serie R and 100nF cap will do

2017-09-04 15:57 GMT-03:00 cuchara <notifications@github.com>:

**Comment by cuchara** [comment]
mmmmm : /     so something like this ? 3
https://static.xx.fbcdn.net/rsrc.php/v3/y4/r/-PAXP-deijE.gif

**Comment by lalo-uy** [comment]
Just see a 1 pixel gif

2017-09-05 9:31 GMT-03:00 cuchara <notifications@github.com>:

**Comment by cuchara** [comment]
Sorry
  here it is:
https://scontent-cdt1-1.xx.fbcdn.net/v/t1.0-9/21369429_10154963293221239_603982951625439924_n.jpg?oh=48975306d4b97636cd716349031f02e9&oe=5A549501

**Comment by lalo-uy** [comment]
The pullup resistor is more important than the series one.


2017-09-05 15:18 GMT-03:00 cuchara <notifications@github.com>:

**Comment by cuchara** [comment]
The two are completely unfamiliar for my, I only attempt to understand how I have to connect the first diagram that you showed me

so can you explain it to me??

**Comment by vMeph** [comment]
@cuchara  take a look in wiki schematics for switches wiring to avoid eletrical noise
https://github.com/gnea/grbl/wiki/Wiring-Limit-Switches

**Comment by vMeph** [comment]
based on your diagram you want to do on all switches how you see on the Z limit
 thats a RC filter
![sem titulo-1](https://user-images.githubusercontent.com/12812111/30086933-b2c78d50-9295-11e7-8404-497d65b66bc0.gif)

**Comment by cuchara** [comment]
Many thanks for your support guys!I  greatly appreciate it.

 I still have questions :D 

I do not have a capacitor like the one they show me, but I have many others

-25v 10uf
-E103Z IKV
-102K IKV 88
-10V100uf
-16V 220uf
-16v 470uf
etc....

which one can I use as a replacement?

many thanks

**Comment by lalo-uy** [comment]
103 is the nears, but is 10 x less.
find some 104  = 100nF

2017-09-08 10:19 GMT-03:00 cuchara <notifications@github.com>:
