### ISSUE TITLE
Rate Grbl....

### ISSUE THREAD

**Issue by algo1980** [grbl/grbl#1240]
How do you rate Grbl firmware

1. Excellent
2. Good
3. Bad
4. Poor
5. Average.

**Comment by bluebriant** [comment]
1+++ !

**Comment by lalo-uy** [comment]
0 Excelent

2017-06-02 9:06 GMT-03:00 bluebriant <notifications@github.com>:

> 1+++ !
>

**Comment by X3msnake** [comment]
Excellent

**Comment by flaplante** [comment]
Excellent!

Fred LaPlante, WA1DLZ

**Comment by bluebriant** [comment]
0 Excellent

**Comment by lakeside53** [comment]
0 - excellent.  Tightest cleanest code I've seen for a long time.

-Andy

**Comment by algo1980** [comment]
a code that it can boost programming skills from beginner to advance level in a couple of months.

**Comment by mayhem2408** [comment]
GRBL is 1 (Excellent)
GRBL-LPC is 0 (Incredible. The fastest gcode parser I have seen. Faster and Smoother than a commercial UC100 controller.)
