### ISSUE TITLE
SPI and GRBL

### ISSUE THREAD

**Issue by Alexsem76** [grbl/grbl#1245]
Dear developers, developers and users of GRBL control, I ask you this question: arduino uno hardware spi has 74hc165 and 74hc595, nobody tried to use them to expand the possibilities, namely to deduce limits on them, control thereby freeing the pins for the 4- Rotary axis or spindle control? Sorry for my english if that did not say so. I work as an industrial automation engineer and I successfully use this method to expand the inputs of the outputs arduino. Maybe this will help. I'm not a C ++ programmer. It is difficult for me to realize.

**Comment by bluebriant** [comment]
Interesting thought. My level of knowledge in this regard is low. Could
anyone explain and say if this is possible? Freeing up additional pins on
the Uno would be welcome.

**Comment by vMeph** [comment]
I dont think that will be possible with arduino uno GRBL, sense there is no memory available, the litle memory that is avaliable is for fix possible bugs, this have been mention alot times

**Comment by vMeph** [comment]
I dont think that will be possible with arduino uno GRBL, sense there is no memory available, the litle memory that is avaliable is for fix possible bugs, this have been mention alot times

**Comment by Alexsem76** [comment]
А можно поинтересоваться где это упомянуто хочу почитать

**Comment by lalo-uy** [comment]
I believe that the UNO version has get as good as it can.
For a similar price tag there are ARM modules with much more
pins/ram//flash/Mhz
The evolution should go  that way.
My humble opinion.



2017-06-07 9:24 GMT-03:00 Alexsem76 <notifications@github.com>:

**Comment by chamnit** [comment]
SPI support is planned to be installed in the ARM version, which has been under development for over a couple of years and the initial release coming out soon. As it turned out, the new overrides in v1.1 fit on a 328p and was released for it until a few more things in the ARM version are worked out.

**Comment by Alexsem76** [comment]
Thank you very much, I will wait for new version 07.06.2017, 14:57, "Sonny Jeon" <notifications@github.com>:Closed #1245.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   --Sincerely, --Aleksey Semenov  Yaroslavl(920) 148-18-36
