### ISSUE TITLE
Grbl 1.1 $N0 & $N1 problem

### ISSUE THREAD

**Issue by mo7amedelhadi** [grbl/grbl#1247]
Hi ;

I am doing a cnc and i'm working with grbl, when I run the program will not look for the homing but it starts directly in the program gcode. 

I want to know what is the utility of $N , $N0 & $N1 ? Because when i modified $N0 and $N1 the cnc works in a space defines without any problem.

Thanks to all

**Comment by chamnit** [comment]
It sets the gcode modes to something that is non-default. For example, if you like to operate in inches mode, you can have a startup string place it in inches mode. Any automated motion can be highly dangerous. Grbl requires you to manually execute homing because of this.
