### ISSUE TITLE
data path 

### ISSUE THREAD

**Issue by abdelrahma22** [grbl/grbl#1254]
plz explain how the grbl translate g code into motion 
 //
what the data path to this code 
\\
what is the functionality  of every file
\\
plz help

**Comment by electrokean** [comment]
Please don't open issues asking for open-ended explanations, that is not what Github issues are for.  I doubt anyone has the spare time to explain things to you.

Spend some time reading the code (but start with the newer v1.1 as I linked in your last issue) and doing some of your own research [1].  Then if you have a specific question or issue, then ask those.

Also, keep in mind the code is under major refactoring at the moment for supporting newer CPU architechtures like ARM, so almost anything may/will change.

[1] as a starting point a bit of googling will turn up article like this one
https://onehossshay.wordpress.com/2011/08/21/grbl-how-it-works-and-other-thoughts/
which is a bit old, but written by someone who knows what they are talking about ;)

**Comment by abdelrahma22** [comment]
thanks
