### ISSUE TITLE
Machine Position

### ISSUE THREAD

**Issue by algo1980** [grbl/grbl#1262]
Hi i need to know which global variable holds machine co-ordinate data?

**Comment by electrokean** [comment]
I suggest you look at `report_realtime_status()` in report.c and see how it calculates the "display" value

**Comment by algo1980** [comment]
how much time do we have for an instruction without causing any error in smooth stepper action?

**Comment by chamnit** [comment]
@algo1980 : Depends on the size of the step segment buffer minus time to compute all other Grbl tasks. Generally, you have several milliseconds. Likely up to 10-15ms.
