### ISSUE TITLE
GRBL 1.1e for Atmega2560 Probe ERROR

### ISSUE THREAD

**Issue by migimantas** [grbl/grbl#1264]
Hello,
so I am having this issue I use grbl 1.1e with arduino mega 2560. For cnc milling I use Candle_1.1.7 and it has hightmap function for pcb milling. The problem is that when the probe touches plate machine stops and I get ERROR:9 
When doing just probe function I get in to allarm:3 state and get this message.
G21G91G38.2Z-30F100 < ALARM:3
ok
G0Z1
G38.2Z-2F10
Grbl 1.1e ['$' for help]
[MSG:'$H'|'$X' to unlock]

This is example video how it should work
[https://youtu.be/tK5Amg-Ye58](url)

And this is how it looks for me when the probe touches plate.
![capture](https://user-images.githubusercontent.com/23704414/28423269-4084d3f2-6d73-11e7-9f36-cc4bc08ce139.PNG)
I do homing cycle but still the same error.
I disable homing still the same error.

**Comment by chamnit** [comment]
Grbl is getting placed into an ALARM state for some reason. According to the wiki and other documentation, ALARM:3 is caused by a 'Reset while in motion'. Meaning your system is being reset for some reason. Maybe you have a reset button and its poorly isolated. error:9 is just the standard Grbl response for trying to command something in an ALARM state. It blocks all gcode.

**Comment by migimantas** [comment]
Somehow I only get this reset error when I am probing. The probe touches plate, it stops and the system shows error:3 and resets. 
Probe setting is
$6=0
Probe circuit is
![511568b7ce395f613f000004](https://user-images.githubusercontent.com/23704414/28439355-3398e1e2-6daa-11e7-932f-364076a7e23e.jpg)
Also I have noticed that when I do not engage Z in a movement but just touche probe contacts system just resets and no error:3. 
![capture](https://user-images.githubusercontent.com/23704414/28439404-6fc8a044-6daa-11e7-8355-e8e178c2b802.PNG)

**Comment by chamnit** [comment]
Please provide your $$ settings and your $I build info string. Also which pin is your probe connected to?

**Comment by migimantas** [comment]
I apologize for my stupidity. I have just noticed that  probe pin is MEGA2560 Analog Pin 15 and I have connected my probe pin to Analog Pin 11 and all the time I was shorting pin to GND and resting processor
