### ISSUE TITLE
GRBL 1.1 is biggetst shit on tne world

### ISSUE THREAD

**Issue by eddie99** [grbl/grbl#1276]
You DEV has completely failed on this version 0.9 was working as excepted  but v1.1 is a mess!!!!!

**Comment by jahnj0584** [comment]
Want to give an actual reason or are you just mad you can't get it set up

**Comment by tklus** [comment]
Good luck getting help with that attitude...

V1.1 has many big improvements abd does have differences than 0.9x...

**Comment by 109JB** [comment]
If you expect V1.1 to perform like 0.9 then you obviously didn't read the WIKI.  Why not try that first!!

**Comment by chamnit** [comment]
This guy likely didn't realize that the communication protocol changed due to having a lot more realtime data and that it requires a GUI that supports it. Either way, this topic is clearly designed to be inflammatory without any respect for others. No reason to continue this. Closing and blocking.
