### ISSUE TITLE
laser issue

### ISSUE THREAD

**Issue by Davida54** [grbl/grbl#1281]
when using laser, the laser is on when moving between positions and off when it should be burning. In other words its backwards.

**Comment by dutchpatriot** [comment]
Could you drop the gcode file here?

**Comment by daniele-salvagni** [comment]
The laser will fire when the output is low and not high, see here: https://youtu.be/Aj-kghLsdEI?t=310

**Comment by chamnit** [comment]
Grbl PWM output for lasers requires low for off and high for on. If your system needs the opposite, you will need to alter the spindle control source code to work with your system. 

Inverted PWM output is slated to be added at some point but I have zero time right now to work on it.  FWIW, it's not that difficult to alter the source.

**Comment by daniele-salvagni** [comment]
Wouldn't an hardware inverter be safer? I fear that the pin could be set low during initialization and fire the laser.

**Comment by chamnit** [comment]
Sure. Do whatever is appropriate for your machine. There are an infinite number of ways to deal with the initialization problem. That would be one.

**Comment by Davida54** [comment]
I got it. Thanks for help

David

On Sep 5, 2017, at 4:41 PM, Sonny Jeon <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure. Do whatever is appropriate for your machine. There are an infinite number of ways to deal with the initialization problem. That would be one.
