### ISSUE TITLE
Am I missing something? Spindle PWM

### ISSUE THREAD

**Issue by jahnj0584** [grbl/grbl#1282]
VFD won't power on with the arduino! Am I missing something basic?

PWM #11 goes to VI 
Spindle direction #13 in FOR 
Ground of arduino to ACM 

When i send M3 S24000 I get 4.72v across VI and GRD so the PWM does work. M5 drops it to 0.01v

In UGS I set Max spindle RPM ($30) to 24000 and min is 0. 

I have VFD settings 001 and 002 to 1 for outside control source. If these are set to 0 the control buttons control the spindle. 

PD0070 is 1 to accept 5v PWM instead of the usual 10v

Do I need to comment something in .config? Is #11 the pwm by default for grbl 1.1?

**Comment by bretonesf** [comment]
Hi, I kind have the same problem as you had, can you tell me how you fixed it? Many thnaks in advance
