### ISSUE TITLE
Is there a command that stops all motors.

### ISSUE THREAD

**Issue by StuartB4** [grbl/grbl#1285]
I've noticed people talking about using M18 on some machines to stop all motors so that no current is present and they can be moved freely. Can GRBL do it with a different command because M18 is not recognised as a valid command.

Thanks.

**Comment by jahnj0584** [comment]
Setting $1 to anything below 255 will stop the flow of current after a move
is made

**Comment by StuartB4** [comment]
Ok jahnj0584, thanks very much.

**Comment by PicEngraver** [comment]
Stopping current to the motors means risking they may shift position slightly when the current resumes.   I, for one, choose to not risk that, and I maintain $1=255 all the time.

**Comment by StuartB4** [comment]
I'm not bothered about it shifting position as I only want it to release the motors after finishing a job.

**Comment by chamnit** [comment]
There is a sleep command that will do what you want. See the wiki commands page.

**Comment by chamnit** [comment]
It is only available on Grbl v1.1.

**Comment by StuartB4** [comment]
Ok chamnit. Thanks very much.
