### ISSUE TITLE
Stop acceleration between each movements ?

### ISSUE THREAD

**Issue by Gruniek** [grbl/grbl#1290]
Hello,

I using the GRBL 1.1 for use my own 2,5W laser.
But I have an acceleration between each mouvements and he burn not uniformy.

That's possible to remove the acceleration mode ?

Thank you!

PS : Awesome projec! Nice !

**Comment by chamnit** [comment]
Use M4 dynamic mode and increase your machine acceleration settings.

**Comment by Gruniek** [comment]
ok thanks!
