### ISSUE TITLE
How to know when Grbl is done with its current motion segment?

### ISSUE THREAD

**Issue by ajohansson-git** [grbl/grbl#1296]
I would like to get an alert/acknowledgment once a specific Gcode line has been completely executed in terms of movement. I suppose making a custom mod of the Grbl codeset is the only way?

The 'OK' message sent by Grbl is useful but this is for when a Grbl command is received and acknowledged, as opposed to after the command being implemented as motion and completed.

The '?' character gets a status report but I'd have to keep periodically sending '?' queries from the PC (polling vs. event-based trigger).

**Comment by chamnit** [comment]
Send a G4 P0.001 dwell command immediately after the line you are interested in. When that returns an ok, your gcode line was just completed. A G4 dwell requires a planner sync and all queued motions to complete prior to executing. THat's why this works.
