### ISSUE TITLE
Using grbl without Universal-G-Code-Sender

### ISSUE THREAD

**Issue by menanagy** [grbl/grbl#1299]
I want to control  one stepper motor by using grbl without Universal-G-Code-Sender..
or 
How to make another  Arduino send the command to Arduino_grbl  instead of Universal-G-Code-Sender

**Comment by winder** [comment]
Everything you need to know is documented on the wiki:
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface

If you want to jump right into it look at one of the [stream scripts](https://github.com/gnea/grbl/tree/master/doc/script) and make something similar for the arduino.

On the GRBL side you can hook right into the RX/TX pins, just send `Ctrl-X` when you boot the master arduino to make sure a connection is established.
