### ISSUE TITLE
Where can i find A5 pin for touch plate g38.2

### ISSUE THREAD

**Issue by mogey336** [grbl/grbl#1300]
Where can i find a5 pin for cnc sheild v3?

**Comment by vMeph** [comment]
using a nultimeter easy to find 
on cnc shield will be where it say SCL blue conectors

**Comment by mogey336** [comment]
@vMeph Thanks

**Comment by vMeph** [comment]
@mogey336  what version of grbl you using with cnc shield v3?
if you use grbl 0.9 or higher you will need to make changes on the cnc shield cause  grbl 0.9 and higher there was a swap between pin 12 and 11
