### ISSUE TITLE
stepper motors not moving, well one is, but only in one direction

### ISSUE THREAD

**Issue by AndySmith1967** [grbl/grbl#1318]
so bought my self a  DIY CNC Router Engraving Kit, Working Area 240*170*65mm, PCB CNC Milling Machine Wood Metal Carving Mini Engraving Router PVC, from amazon. 
machine arrived fairly quickly and build didnt go to badly, few small hiccups me no taking notice which way things went.

The problem i have is that none of the motors work with the grbl controller. Well thats not strictly true, one works but only goes in one direction.

When I start the controller software I get this message
[CTRL+X] < Grbl 1.1z ['$' for help]{8kdz.com}

entering $$ gives me this info

$$ < $0=10
$1=25
$2=0
$3=0
$4=0
$5=0
$6=0
$10=1
$11=0.010
$12=0.002
$20=0
$21=0
$22=0
$23=0
$24=25.000
$25=500.000
$26=250
$27=1.000
$30=1000
$31=0
$32=0
$80=0
$81=0
$82=4
$100=200.000
$101=200.000
$102=200.000
$110=5000.000
$111=5000.000
$112=500.000
$120=20.000
$121=20.000
$122=20.000
$130=200.000
$131=200.000
$132=200.000
ok

When i press the jog buttons this happens (ive got it set to move 5mm
x- i hear a noise but nothing happens
x+ i hear a noise but nothing happens
y- the motor steps right by 5mm
y+ the motor steps right again by 5mm
z- i hear a noise but nothing happens
z+ i hear a noise but nothing happens

I have tried connecting the y axis cable to all three motors and they all move so assume the motors are good and the problems lies elsewhere.

I conntacted the seller who said re flash the firmware with no further explantion. Any help on this would be a big help as i haven't a clue where to start.

I have attached a few pics of the cuircit board. I haven't a clue what type it is (una??Mega??)

Again any help identifying board may help find a solution.

I am new to this and to be honest after three days of looking at my expensive paperweight i am a little downhearted.

Thanks for any help you can give.
![control board wiring](https://user-images.githubusercontent.com/33575239/32690828-de602b1e-c6f4-11e7-82ca-5b87e9e1b9ef.jpg)
![20171111_144208_resized](https://user-images.githubusercontent.com/33575239/32690831-e8988acc-c6f4-11e7-8ed1-446c58dd3b55.jpg)
![20171111_143951_resized](https://user-images.githubusercontent.com/33575239/32690832-ea352c14-c6f4-11e7-8109-af99a1625956.jpg)
![Uploading 20171111_144009_resized.jpg…]()

**Comment by chamnit** [comment]
Unfortunately there is no such thing as v1.1z. This looks like a manufacturer forked Grbl and made their own custom changes to the firmware. I can’t help you with these alterations or if they cause problems. 

But you problem has to do with the stepper driver current setting on the small drivers. There are little trim pots that set this. You’ll need to measure the current in your stepper wires as you adjust it and must be set it somewhere below the stepper amp rating. Be careful though, the drivers get hot when set too high and require cooling. So just increase it slowly and set it a bit below when the steppers drivers get too hot and start to thermally shutdown.
