### ISSUE TITLE
RPM sensor

### ISSUE THREAD

**Issue by goloplo** [grbl/grbl#1320]
I know is not a real issue, but is there any way to add an IR sensor that can use one of the left pins and to display the RPM of the spindle?
Thank you.

**Comment by mschorer** [comment]
hi,

i have a leonardo with a display doing pid rpm control and obviously
display rpm ...

pls see https://github.com/mschorer/grbl_mc and related
https://github.com/mschorer/grbl

cheers,

markus schorer mobile

**Comment by chamnit** [comment]
I just built one for my lathe. A hall sensor and a magnet on the spindle. A spare arduino just reads the hall sensor and runs a simple LCD. Super easy.
