### ISSUE TITLE
Bug Bounty program

### ISSUE THREAD

**Issue by Chokoabigail** [grbl/grbl#1325]
Is there a Bug Bounty program?
If so where can I find more details about her?
(More details = what bugs are accepted, what is the minimum payment, what form of submission accepted , who to submit my founding, etc.)

**Comment by chamnit** [comment]
There is no bug bounty program. There are only a couple of minor bugs that I'm aware of. Neither of which effect performance. If you found one, please post your issue, version info, settings, and steps to reproduce it. The vast majority of issues are related to electromagnetic problems like interference and grounding. Neither of which are firmware issues.
