### ISSUE TITLE
motors dont move config error

### ISSUE THREAD

**Issue by Desuza** [grbl/grbl#1331]
I have no problem on power supply, and I have cnc shield and tb6560 and all was working good, but now nothing move at all, and when try to reupload grbl I got this error In file included from C:\Users\acc\Documents\Arduino\libraries\grbl/config.h:30:0,

                 from C:\Users\acc\AppData\Local\Temp\arduino_modified_sketch_71775\grblUpload.ino:1:

C:\Users\acc\Documents\Arduino\libraries\grbl/grbl.h:68:4: error: #error "Required HOMING_CYCLE_0 not defined."

   #error "Required HOMING_CYCLE_0 not defined."

    ^

C:\Users\acc\Documents\Arduino\libraries\grbl/grbl.h:108:4: error: #error "WCO refresh must be greater than one."

   #error "WCO refresh must be greater than one."

    ^

C:\Users\acc\Documents\Arduino\libraries\grbl/grbl.h:111:4: error: #error "Override refresh must be greater than zero."

   #error "Override refresh must be greater than zero."

    ^

Multiple libraries were found for "config.h"
 Used: C:\Users\acc\Documents\Arduino\libraries\grbl
 Not used: C:\Program Files (x86)\Arduino\libraries\grbl
 Not used: C:\Program Files (x86)\Arduino\libraries\grbl
 Not used: C:\Program Files (x86)\Arduino\libraries\grbl
 Not used: C:\Program Files (x86)\Arduino\libraries\grbl
exit status 1
Error compiling for board Arduino/Genuino Uno.
What cause this error, and could this be the reason that nothing moves, and how to fix it, notice I am using Chinese arduino?

**Comment by chamnit** [comment]
You have to follow the instructions exactly. Note the part that talks about selecting the right folder.
