### ISSUE TITLE
position standalone GRBL

### ISSUE THREAD

**Issue by sadezohdi** [grbl/grbl#1358]
Hello
I'm writing a standalone grbl. I used the following code to get the position, but the position is displayed with a delay. What is your offer to solve the problem?
I used two arduino.

while(1){

  String get_rx=" ";
    
   Serial3.println('?');
   get_rx=Serial3.readString();
   get_rx.trim();
 
    if(get_rx.substring(1,5)=="Idle"){
  
      
      break;
     }
 
   if(get_rx.substring(1,4)=="Run"){

//print positon                              
                      
   
    if(get_rx.length() <= 11){
        break;
                  
                 }
                 
              
            }
     }

**Comment by chamnit** [comment]
You clearly don't understand how Grbl works. Read the Grbl Interface Wiki.
