### ISSUE TITLE
Headless Controller / Streamer - Configuration

### ISSUE THREAD

**Issue by komradebob** [grbl/grbl#136]
Picking up where we left off in the Advanced Commands/configuration discussion, this thread is to discuss the design,config, and implementation of a headless controller.

The general concept is of a device that can connect to a grbl controller and stream gcode from an SD card to the grbl controller in place of a PC.

The goals are:

0) Open Source HW and SW.
1) Keep it simple to build.
2) Keep it simple to use.
3) Keep it cheap. See rule #1. 

In support of this, I would further say:

1) Use off the shelf components whenever possible, both hw and sw. An Arduino using existing libraries and shields for example. 
2) Stay away from goofball user interfaces. A few buttons, maybe a menu or two and not much more. 
3) This can conflict with using off the shelf parts sometimes. I'd love to use a 3" touchscreen shield, but at $55 a clip is a bit much. But against the complexity of driving a $7 600x400 pixel display it starts to look good. 

My feeling is to start with the simplest implementation, namely, an arduino with an SD card reader that reads a file found in the root directory named 'mygcode.g' and streams it out to the controller over a serial port at a predetermined baud rate/etc. 

Issue 1: Since you cannot connect arduino to arduino via USB, this will require using standalone serial ports or possibly interconnecting the two by simply doing a crossover on pins 0 and 1 (plus gnd of course). Has anyone tried this?

Later enhancements:

LCD Display - This can be used to show the code streaming by, pick a file from the SD card, configure the device, or any number of other functions. Start with a 4 line x 16 character display (because I have a bunch). Use it to watch the code go by. Later enhancements would be to go to a graphical display. 

Buttons - Could be used for jogging, starting or stopping the stream, configuring the device, etc. My feeling is that I'll probably start with eight buttons; jog +/- in 3 axis, start stream, and a spare, then go to an i2c keyboard (again, because there is one in the drawer) and use that.

Different platform - I'll probably do a bunch of this on atmega128 once I get off the initial arduino, again, because I have a drawer full of them. And they have more pins/space. 

Comments welcome. SD card reader and LCD shield donations welcome too ;)

**Comment by AsadollahA** [comment]
Hi
I want to make a Headless CNC that it work without PC
Can you help me to make it step by step?

**Comment by AsadollahA** [comment]
I want to it work by GRBL
