### ISSUE TITLE
Status report, mask: How to show hard limit status?

### ISSUE THREAD

**Issue by net-split** [grbl/grbl#1378]
I just updated GRBL to v1.1.
On older versions setting the $10 (Status report mask) to 19 would make "?" show the current status of the hard limits.
This doesn't seem to work anymore. On the Wikipedia it only mentions 3 report types for $10: (0,1,2) and none of those include the hard limit status. (I have hard limits enabled)
Is there any way to show this with the current GRBL version? For debugging / building a machine this is a very handy feature.

**Comment by chamnit** [comment]
Limit switch state reporting is standard on v1.1. It’s described in the interface wiki page.
