### ISSUE TITLE
Helpppppppppppppppppppppp

### ISSUE THREAD

**Issue by frobert0** [grbl/grbl#1384]
do not make grbl 1.1 into a grbl-sim.

make constantly shows errors

please help, someone can send me a finished grbl-sim

sorry bad english, google translate

Robert

**Comment by Rob2029** [comment]
What language do you speak?

**Comment by chamnit** [comment]
Grbl sim hasn’t been updated for v1.1. I don’t plan on working on it.

**Comment by frobert0** [comment]
Österreich / Deutsch

2018-04-07 16:33 GMT+02:00 Rob2029 <notifications@github.com>:
