### ISSUE TITLE
Y Axis is off by 1mm

### ISSUE THREAD

**Issue by RyanNelwan** [grbl/grbl#1385]
Issuing: 

> G1 Y10 F200

Places the y axis at 11 rather than 10. Not sure why this is.

> <Idle|MPos:10.000,11.000,0.000|FS:0,0>

**Comment by Norwegian-Gadgetman** [comment]
And if you move to Y100, where does it end up then?

**Comment by jahnj0584** [comment]
https://nathan7.eu/stuff/RepRapCalculator/RepRapCalculator.html#MotorStuffPrecise

**Comment by Rob2029** [comment]
What grbl controller are you using?

**Comment by RyanNelwan** [comment]
An arduino + gshield. 

Do you think it's worth re-installing GRBL onto it?

**Comment by Rob2029** [comment]
Maybe, but try also different grbl controllers like chillipeppr, UGCS or
Bcnc to see if the error persists

**Comment by jahnj0584** [comment]
Ryan, you do understand what calibrating your steppers will do right?

**Comment by RyanNelwan** [comment]
@jahnj0584 Yes I do. However, I'm strictly talking about software here and not concerning myself with actual machine movements. 

Out of the box on a freshly new install of GRBL and issuing a command of

> G1 Y10

should give me a read out of

> <Idle|MPos:10.000,10.000,0.000|FS:0,0>

And not

> <Idle|MPos:10.000,11.000,0.000|FS:0,0>

@Rob2029 I tried running the same command with UGCS and gave me the same output. Going to now try and re-installing GRBL onto my arduino.

**Comment by Norwegian-Gadgetman** [comment]
One question...   
Are you in G90 (absolute coordinates) or G91 (relative coordinates) ?

**Comment by langwadt** [comment]
Work coodinates vs. Machine coordinates

**Comment by RyanNelwan** [comment]
@Norwegian-Gadgetman @langwadt Absolute coordinates.

**Comment by RyanNelwan** [comment]
Here's a video running gcode sender

https://youtu.be/TyYQbbWrhC8

**Comment by chamnit** [comment]
You have a work coordinate offset of 1.0 mm. You are executing the moves in work coordinates and viewing the machine coordinates. It’s working properly.
