### ISSUE TITLE
ID33 with UGS

### ISSUE THREAD

**Issue by renepaats** [grbl/grbl#1392]
i need help with the following code
it's generate a ID33: motion command target is invalid

Thanks in advance

G17 F75
G0 X0 Y0 S0
G2 X0 Y10 I0 J10 S300
G0 X0 Y0 S0
G3 X0 Y30 I0 J10 S300
G0 X0 Y0 S0
M05 S0

using grbl1.1 and UGS   $12=0.002

**Comment by chamnit** [comment]
You are commanding impossible arcs. The target and initial position do not lie on the arc with the radius you specified. I and J are the offset locations of the arc center from the initial position
