### ISSUE TITLE
Trying to enable Laser Mode on GRBL 1.1f

### ISSUE THREAD

**Issue by StuartB4** [grbl/grbl#1393]
Every time I try to set $32 to 1 to enable laser mode I just get Error 17
"Error 17 Laser mode requires PWM output."

What do I need to do to stop it.
I have an Arduino UNO with GRBL 1.1f installed.

I have checked the config h file so that the PWM signal goes to pin 11 on the Arduino.
It looks like this:
**// Enables variable spindle output voltage for different RPM values. On the Arduino Uno, the spindle
// enable pin will output 5V for maximum RPM with 256 intermediate levels and 0V when disabled.
// NOTE: IMPORTANT for Arduino Unos! When enabled, the Z-limit pin D11 and spindle enable pin D12 switch!
// The hardware PWM output on pin D11 is required for variable spindle output voltages.
#define VARIABLE_SPINDLE // Default enabled. Comment to disable.**

I have a TTL Laser driver board with the TTL + going to pin 11 on the Arduino.

Am I missing something?

Thanks.

**Comment by chamnit** [comment]
This error is generated only if VARIABLE_SPINDLE is not defined. It's hard coded into the source code. You are probably editing the wrong file.

**Comment by StuartB4** [comment]
As you can see from what i posted, variable spindle is defined.
So now what?

**Comment by StuartB4** [comment]
Thanks for the help.
