### ISSUE TITLE
Jerk relief

### ISSUE THREAD

**Issue by MARIOBASZ** [grbl/grbl#1394]
Could you implement some jerk relief by adding some intermediate point (or more) in the trapezoidal profile of acceleration?
I think something like acceleration is a part (example 1/3) of the established to reach a certain speed and between this speed and zero.
For trochoidal cutting mode it would be good to increase the acceleration with fewer jerks.

![image](https://user-images.githubusercontent.com/11743403/39636822-b5f7315a-4f97-11e8-9ebe-1e776bb40b7f.png)

**Comment by chamnit** [comment]
Its been planned for a long time. But the AVR does not have the processing power to compute them, and it’s not a trivial solution. It’s coming to the ARM version. Be patient.
