### ISSUE TITLE
Homing fails

### ISSUE THREAD

**Issue by Delaser** [grbl/grbl#1396]
Hopefully user error, but I'm stumped on the issue.

Just updated my laser to GRBL 1.1f
Using an uno/gshield V3
LaserGRBL v2.8.45

Everything was working fine before the update.
Post update, when I hit the find Home button, from both bottom tray, custom button and Grbl menu in LaserGRBL, I get:
Homing Fail. Could not find limit switch within search distances.
Try increasing max travel or decreasing pull-off distance or check wiring.

Now, that would make sense, however the homing button doesn't even attempt to move towards my limit switches, it just hangs for a moment then throws the error.

My hardware switches otherwise work fine, laser triggers ok, jogging works no issues.

My config export is here:
 
$0=10 (Step pulse time)
$1=25 (Step idle delay)
$2=0 (Step pulse invert)
$3=1 (Step direction invert)
$4=0 (Invert step enable pin)
$5=0 (Invert limit pins)
$6=0 (Invert probe pin)
$10=1 (Status report options)
$11=0.010 (Junction deviation)
$12=0.002 (Arc tolerance)
$13=0 (Report in inches)
$20=0 (Soft limits enable)
$21=1 (Hard limits enable)
$22=1 (Homing cycle enable)
$23=3 (Homing direction invert)
$24=2500.000 (Homing locate feed rate)
$25=5000.000 (Homing search seek rate)
$26=0 (Homing switch debounce delay)
$27=10.000 (Homing switch pull-off distance)
$30=1000 (Maximum spindle speed)
$31=0 (Minimum spindle speed)
$32=1 (Laser-mode enable)
$100=160.000 (X-axis travel resolution)
$101=160.000 (Y-axis travel resolution)
$102=1.000 (Z-axis travel resolution)
$110=2000.000 (X-axis maximum rate)
$111=2000.000 (Y-axis maximum rate)
$112=2000.000 (Z-axis maximum rate)
$120=500.000 (X-axis acceleration)
$121=500.000 (Y-axis acceleration)
$122=100.000 (Z-axis acceleration)
$130=160.000 (X-axis maximum travel)
$131=190.000 (Y-axis maximum travel)
$132=200.000 (Z-axis maximum travel)

Thanks for your time.

**Comment by chamnit** [comment]
Read this [FAQ](https://github.com/gnea/grbl/wiki/Frequently-Asked-Questions#how-do-i-configure-my-homing-cycle-to-just-do-2-axes-or-i-have-a-pen-plotter-and-dont-have-a-z-axis)
