### ISSUE TITLE
Unlock button does not turn red unless Homing is active

### ISSUE THREAD

**Issue by 1Metalguru** [grbl/grbl#1404]
This is a relatively minor bug, but the Unlock button and the Status box do not turn red on connect or on reset if the Homing is not enabled (no homing button).  If the Homing is enabled in the GRBL settings window, all 3 buttons turn red on startup, connect, or reset.

It appears that the Unlock button still works, you just cant tell if anything happens when you push it.

V 1.0.9.17

Metalguru

**Comment by 109JB** [comment]
This is an issue with a user interface, not Grbl. You need to send this to the developer of the interface.
