### ISSUE TITLE
Code decomposition

### ISSUE THREAD

**Issue by vladtcvs** [grbl/grbl#1417]
Hi!

Grbl is a good project, but it's code can be decomposed to arduino-related code, and math, gcode, etc code, which is arduino-independent. There are many port of grbl to different controllers, such as stm32 and other. I think, if arduino-independent code will be separated into library, it whould be much easier to port grbl to other archs, and bug fixes or improvements in this library will be useble for ports too.

So will start this decomposition.

**Comment by chamnit** [comment]
Yes. Agreed. A hardware abstraction of Grbl has been worked on for the last couple of years or so. It’s nearing release and designed to be portable, particularly for ARM chips. It’s not publicly available until the beta release.
