### ISSUE TITLE
laser enngraver not getting connected with GRBL software

### ISSUE THREAD

**Issue by joel741174** [grbl/grbl#1422]
![grblsend](https://user-images.githubusercontent.com/42007354/43994862-e42649e4-9d58-11e8-9f5b-8ebe2cdc9516.PNG)
my chinese supplier didnt give me one wire connecting stepper motor to the grbl CONTROL BOARD.
so i thought in the mean time i will set up the remaning config....installed grbl laser soft..driver340ser .then i connected all the power usb to pc.the pc detected com3...then i clicked connect...but it is not connecting...why is that? is it becos i didnt  connect one stepper motor(Yaxis) to the control board?

**Comment by mayhem2408** [comment]
@joel741174 Check the Baud rate of your control board. Probably something simple like that.

**Comment by joel741174** [comment]
thankyou it worked :)
