### ISSUE TITLE
Possible ID 10T Error

### ISSUE THREAD

**Issue by Ajb2k3** [grbl/grbl#1455]
I'm trying to control a turntable driven by one stepper but I'm struggling to get in dialed in.
The stepper is connected to the "Z" port however 
`G91 X0Y0Z1 F30`
isn't moving it one step or 1.8 degrees clockwise.
Can you tell me what I'm missing?

**Comment by mayhem2408** [comment]
Z1 is not telling GRBL to more 1 step, it is telling it to move one millimeter. You need to make sure you $102=1 to tell GRBL that there is 1 step per millimeter.

**Comment by Ajb2k3** [comment]
Can you point me to a referance on it please?

**Comment by mayhem2408** [comment]
>           Can you point me to a referance on it please?

To understand Gcode itself you can have a read of
[](https://en.wikipedia.org/wiki/G-code)

and for the GRBL settings you can read
[](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration)

**Comment by Ajb2k3** [comment]
> > ```
> >       Can you point me to a referance on it please?
> > ```
> 
> To understand Gcode itself you can have a read of
> https://en.wikipedia.org/wiki/G-code
> and for the GRBL settings you can read
> https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration

Thank you. 
I thought it was an ID 10 T error all along (idiot).
