### ISSUE TITLE
Motor hour counter

### ISSUE THREAD

**Issue by Harvie** [grbl/grbl#1456]
Hi, do you think it's possible to add motor hour counter? So we can keep track of how long are our machines running? Idealy it might be configurable as option, so i can copy it using $$ and restore it along with configuration when i change arduino or reinstall grbl. But it should not write too often to eeprom.

**Comment by chamnit** [comment]
That would be a nice addition. I can add this to the list of things to add eventually in the next version. I would imagine this could be an additional line in the $I info output.

**Comment by chamnit** [comment]
I should add that the current 328p version does not have an available timer to keep track of this anyhow.
