### ISSUE TITLE
Engraving Results not As Intended

### ISSUE THREAD

**Issue by cdaileyjr** [grbl/grbl#1457]
Hello,

I am getting so close to making my CNC router work, but yet little things get in the way.

Attached is a copy of my GRBL settings and project gcode.

I've also attached a picture of what I thought was a simpler project.

As you can see the "E" turned out beautifully.

But after that, everything went going wrong.

Before starting the "F", the Z axis did not not raise to safe travel height.  Then it plunged into the work well beyond the maximum depth.

This is very frustrating.    Any help would be greatly appreciated.

Thank you,

Calvin

[FE - F Engrave gcode.txt](https://github.com/grbl/grbl/files/2540026/FE.-.F.Engrave.gcode.txt)
![fe project](https://user-images.githubusercontent.com/43617235/47878641-6e714880-dde4-11e8-9660-3ae64da4b53e.jpg)
[GRBL Settings.txt](https://github.com/grbl/grbl/files/2540042/GRBL.Settings.txt)

**Comment by chamnit** [comment]
You depth of cut is too aggressive and your CNC is losing steps. Also your x axis acceleration is pretty high. This will reduce your x-axis' resistance to losing steps.
