### ISSUE TITLE
G-Code sanity check

### ISSUE THREAD

**Issue by Harvie** [grbl/grbl#1460]
In bCNC we had issue, that one of our users was sending invalid g-code to GRBL and it caused weird behavior. I think GRBL should throw some error in such case:

[drawings-of-tigers-tiger-drawings-related-keywords-amp-suggestions-tiger-drawings(270мм X 210мм).cncR.zip](https://github.com/vlachoudis/bCNC/files/2560991/drawings-of-tigers-tiger-drawings-related-keywords-amp-suggestions-tiger-drawings.270.X.210.cncR.zip)

https://github.com/vlachoudis/bCNC/issues/1035

The user tried to convince me that g-code is OK (because GRBL accepted it) and blame the problem on bCNC. If GRBL poped an error it would be clear that the g-code is invalid and we wouldn't need to solve this.

Code looks like this:

```
[Блок №91301]   
G0 Y267.127 X46.646
G1Z-5
G0Z1
[Блок №91302]   
G0 Y267.059 X47.965
G1Z-5
G0Z1
[Блок №91303]   
G0 Y267.092 X48.878
G1Z-5
G0Z1
[Блок №91304]   
G0 Y266.925 X49.353
G1Z-5
G0Z1
```

**Comment by chamnit** [comment]
@Harvie : No. This g-code is not ok. Grbl rejects the [] bracketed lines and returns an `error:Invalid entry`. This can be checked by simply streaming to Grbl directly or hand writing this g-code to grbl.
