### ISSUE TITLE
Override Reset & Unlock?

### ISSUE THREAD

**Issue by AcrimoniousMirth** [grbl/grbl#1464]
Hi,
So, loving my CNC and by and large loving GRBL. I had a few noise issues triggering the end stops, the most notable being the spindle, but as far as I could see it only triggered when powering on to start with. However, I've had it stop for erroneous "Hard Limit" errors in the middle of cuts a few time now. Unfortunately I don't see a way to override that and resume from where I was because the reset button wipes my cut progress.
Suggestions or advice?
Thanks, all!

**Comment by AcrimoniousMirth** [comment]
@jahnj0584 It isn't, no, just wanted to know if there was a quick allowance. I have all of my switches running between 5V and GND so they're either one or the other and never floating, I have ferrite beads around every wire EXCEPT the spindle (because I haven't got any large enough yet) and because I'm in the UK everything goes to a common ground as per standard.
I was just hoping I'd be able to do some more test cuts while waiting for my wider ferrite beads to arrive.

**Comment by PicEngraver** [comment]
I gave up on hard limits a while back due to the same issue you describe, and switched to the use of soft limits, which are a brilliant solution by Sonny IMO.

**Comment by AcrimoniousMirth** [comment]
@PicEngraver I have those enabled too! I'll need to look into them further but my main concern is how much my motors could move when I'm messing with the spindle (as its an easy moving system) so the hard limits to home to a fixed known location are handy! I think I saw an option to ignore hard limits while running though, is that what you're referring to?

**Comment by PicEngraver** [comment]
Having hard limits ($21) enabled is not needed or used to home a machine, only the home setting ($22) is used for that.  On my system I have:
$20=1
$21=0
$22=1

**Comment by chamnit** [comment]
Hard limits invoke a sudden and immediate stop to motion. A loss of steps and position is likely. You need to rehome after it happens. Resuming from a point in the middle of a program is not trivial. Gcode is a modal language. You have to ensure all of the modes and relative positions are set correctly before resuming. A GUI can theoretically do this but I have not seen any yet.
