### ISSUE TITLE
Motors does not work

### ISSUE THREAD

**Issue by RafatCAD** [grbl/grbl#1465]
I don't know where is the problem , motors work when I use repetier host, but does not work in Grbl all thing I think it is correct , but I don't know where is problem ,
![whatsapp image 2018-11-19 at 5 35 32 pm](https://user-images.githubusercontent.com/45174294/48717370-f26b6300-ec21-11e8-8fd4-3183fc683f1f.jpeg)

**Comment by RafatCAD** [comment]
![whatsapp image 2018-11-11 at 9 59 19 pm](https://user-images.githubusercontent.com/45174294/48715393-9acaf880-ec1d-11e8-9b38-9bbd9485800c.jpeg)
![whatsapp image 2018-11-19 at 5 04 32 pm 1](https://user-images.githubusercontent.com/45174294/48715395-9b638f00-ec1d-11e8-886e-51a081406d85.jpeg)
![whatsapp image 2018-11-19 at 5 04 32 pm](https://user-images.githubusercontent.com/45174294/48715396-9b638f00-ec1d-11e8-9601-08958bebc9bd.jpeg)
![test_grbl](https://user-images.githubusercontent.com/45174294/48715420-a4546080-ec1d-11e8-9fe3-12f838d18622.PNG)

**Comment by svenhb** [comment]
You didn't enabled Homing - as the response says: "Homing cycle failure. Homing is not enabled"
Read here: https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration
$22 will enable homing.
But for first use you should avoid homing, first setup directions, end switches and so on.

**Comment by svenhb** [comment]
You use version 1.1g. The latest official release is 1.1f... What is the difference?

**Comment by RafatCAD** [comment]
1.1g this is for mega

**Comment by chamnit** [comment]
1.1g is a bug fixed version on both the 328p and Mega. Mostly minor bugs.

**Comment by svenhb** [comment]
You should check the wiring of the motor-shield. I remember a similar looking shield were clk and dir was switched (compared to usual Arduino grbl pinout).

**Comment by svenhb** [comment]
The one I mean is from banggood (CNC-Shield-V4-With-Nano-3_0-A4988), if you follow the conductor track you find "dir" (pin 1) of one driver connected to D2 ="stp" of default grbl.

**Comment by svenhb** [comment]
For the mega, the default X_dir is on Pin 30: https://github.com/gnea/grbl-Mega/wiki/Connecting-Grbl-Mega
But for the Ramps 1.4 shield, X_Dir is connected to A1: https://reprap.org/mediawiki/images/f/f6/RAMPS1.4schematic.png
Probably that is the problem.

**Comment by RafatCAD** [comment]
I test my project on UNo everything works, I try to put cnc sheild on mega it also doesn't work . 
I think mega have something must change  on CPU .h .

**Comment by RafatCAD** [comment]
I use mega because I need at least 4 motors

**Comment by terjeio** [comment]
Perhaps the motor enable signals are incorrect? The RAMPS board has a separate enable signal for each motor (active low).

**Comment by RafatCAD** [comment]
Problem solved, but I have  inquirie , the probing in UNo on A5  pin but in mega in A15 (thermal sensor 2) . This thing is Wright or not

**Comment by svenhb** [comment]
I figured out same relation in the links posted above.

**Comment by mkaluza** [comment]
@RafatCAD Hi,
I've just got my hands on RAMPS 1.4 only to find out it's not supported by grbl. Can you post the changes you made somewhere?

**Comment by mkaluza** [comment]
ok, nevermind. It appears you just need to recompile grbl-mega. I was looking in the wrong repo.
