### ISSUE TITLE
"Notice: This site will be phased out and moved to the new one!" without link to a new site

### ISSUE THREAD

**Issue by matkoniecz** [grbl/grbl#1476]
It may be a good idea to link a new site in "new site" text.

**Comment by 109JB** [comment]
What???  The links to the new site are everywhere!!!!!

It is at the top of EVERY WIKI page, and the top of the code page. What more do you want?

**Comment by matkoniecz** [comment]
"new one" text linking to https://github.com/gnea/grbl

Currently readme has only "Grbl v1.1 has been released here!" that looks like outdated release info given line directly below.

**Comment by MeJasonT** [comment]
we -  will not......we will not be moved 
come on you know the song.  
Sonny we are taking over.

**Comment by MeJasonT** [comment]
spoil sport
