### ISSUE TITLE
How to use grbl to drive steerable wheel robot

### ISSUE THREAD

**Issue by Abd9** [grbl/grbl#1479]
I want to move steerable wheel robot with g codes using grlb in arduino,any ideas how to make changes in grl files

**Comment by chamnit** [comment]
You are better off using a PID controller that outputs a step signal through PWM. Grbl is for CNC machines not traditional robots.

**Comment by Abd9** [comment]
Actually i'm trying to make a cnc mobile robot like golaith,but i am using
steerable wheels mechanism.
I am having trouble with grbl kindly help me with this.
