### ISSUE TITLE
Limit switch

### ISSUE THREAD

**Issue by JacquesBrunet** [grbl/grbl#1496]
Hello,
I am building a CNC router from scratch with arduino Nano and shield V3. After correcting pins allocation in cpu_map and wrong µsteps jumpers grounding on the PCB, my X motor runs front and back (actually the only axis built). But I cannot get the limit switch working. The signal pin D9 goes from 1 (4.9 V)  to 0 (0.7 V) when actuated, but X motor continues its move. 
I am stuck with that issue.
Thank you for helping me

Jacques

[$1.txt](https://github.com/grbl/grbl/files/2780525/1.txt)
[cpu_map.h.txt](https://github.com/grbl/grbl/files/2780532/cpu_map.h.txt)

**Comment by JacquesBrunet** [comment]
Hello Rob2029,

 

Thank you for such a fast reply. Unfortunately CNCJs send no message in the console, whatever X, Y or Z switch input I activate. But once more, the pins status changes from 1 to 0.

 

Any other idea ?

 

Jacques

 

De : Rob2029 <notifications@github.com> 
Envoyé : lundi 21 janvier 2019 22:30
À : grbl/grbl <grbl@noreply.github.com>
Cc : JacquesBrunet <jacbrunet@free.fr>; Author <author@noreply.github.com>
Objet : Re: [grbl/grbl] Limit switch (#1496)

 

Check if the grbl sends a message to the console when you trigger the
switch, also try switching the pin and activate it manually to see if all 3
are working

**Comment by Rob2029** [comment]
Grbl should send a message if you have homing enabled, check the grbl wiki
for configuration guidance, and also you should check it in the serial
monitor of arduino IDE

**Comment by JacquesBrunet** [comment]
Hello Rob, 

 

So far Homing is disabled $22=0. But I believe it must not prevent limit switches from stopping motions when actuated. No more message in Arduino Serial Monitor.

I just enable Homing $22=1 without success. Because my machine actually has only 1 axis, I moved it to Y instead of X, I disabled variable spindle because the shield V3 connects Z limit to D11, I installed optical end switch and inverted $5=1 (I can measure D11 = 5 V when actuated). When I perform Homing $H, Y motor starts but limit switch has no effect, Homing ends with error 9…

 

It late here I go to bed !

 

Jacques

 

De : Rob2029 <notifications@github.com> 
Envoyé : lundi 21 janvier 2019 22:42
À : grbl/grbl <grbl@noreply.github.com>
Cc : JacquesBrunet <jacbrunet@free.fr>; Author <author@noreply.github.com>
Objet : Re: [grbl/grbl] Limit switch (#1496)

 

Grbl should send a message if you have homing enabled, check the grbl wiki
for configuration guidance, and also you should check it in the serial
monitor of arduino IDE

**Comment by Rob2029** [comment]
I see, it's no easy to tell you what's wrongs but you can try some basic
things like recheck connections and re uploading the grbl, trying another
version and read all the configuration wiki for a good reference on homing
and limit switches

**Comment by JacquesBrunet** [comment]
Hi,

I am still busy with homing… Z motor starts but limit switch has no effect. I did what you asked for without success. In order to validate my hardware (including Nano, shield V3, stepper driver, stepper power supply, limit switches and wiring) I wrote few lines of arduino code which simulate a homing … and it works fine : carriage goes toward end switch, stops when D12 Limit switch is actuated, reverses direction to release it etc. So my hardware works.

Then my problem comes from Grbl config, but I do not see where, even after several reads of the manual and reviewing cpu mapping and config files line after line. Now I am stuck with 2 issues you probably can fix:

1.	I cannot use “?” command to get real time report when homing runs. It works only when homing stops on alarm 9. I tried with Arduino serial monitor and Putty.
2.	I do not understand the report mask usage to determine  $10= value to see Pn status. I never see this pins status (which should help me a lot). I know, following manual, that it doesn’t show up is there is no change, but believe me at least D12 pin voltage change from 0 to 5V.

Thank for helping.

 

Jacques

 

De : Rob2029 <notifications@github.com> 
Envoyé : mardi 22 janvier 2019 00:46
À : grbl/grbl <grbl@noreply.github.com>
Cc : JacquesBrunet <jacbrunet@free.fr>; Author <author@noreply.github.com>
Objet : Re: [grbl/grbl] Limit switch (#1496)

 

I see, it's no easy to tell you what's wrongs but you can try some basic
things like recheck connections and re uploading the grbl, trying another
version and read all the configuration wiki for a good reference on homing
and limit switches

**Comment by JacquesBrunet** [comment]
Hello,

 

Probably yes, but so much literature to read… and understand!

 

I made a big step ahead by downloading the hex file instead of Arduino GrblUpload. Now I have it working, but the default config doesn’t much my shield hardware where PORTD is inverted

 

// Define step pulse output pins. NOTE: All step bit pins must be on the same port.

  #define STEP_DDR        DDRD

  #define STEP_PORT       PORTD

  #define X_STEP_BIT      5  // Shield V3 // Uno Digital Pin 2

  #define Y_STEP_BIT      6  // Shield V3// Uno Digital Pin 3

  #define Z_STEP_BIT      7  // Shield V3// Uno Digital Pin 4

  #define STEP_MASK       ((1<<X_STEP_BIT)|(1<<Y_STEP_BIT)|(1<<Z_STEP_BIT)) // All step bits

 

  // Define step direction output pins. NOTE: All direction pins must be on the same port.

  #define DIRECTION_DDR     DDRD

 #define DIRECTION_PORT    PORTD

  #define X_DIRECTION_BIT   2  // Shield V3// Uno Digital Pin 5

  #define Y_DIRECTION_BIT   3  // Shield V3// Uno Digital Pin 6

  #define Z_DIRECTION_BIT   4  // Shield V3// Uno Digital Pin 7

 

I try to compile my config with Atmel Studio (never done before. I will let you know.

 

Thanks

 

De : Sonny Jeon <notifications@github.com> 
Envoyé : mercredi 23 janvier 2019 14:25
À : grbl/grbl <grbl@noreply.github.com>
Cc : JacquesBrunet <jacbrunet@free.fr>; Author <author@noreply.github.com>
Objet : Re: [grbl/grbl] Limit switch (#1496)

 

1.	Grbl does reply to status reports during a homing cycle. This is an oversight on my part but even if you had that report, it wouldn’t tell you any useful position feedback.
2.	Pin status is automatic. You shouldn’t need to use $10 to configure it in v1.1, which is the version you are using. Make sure you are looking at the right wiki. I suspect you are reading the v0.9 version.

**Comment by JacquesBrunet** [comment]
Hello,

The compilation produces a too big hex file. any idea ?

Thank you
![memoryfull](https://user-images.githubusercontent.com/17966743/51619187-130cad80-1f30-11e9-8494-f76d78a5dddd.jpg)

**Comment by chamnit** [comment]
I don’t recommend compiling with Atmel studio. It’s only for experts. Please follow the compiling instructions in the wiki using the Arduino IDE.

**Comment by JacquesBrunet** [comment]
Hi Sonny,

 

I am not an expert, but I have already developed several projects in assembler for custom boards with Atmel Studio and downloaded with AvrDude. Because I had problems compiling with Arduino IDE, I tried Atmel Studio as described in the manual. Anyway, I finally got my Z home position “by mistake”. As I said, my shield is not standard, and I have to swap PORTD 2, 3, 4 with 5, 6, 7 in cpu_map in order to get the motors running. Till now I also changed limit_bits to match Uno configuration :  #define X_LIMIT_BIT      1  // Uno Digital Pin 9 (changed 1 to 9), #define Y_LIMIT_BIT      2  // Uno Digital Pin 10 (changed 2 to 10) etc.

My “mistake” this time was to forgot these changes and left  #define X_LIMIT_BIT      1, #define Y_LIMIT_BIT      2 etc. 

 

It remains something not so clear in defining limits bits. Or the comments lead to misunderstanding.

 

Anyway thank you very much for supporting me.

 

Jacques

 

// Define step pulse output pins. NOTE: All step bit pins must be on the same port.

  #define STEP_DDR        DDRD

  #define STEP_PORT       PORTD

  #define X_STEP_BIT      5  // Uno Digital Pin 2

  #define Y_STEP_BIT      6  // Uno Digital Pin 3

  #define Z_STEP_BIT      7  // Uno Digital Pin 4

  #define STEP_MASK       ((1<<X_STEP_BIT)|(1<<Y_STEP_BIT)|(1<<Z_STEP_BIT)) // All step bits

 

  // Define step direction output pins. NOTE: All direction pins must be on the same port.

  #define DIRECTION_DDR     DDRD

  #define DIRECTION_PORT    PORTD

  #define X_DIRECTION_BIT   2  // Uno Digital Pin 5

  #define Y_DIRECTION_BIT   3  // Uno Digital Pin 6

  #define Z_DIRECTION_BIT   4  // Uno Digital Pin 7

  #define DIRECTION_MASK    ((1<<X_DIRECTION_BIT)|(1<<Y_DIRECTION_BIT)|(1<<Z_DIRECTION_BIT)) // All direction bits

 

  // Define stepper driver enable/disable output pin.

  #define STEPPERS_DISABLE_DDR    DDRB

  #define STEPPERS_DISABLE_PORT   PORTB

  #define STEPPERS_DISABLE_BIT    0  // Uno Digital Pin 8

  #define STEPPERS_DISABLE_MASK   (1<<STEPPERS_DISABLE_BIT)

 

  // Define homing/hard limit switch input pins and limit interrupt vectors.

  // NOTE: All limit bit pins must be on the same port, but not on a port with other input pins (CONTROL).

  #define LIMIT_DDR        DDRB

  #define LIMIT_PIN        PINB

  #define LIMIT_PORT       PORTB

  #define X_LIMIT_BIT      1  // Uno Digital Pin 9

  #define Y_LIMIT_BIT      2  // Uno Digital Pin 10

  #ifdef VARIABLE_SPINDLE // Z Limit pin and spindle enabled swapped to access hardware PWM on Pin 11.

    #define Z_LIMIT_BIT     4 // Uno Digital Pin 12

  #else

    #define Z_LIMIT_BIT    3  // Uno Digital Pin 11

 

De : Sonny Jeon <notifications@github.com> 
Envoyé : mercredi 23 janvier 2019 17:35
À : grbl/grbl <grbl@noreply.github.com>
Cc : JacquesBrunet <jacbrunet@free.fr>; State change <state_change@noreply.github.com>
Objet : Re: [grbl/grbl] Limit switch (#1496)

 

I don’t recommend compiling with Atmel studio. It’s only for experts. Please follow the compiling instructions in the wiki using the Arduino IDE.

**Comment by chamnit** [comment]
The reason I said Atmel Studio is for experts is because the compiler settings and other settings may be different from the Arduino IDE. It’s too difficult to diagnose problems when there are so many options.  Only the Arduino IDE compiling method is supported here. You are in your own with Atmel Studio.
