### ISSUE TITLE
Arduino Mega GRBL - Stepper motor run on it's own

### ISSUE THREAD

**Issue by Fredzki** [grbl/grbl#1499]
Hey
I have a strange problem. I'm in the middle of building my own CNC, and I have connected the Arduino mega 2560 to the stepper drives as shown here: https://imgur.com/a/rI6zJyd

If I just connect one stepper motor to this setup I can control it as I should be able to. 
There is a bit of chatter from it, and it doesn't move smoothly, but I think that comes down to finetuning of the stepper perimeters. 
When I connect a second stepper motor the first one just start spinning fast. 
I have tried with different stepper motors and every combination of the stepper drivers.
What could be causing this? 
I'm at a lost right now...
Thank you in advance!

**Comment by 109JB** [comment]
This is the repo for the Arduino uno version of grbl. Are you using a grbl version that is made for use with the mega?

https://github.com/gnea/grbl-Mega/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
