### ISSUE TITLE
Zsafe, G0Z[safe]

### ISSUE THREAD

**Issue by wurth70** [grbl/grbl#1519]
Running grbl 1.x on Arduino UNO controlled by bCNC. I cannot find anything on how to directly set the variable [safe] for setting the safe Z parameter.  Help!

![bcnc](https://user-images.githubusercontent.com/41460837/56076182-ab257080-5d82-11e9-9843-6b2036d3cbc9.jpg)

**Comment by chamnit** [comment]
The safe variable is inside bCNC. Not inside Grbl.

**Comment by wurth70** [comment]
Thanks Sonny
    On Saturday, April 13, 2019, 06:43:15 AM PDT, Sonny Jeon <notifications@github.com> wrote:  
 
 
The safe variable is inside bCNC. Not inside Grbl.
