### ISSUE TITLE
Steppers Motors Not Moving

### ISSUE THREAD

**Issue by Bugz2find** [grbl/grbl#1522]
I am completely new to this. Just want to throw that out there. My spindle is moving but when I load a program into the grbl controller 3.6.1 the steppers don't move. Previous to the beginning of the program they are humming and provide a resistance to me turning them manually. 

This is all i received from the manufacturer:

![59342832_889486854737777_4119015821756334080_n](https://user-images.githubusercontent.com/27552190/57172810-0c28ed00-6df3-11e9-85e4-33752e4113ef.jpg) 

![59087045_2321590371497065_7487688586179903488_n](https://user-images.githubusercontent.com/27552190/57172813-2236ad80-6df3-11e9-9fe8-446782a788de.jpg)

https://cdn.fbsbx.com/v/t59.2708-21/57256984_550103998728975_4079442469832359936_n.doc/interface-description1.doc?_nc_cat=100&_nc_ht=cdn.fbsbx.com&oh=84e2971e3132987bc6fab1f6eb50f802&oe=5CCEF3E1&dl=1&fbclid=IwAR2I1ZGCRQvJkcVsHStbbwGAjg491LzantDoQIC7AtDVhb7Kg7Jz4RHmdhI

#	ASIN	Product Name
1	B079PNSVB1	Benbox DIY Mini 1310 Metal Engraving Machine Cutting Engrave PVC,PCB,Aluminum,Copper CNC Router
Message:
Hello friend
You can download grbl software from below link,and attached manual,thanks!

https://grbl-controller.software.informer.com/download/

install video can see from below link,thanks!

https://www.amazon.com/gp/product/B079PNSVB1

Kind Regards
Wendy

These are photos of the controller:

![58933415_828676757499381_9203363635353616384_n](https://user-images.githubusercontent.com/27552190/57172840-8ce7e900-6df3-11e9-8b12-831857c4e196.jpg)

![59120993_314542669216712_2541489379205971968_n](https://user-images.githubusercontent.com/27552190/57172841-8fe2d980-6df3-11e9-8123-9119ec643d2a.jpg)

**Comment by Bugz2find** [comment]
Also many of the other users of this engraver said they used grbl.. maybe I'm using the wrong program to control it with, but this is the only one I could connect to the controller with at all.

**Comment by woshituzaizi** [comment]
I do not know if you can receive this mail
but first,if the program is not running,the spindle should should not moving too.
sencode,as usual，Red wire is positive，Black wire is negative，the picture`s Lower right corner is not good,
you should confirm to your manufacturer,
if it connected wrong,it might burnout the driver board。





At 2019-05-04 10:34:17, "Bugz2find" <notifications@github.com> wrote:


I am completely new to this. Just want to throw that out there. My spindle is moving but when I load a program into the grbl controller 3.6.1 the steppers don't move. Previous to the beginning of the program they are humming and provide a resistance to me turning them manually.

This is all i received from the manufacturer:

https://cdn.fbsbx.com/v/t59.2708-21/57256984_550103998728975_4079442469832359936_n.doc/interface-description1.doc?_nc_cat=100&_nc_ht=cdn.fbsbx.com&oh=84e2971e3132987bc6fab1f6eb50f802&oe=5CCEF3E1&dl=1&fbclid=IwAR2I1ZGCRQvJkcVsHStbbwGAjg491LzantDoQIC7AtDVhb7Kg7Jz4RHmdhI

ASIN Product Name

1 B079PNSVB1 Benbox DIY Mini 1310 Metal Engraving Machine Cutting Engrave PVC,PCB,Aluminum,Copper CNC Router
Message:
Hello friend
You can download grbl software from below link,and attached manual,thanks!

https://grbl-controller.software.informer.com/download/

install video can see from below link,thanks!

https://www.amazon.com/gp/product/B079PNSVB1

Kind Regards
Wendy

These are photos of the controller:

**Comment by Bugz2find** [comment]
Photos of controller:
![3](https://user-images.githubusercontent.com/27552190/57182663-a9296b80-6e6f-11e9-80a6-58060270b02b.jpg)
![4](https://user-images.githubusercontent.com/27552190/57182665-ac245c00-6e6f-11e9-8d26-208117ccdd3f.jpg)
![5](https://user-images.githubusercontent.com/27552190/57182667-adee1f80-6e6f-11e9-8ac7-9641e9626510.jpg)
![6](https://user-images.githubusercontent.com/27552190/57182669-afb7e300-6e6f-11e9-8a6b-598dab5b9b8a.jpg)
![11](https://user-images.githubusercontent.com/27552190/57184102-5312f300-6e84-11e9-8787-43d12df2e54c.jpg)
![12](https://user-images.githubusercontent.com/27552190/57184117-848bbe80-6e84-11e9-982a-819c884c414e.jpg)
![13](https://user-images.githubusercontent.com/27552190/57184119-85bceb80-6e84-11e9-801e-904e6f1cfdfb.jpg)
![14](https://user-images.githubusercontent.com/27552190/57184121-88b7dc00-6e84-11e9-87d9-4635c7cf9543.jpg)


That's the only place for me to connect it. The only other place with the same connector is the DCout but that keeps the spindle continuously moving. 

Thanks for the response!!

**Comment by Bugz2find** [comment]
I am not new to electronics I'm in school for electronics currently. So I will understand most of the talk. I just don't know about this particular field. I have also played with a raspberry pi and arduino uno.

**Comment by Bugz2find** [comment]
@woshituzaizi

**Comment by woshituzaizi** [comment]
Hi:
   i did not read all the source code,but i worry about S112 z = 0.000 (z max rate,mm/min)
please change it to 500.000 and try again
  check again,your wiring is good





At 2019-05-05 03:53:57, "Bugz2find" <notifications@github.com> wrote:


Photos of controller:









That's the only place for me to connect it. The only other place with the same connector is the DCout but that keeps the spindle continuously moving.

Thanks for the response!!

**Comment by Bugz2find** [comment]
I changed it to 150 earlier I’ll try the 500 also I have the Y axis moving a little bit at the beginning of a file. I was having trouble with undefined feed rate but I think when I changed the $112 it stopped. I think the driver current may just be too high.

**Comment by Bugz2find** [comment]
Works great thanks I'm not sure if it was that or the potentiometer but one of those two worked great!
