### ISSUE TITLE
No linear movement when gcode changes from M3 to M5/G0 to G1 (LaserMode, Dithering) 

### ISSUE THREAD

**Issue by Naisk2k** [grbl/grbl#1523]
Hi,
is there an delay in LaserMode when the Gcode switches  M3 <-> M5 and/or G0 <-> G1? (Didn't find something like that in the last issues...)
When i dithering (without PWM) an image the axis moves in short discrete steps, added speed moves faster but still feels discrepancy. Is it possible to smooth the motion (even linear?) so that only the laser flickers?

The problem makes the process really slow (5h instead of 1h). It works fine and steady when i change the Gcode like this.
M3 S0 for M5
M3 S255 for M3 (S255 defined before) and
G1 for all G0

Best regards.

**Comment by chamnit** [comment]
Yes there is a way. See the laser mode wiki pages for how this works.
