### ISSUE TITLE
Spindle doesn't turn off when serial connection is closed or program is closed

### ISSUE THREAD

**Issue by tiptonspiderj** [grbl/grbl#1524]
I found an issue with Grbl when I was testing my own spindle speed controller routine.  When I connect to Grbl, send the unlock command, turn on the spindle using the command "M3", the spindle turns on as expected.  When I close the java program completely or unexpectedly, the spindle continues to spin.  Is there a way to prevent this behavior inside Grbl's program when it loses connection or is it something I have to control in my software when the Java program shuts down?  I have a short term fix for sending "Ctrl + X" when the software shuts down.  I would think when the serial connection is closed that all commands from Grbl would cease.

**Comment by langwadt** [comment]
grbl has no way to tell if the connection is open or closed, it just waits for commands
