### ISSUE TITLE
Stepper motors torque but not moving (Arduino UNO, GBRL 1.1, Protoneer v3.51, DRV8825)

### ISSUE THREAD

**Issue by alandroid** [grbl/grbl#1532]
Please someone help,
I have spent many hours troubleshooting my motors:

I'm trying to use 2 different kinds of motors, both are nema17, i am unable to get either to work, i've been trying to change the driver pot value and changing the wiring order of the wires and nothing is helping.

The motors are holding some torque at best, but not moving.

Using Arduino UNO, GBRL 1.1, Protoneer v3.51, DRV8825

Motor set 1:
PrimoPal Stepping Motor
Model: PHB42S48-403
1.8Deg 2.3A 1.2ohm
(is 2.3A too high?)
http://vi.vipr.ebaydesc.com/ws/eBayISAPI.dll?ViewItemDescV4&item=112160962313&t=1475036475000&tid=10&category=9723&seller=aplus_cnc_technology&excSoj=1&excTrk=1&lsite=0&ittenable=false&domain=ebay.com&descgauge=1&cspheader=1&oneClk=1&secureDesc=0
(i dont think i got them from ebay but this seems to be a datasheet for the motors)

Motor set 2:
Casun
Stepping Motor
Type: 42SHD0217-24B
2015/09/02
GEETECH.COM
(these motors i have to check wiring again, but i think i'm having the same issue with them)
https://www.geeetech.com/nema17-stepper-motor-with-skidproof-shafts4lead18-degree-p-696.html

Something must be broken or incompatible, maybe its way too late - if i buy new electronics without understanding the issue i will potentially face the same issue again, and i'm not learning.

`Grbl 1.1g ['$' for help]
>>> $$
$0=10
$1=25
$2=0
$3=0
$4=0
$5=0
$6=0
$10=1
$11=0.010
$12=0.002
$13=0
$20=0
$21=0
$22=0
$23=0
$24=25.000
$25=500.000
$26=250
$27=1.000
$30=1000
$31=0
$32=0
$100=250.000
$101=2147483.648
$102=2147483.648
$110=-0.000
$111=-0.000
$112=-0.000
$120=10.000
$121=10.000
$122=10.000
$130=200.000
$131=200.000
$132=200.000
ok`

Please tell me what information i can provide to get this issue resolved.

**Comment by 109JB** [comment]
$110 ,-$112 all equal 0. These are the maximum speed settings in mm/ minute. It can't move if 0 is it's fastest speed

**Comment by alandroid** [comment]
I tried to change to:
`$110=300.000
$111=100.000
$112=100.000`
neither 100 or 300 make a difference but thank you very much for pointing that out, im sure it helps overal

**Comment by chamnit** [comment]
Try resetting your EEPROM by issuing Grbl the ‘$RST=*’ command.

**Comment by alandroid** [comment]
That had no effect, my motors still hold torque, make buzzing noise but dont move :(

**Comment by chamnit** [comment]
Buzzing when you command it? That means you probably don’t have the current set high enough on your step drivers.

**Comment by alandroid** [comment]
> Buzzing when you command it? That means you probably don’t have the current set high enough on your step drivers.

Only X axis works though, i swapped driver and motor.

**Comment by terjeio** [comment]
Over to million steps per mm for Y and Z ($102 & $103) is perhaps a bit too much?

**Comment by alandroid** [comment]
> Over to million steps per mm for Y and Z ($102 & $103) is perhaps a bit too much?

Wow, thanks for noticing that. Let me try again.
