### ISSUE TITLE
Z axis not working while X and Y makes loud noises

### ISSUE THREAD

**Issue by NghiDao2** [grbl/grbl#1538]
So im making a 4xidraw machine. The x and y axis works normally, however they make really loud noises. However, the z axis doesn't work and just shakes while the X and Y axis motors made some noises. I tried unplugging either the x or y axis stepper motor, and the z axis starts to move a bit, if a unplug both the X and Y stepper motor, the z axis starts to move normally.
I used a 12V power supply, so i dont think thats the problem.
Can someone help me to get the Z axis moving with the X and Y axis plugged in ?

Thanks

**Comment by jahnj0584** [comment]
You don't have enough current available. 12V isn't a lot either. I consider
24v the bare minimum for nema23's but prefer 48-60.

**Comment by NghiDao2** [comment]
ok thanks
