### ISSUE TITLE
Problem with m3 on grbl 1.1f 

### ISSUE THREAD

**Issue by delphy38** [grbl/grbl#1546]
I just received a CNC 3018 with a motherboard controlled by an arduino nano and grbl 0.9j, M3 works pretty well: the spindle motor turns/stops, for 30 seconds then starts finally.
I flashed Grbl 1.1f and now M3 doesn’t work at all.
With Grbl 0.9j I use grblControl_0.8.1.
With Grbl 1.1f I use Grblpanel-Release-1.0.9.18A.
I am new in the field of Grbl, is there a setting or configuration to run M3 on Grbl 1.1f ?
Thank you.

**Comment by jahnj0584** [comment]
I believe the pins changed

**Comment by chamnit** [comment]
Comment out `#define VARIABLE_SPINDLE` in config.h. Make sure you are editing the files in the library folder.

**Comment by delphy38** [comment]
Merci.
Je l'avais déjà fait, avant d'installer la bibliothèque, et de téléverser grbl sur l'arduino.
Donc il y a un autre problème, apparemment.

**Comment by delphy38** [comment]
Why was this number closed?
I still hope to have some answers.

**Comment by chamnit** [comment]
You closed it.

**Comment by delphy38** [comment]
Non !

**Comment by chamnit** [comment]
Yes.

**Comment by chamnit** [comment]
@delphy38 : If you would like help, you need to provide more detail than saying it doesn't work like it used to. One way to check if you disabled VARIABLE_SPINDLE correctly is providing the $I build info output. It should not contain the letter V.

**Comment by delphy38** [comment]
****Part of my config.h*****
// Sets which axis the tool length offset is applied. Assumes the spindle is always parallel with
// the selected axis with the tool oriented toward the negative direction. In other words, a positive
// tool length offset value is subtracted from the current location.
#define TOOL_LENGTH_OFFSET_AXIS Z_AXIS // Default z-axis. Valid values are X_AXIS, Y_AXIS, or Z_AXIS.
// Enables variable spindle output voltage for different RPM values. On the Arduino Uno, the spindle
// enable pin will output 5V for maximum RPM with 256 intermediate levels and 0V when disabled.
// NOTE: IMPORTANT for Arduino Unos! When enabled, the Z-limit pin D11 and spindle enable pin D12 switch!
// The hardware PWM output on pin D11 is required for variable spindle output voltages.
// #define VARIABLE_SPINDLE // Default enabled. Comment to disable. ************************

// Used by variable spindle output only. This forces the PWM output to a minimum duty cycle when enabled.
// The PWM pin will still read 0V when the spindle is disabled. Most users will not need this option, but
// it may be useful in certain scenarios. This minimum PWM settings coincides with the spindle rpm minimum

****** I will try tomorrow the order $ I build info

**Comment by delphy38** [comment]
Good morning,
Here are the results of $I build info:
![2019-08-24 11 15 15](https://user-images.githubusercontent.com/24485586/63635915-71397480-c668-11e9-94b4-538db10d278c.jpg)

[VER : 1.1f . 20170801 : ]
[OPT : , 15 , 128]

**Comment by ygjfggfgfj** [comment]
hello there
i dont have any programming knowledge
could any one help me how to set stepper motor as spindle in GRBL library?
im using 2 stepper motors for x,y axis , solenoid for z axis , stepper motor as spindle
im really in rush for solving this problem
please

**Comment by delphy38** [comment]
Bonjour,
Je n'ai également aucune connaissance en programmation, et je n'ai jamais reçu de réponse à ce problème, qui me permette  de le résoudre.
