### ISSUE TITLE
Having issue with homing

### ISSUE THREAD

**Issue by madhatter46** [grbl/grbl#1551]
Hey guys ! 

I started to make my cnc for plasma cutting, I use the X and Y axes only (I do not use Z axis).

For now I managed to make the basic settings (X and Y-axis travel resolution, X and Y-axis maximum rate, X and Y-axis acceleration) and I'm now trying to adjust the homing cycle.

I only have 3 limit switches and I wonder if I can combine the $21 "hard limits" parameters to define the end positions on X- and Y- with the $ 130 and $ 131 "maximum travel" parameters to define the end position on X + and Y +.
Is it possible? What are the settings to do?

Regarding the homing cycle, I changed the config.h file by replacing

#define HOMING_CYCLE_0 (1 << Z_AXIS) // REQUIRED: First move Z to clear workspace.
#define HOMING_CYCLE_1 ((1 << X_AXIS) | (1 << Y_AXIS)) // OPTIONAL: Then move X, Y at the same time.

by

#define HOMING_CYCLE_0 (1 << X_AXIS)
#define HOMING_CYCLE_1 (1 << Y_AXIS)

But when I run the home machine command (I use UGS platform) I get an alarm (apparently it looks for the z axis, doesn't find it and then run alarm ...). Some help will be appreciate !!

I've got :
- arduino UNO
- grbl 1.1h
- protoneer (Chinese) CNC shield v3.0
- pololu DRV8825 Stepper Motor Driver Carrier
- nema 17 stepper motor
- and this kind of end stop [https://www.amazon.com/Mechanical-Endstop-Limit-Switch-Printer/dp/B01LYSF3Q4](url)

Hoping you can help me to get thru this :)

Nico.

**Comment by 928oleg** [comment]
Do it in this way
//#define HOMING_CYCLE_0 (1 << Z_AXIS) // REQUIRED: сначала переместите Z, чтобы очистить рабочее пространство.
