### ISSUE TITLE
abort breaks tools

### ISSUE THREAD

**Issue by Arbuthnot999** [grbl/grbl#1560]
Got a 3018 CNC, using arduino nano, running grbl 0.9j. Problem is, when I hit abort the machine drives the cutting tool down and then snaps it off. Is there a fix for this?? This reminds me of the reversed jogging (needed $3=5 or similar).
Also bought some limit switches and fitted them. Can someone give me a clue about connection to the arduino??

**Comment by MeJasonT** [comment]
Arbuthnot999
I did a quick search and found the following.

![image](https://user-images.githubusercontent.com/21656956/66553248-aaf40b00-eb42-11e9-8efd-14e7fb3dcc95.png)

wire something like the image below, you don't have to have a switch at both ends as you can use in tandem with soft limits which will prevent your machine going further than the limits of your bed anyways.  If you can install max limit switches - why wouldn't you.
the image below is for the uno but armed with the pin numbers above you should be able to see how to wire the switches to the nano.

![image](https://user-images.githubusercontent.com/21656956/66553507-2786e980-eb43-11e9-9965-1cf7a0652f67.png)

**Comment by Arbuthnot999** [comment]
Thanks for all your good efforts, Jason.
I do have an Arduino but it is being used for something else.
Proper name of this board is “Developower v2.0 (pic attached) I hope this shows the info you need.
As you might be able to tell, I’m brand new to forums and discussions. I blame this for my lack of etiquette .
The problem of breaking tools hasn’t been addressed yet. Will this be a code problem or something else??
Once again,
Thanks for your time,
Regards,
Pete Smith (Arbuthnot999)

Sent from Mail for Windows 10
