### ISSUE TITLE
How speed up grbl verbose output  transmit frequency ?

### ISSUE THREAD

**Issue by manojprasanga** [grbl/grbl#1569]
This is a simple issue.How change grbl verbose output recieve frequency.This mean ,Universal gcode sender has 1second  recive frequency and bCNC has 0.1 second frequency

**Comment by MeJasonT** [comment]
Its sounds like your issue is with UGS and not grbl if bCNC give you faster responses
is there a polling setting in UGS that can be adjusted

**Comment by MeJasonT** [comment]
![UGS](https://user-images.githubusercontent.com/21656956/67842357-e8203d00-faf1-11e9-8386-d5bb16f8934d.jpg)

**Comment by manojprasanga** [comment]
I grateful for your response sir
