### ISSUE TITLE
I want to know what are these pins used for

### ISSUE THREAD

**Issue by Rob2029** [grbl/grbl#1586]
![cnc shield v3 protoneer](https://user-images.githubusercontent.com/37225325/71386196-cacb9480-25b1-11ea-9cd8-e710c7421b90.PNG)

Hello everyone! i was checking my CNC shield for UNO, i have the Protoneer v3, and i want to know if these pins circled in yellow have a major use or are there just for configuring the drivers, if so how can i use them?
In the assembly guide or any documentation i found this doesn't get mentioned so i ask you guys
Any info will be helpful, thanks!

**Comment by langwadt** [comment]
they are just there for easy access to the signals or if you want to connect external drivers
