### ISSUE TITLE
Steppers humming and holding torque, but no movement

### ISSUE THREAD

**Issue by herrluki** [grbl/grbl#1587]
Hello everybody, 
I am having trouble with my homemade laser cutter...
I am using an arduino nano with a v4 cnc shield. When I move the motors (with LaserGRBL) both of them are humming and holding torque, but not moving. I tried various wiring setups but none of them worked. I switched out the arduino, because I couldn't overwrite it anymore, but that also didn't help.

Please help me,
thanks, Luki

![IMG_0621 1](https://user-images.githubusercontent.com/59396188/71627296-f1ad4a80-2bf1-11ea-88cd-ee9e1515f3e5.JPG)

![IMG_0622](https://user-images.githubusercontent.com/59396188/71627336-2b7e5100-2bf2-11ea-93ac-8b0cc2992b52.JPG)
![IMG_0623](https://user-images.githubusercontent.com/59396188/71627338-30db9b80-2bf2-11ea-8648-60fe087da4e3.JPG)
![IMG_0625](https://user-images.githubusercontent.com/59396188/71627344-389b4000-2bf2-11ea-8b96-f3ef58624dcc.JPG)
![IMG_0624](https://user-images.githubusercontent.com/59396188/71627347-3df88a80-2bf2-11ea-81f7-362d526f325e.JPG)

**Comment by jahnj0584** [comment]
I guarantee you have the motor coil pairs reversed, since you didn't say
you checked that.

**Comment by herrluki** [comment]
@jahnj0584 
thanks a lot for your quick answer!
I tried that allready, but I think I didn't try out all variations...

**Comment by herrluki** [comment]
I found the mistake, thanks!
the pins were the wrong ones for my arduino nano (in the grbl file)

https://www.davidpilling.com/wiki/index.php/CNCShield
