### ISSUE TITLE
does GRBl upport G68 and G69?

### ISSUE THREAD

**Issue by Slixxor** [grbl/grbl#1617]
Looking at adding some easy auto straightening features to GRBL using a probe. I wondering if it supports G68 and G69 commands?

**Comment by Rob2029** [comment]
I don't know, but you can try to send the command, with a finger on the E-Stop just in case, if the response is "ok" then it supports the command

**Comment by terjeio** [comment]
G68 and G69 is not supported and neither is [G10 L2 with R word](http://linuxcnc.org/docs/html/gcode/g-code.html#gcode:g10-l2), however some senders supports rotation.

**Comment by Slixxor** [comment]
> 
> 
> G68 and G69 is not supported and neither is [G10 L2 with R word](http://linuxcnc.org/docs/html/gcode/g-code.html#gcode:g10-l2), however some senders supports rotation.

Thanks for that. Do you know which senders support it?

**Comment by terjeio** [comment]
At least [GRBL-Plotter](https://github.com/svenhb/GRBL-Plotter) claims to do so. Never tested it though.
