### ISSUE TITLE
How do I INVERT the Y and Z Axis of my GRBL CNC?

### ISSUE THREAD

**Issue by ValentineKilla** [grbl/grbl#1625]
Hey guys, :) 

I'd like to know how to INVERT the direction on just my Y-Axis and my Z-Axis. 

My X-Axis is correct. Left goes LEFT and Right goes RIGHT. 
Unfortunately my Y-Axis (-) goes AWAY from me and (+) comes towards me. 
My Z-Axis (-) goes UP and (+) goes DOWN. 

Everything else I've managed to correct and re-calibrate through other posts on this site. So BIG THANKS to you legends. 

Below are my current settings. 

>>> $$
$0=132.978 (x, step/mm)
$1=132.978 (y, step/mm)
$2=132.978 (z, step/mm)
$3=10 (step pulse, usec)
$4=250.000 (default feed, mm/min)
$5=500.000 (default seek, mm/min)
$6=192 (step port invert mask, int:11000000)
$7=25 (step idle delay, msec)
$8=10.000 (acceleration, mm/sec^2)
$9=0.050 (junction deviation, mm)
$10=0.100 (arc, mm/segment)
$11=25 (n-arc correction, int)
$12=3 (n-decimals, int)
$13=0 (report inches, bool)
$14=1 (auto start, bool)
$15=0 (invert step enable, bool)
$16=0 (hard limits, bool)
$17=0 (homing cycle, bool)
$18=0 (homing dir invert mask, int:00000000)
$19=25.000 (homing feed, mm/min)
$20=250.000 (homing seek, mm/min)
$21=100 (homing debounce, msec)
$22=1.000 (homing pull-off, mm)
ok

Your feedback is greatly appreciated! :D Thanks again!

**Comment by olvll** [comment]
I'm not sure how you generated that parameter list but it seems wrong (or non-standard to say the least). Look at the list at [Grbl v1.1 Configuration](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration) and note the differences.

In a normal Grbl setup you configure the directions of your axis with the [$3](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#3--direction-port-invert-mask) parameter.

For example $3=6 would invert both Y and Z, simple as that.

If you are using a version of Grbl that was hacked/adapted to work with a specific board or machine I guess it is possible that whoever did that, left the "direction port invert" parameter out and you will have to take it up with them.

Either way you could always just switch the wires from your stepper motors. That will make them turn the other way too.

**Comment by ValentineKilla** [comment]
Hey Guys, 

Thanks for the feedback. 
I managed to find another post with a similar issue which matched my settings. 

Apparently each axis has a value assigned to them. 32 , 64 & 128. 
Depending on which one you wish to invert. You simple change $6= accordingly. 

For example.  
$6=32 
$6=64 
$6=128 

If you wish to invert more than one axis, simply add the numbers together. 
32 + 64 = 96 ($6=96)

Now as you can see my current value is 192 (no idea why!?) 
That means 64 and 128 have been inverted. 

Sooo I took a wild guess and decided to see what happens if I set the value to zero. 
$6=0 

IT WORKED!!
This removed the inversion on the two troubled axis Y & Z. 

Thanks for reading and I hope this helps anyone else in future. :)

Take care! 

Kind Regards,
VK
