### ISSUE TITLE
Looking for a way to call macro directly without 2nd dialog pop-up asking to run the macro

### ISSUE THREAD

**Issue by dlarue** [grbl/grbl#1630]
I'm looking for a way to launch a macro directly either in one click or one keyboard sequence? The current "Run Macro" button only launches another dialog halfway across the screen showing the macro contents and with a RUN button.  

I tried to use the Custom Command feature but it doesn't know about CNCjs variables like xmin,xmax, ymin, ymax.

**Comment by abdset** [comment]
What are you using as grbl sender software ?

**Comment by dlarue** [comment]
Oh my goodness, I posted to the wrong git repository!  I must have still had this GRBL repo open and my CNCjs repo.  Sorry, this is closed.
