### ISSUE TITLE
Strange receive of "ok" from GRBL v1.1

### ISSUE THREAD

**Issue by Mikron007** [grbl/grbl#1665]
Hi
I made myself a laser engraver and it stops working at random position, but comunication stays open.
From LightBurn software console I noticed strange receive from controller. I'm using Arduino Uno GRBL shield.
I changed the USB cable for shorter one (about 0.5 m shielded cable) and that didn't solve my problem.
I added picture of my problem.
![grbl problem](https://user-images.githubusercontent.com/71175141/92994158-1e8f5c80-f4f8-11ea-90c7-1fb10e41e024.jpg)

**Comment by Mikron007** [comment]
Now i'm trying Universal Gcode Sender - UGS and I getting similar results. Laser still stops in the middle of the job.
![CVBCB](https://user-images.githubusercontent.com/71175141/93103786-54c20d00-f6ad-11ea-9f1d-a6568903a724.png)
![FDGD](https://user-images.githubusercontent.com/71175141/93103787-555aa380-f6ad-11ea-80ce-cfbd7c58dc06.png)

**Comment by langwadt** [comment]
settings?

**Comment by Mikron007** [comment]
> settings?

My grbl settings are:
$0=10
$1=25
$2=0
$3=0
$4=0
$5=0
$6=0
$10=1
$11=0.010
$12=0.002
$13=0
$20=0
$21=0
$22=0
$23=0
$24=25.000
$25=500.000
$26=250
$27=1.000
$30=255
$31=0
$32=1
$100=100.000
$101=100.000
$102=250.000
$110=6000.000
$111=6000.000
$112=6000.000
$120=10.000
$121=10.000
$122=10.000
$130=200.000
$131=200.000
$132=200.000

**Comment by terjeio** [comment]
Some Arduino clones has a lousy USB <> UART chip? There are lost characters so worth investigating?

**Comment by Mikron007** [comment]
> Some Arduino clones has a lousy USB <> UART chip? There are lost characters so worth investigating?

Tnx. I have one arduino from Keyestudio. I will try that one.

**Comment by Mikron007** [comment]
It seems that changing the arduino uno board solved the problem.
Tnx.
