### ISSUE TITLE
porting Grbl code to Xmega

### ISSUE THREAD

**Issue by jtronics** [grbl/grbl#171]
Hello,
some years  ago I ported a Version of Grbl to an Atmega128. Since last year, I'm working with the Xmega controller family and I decided to port the actual version of Grbl to one of these controllers.
So I designed a new fully featured USB CNC motion Controller by using an Xmega128.
- Fully integrated CNC controller with 4 stepper motor drivers
- Control via standard Gcode via the USB port, by using Grbl
- integrated SD card
- 3-axis CNC (XYZ)
- Integrated Stepper Motor Driver, up to 2.5A
- Micro-stepping up to 1/8
- Optional two extension ports for an external display or an operating unit.

<a href="http://www.flickr.com/photos/jtronics/8258137896/" title="jtronics_cncv2_5 von www.jtronics.de bei Flickr"><img src="http://farm9.staticflickr.com/8077/8258137896_5a907b3ba3_m.jpg" width="240" height="180" alt="jtronics_cncv2_5"></a><a href="http://www.flickr.com/photos/jtronics/8294027540/" title="jtronics_cncv2_10 von www.jtronics.de bei Flickr"><img src="http://farm9.staticflickr.com/8495/8294027540_52e054c14d_m.jpg" width="240" height="160" alt="jtronics_cncv2_10"></a>
<a href="http://www.flickr.com/photos/jtronics/8358820087/" title="jtronics_cnccontrollerv2_12 von www.jtronics.de bei Flickr"><img src="http://farm9.staticflickr.com/8185/8358820087_01bd1df96a_m.jpg" width="240" height="160" alt="jtronics_cnccontrollerv2_12"></a><a href="http://www.flickr.com/photos/jtronics/8394057335/" title="jtronics_software_jcnc von www.jtronics.de bei Flickr"><img src="http://farm9.staticflickr.com/8473/8394057335_1c822529da_m.jpg" width="240" height="145" alt="jtronics_software_jcnc"></a>

Last week, I finished the main part of the work. The first run of my self made milling machine you could see 
on youtube --> http://www.youtube.com/user/jtronicsTV
or here --> http://www.jtronics.de/forum/viewtopic.php?f=18&t=6#p300

**Comment by oxygenic** [comment]
@jtronics will your webpage ever be available again? Or are the sources of your modifications available on some public place? none of your links is working any more...
