### ISSUE TITLE
diy cnc machine problem with cnc shield v3 + arduino uno + step motor + micro step driver

### ISSUE THREAD

**Issue by 1mies80** [grbl/grbl#1711]
could anyone help me with my problem. i have just build my cncmachine and now testing if my motors will work. im using universal gcode sender. i have import code in to the arduino but when i push x+ button x-axel (every axel has same problem) start vibration and it not move at all. What is wrong? i have try multiple things but nothing will help. here is you tube link what happen when i push that button. it kind move clockwise and counter clockwise but only one step and it do that rapidly sound come from that movement.

Ty for your answers

https://www.youtube.com/watch?v=erradsnasLc

**Comment by jahnj0584** [comment]
Allow comments on the video. Makes life easier.

Try JUST the motor first.

**Comment by 1mies80** [comment]
now it is open :)

**Comment by 1mies80** [comment]
"Try JUST the motor first." what you mean about that?
