### ISSUE TITLE
grbl/grbl or gnea/grbl ?

### ISSUE THREAD

**Issue by mattchesters** [grbl/grbl#1716]
Although links across this project and readme.md now suggest the project has moved to gnea/grbl, grbl/grbl still seems very active.

Which should be considered the official project? What's the history of this spilt?

**Comment by chamnit** [comment]
grbl/grbl is the original repo up to v0.9. No code updates have occurred there a quite some time. It's only active as the issues threads are being used like a forum.

gnea/grbl is v1.1+. This contained real time overrides that I felt was significant enough of a contribution to break away from the original project.

gnea is a group I created to contain all of the work I've been doing on the project, which I could have been done all the way back to v0.7 in 2011, but didn't out of respect for Simen. However, recently, a new job and two demanding kids has sidelined me more than I expected. Any new work I publish, I intend to put in the gnea group.
