### ISSUE TITLE
Sometimes z axis won't going up

### ISSUE THREAD

**Issue by alfarosi** [grbl/grbl#1772]
My z axis sometimes won't going up. So if I'm doing 2d contour, z axis move from z0.5 to z5 and then to z-1. But sometimes it wont go to z5 dispite it was written z5 on the g code. And its destroying my works because now it has to run to 5.5mm depth instead of 0.5. any solution?

**Comment by c3ntaur** [comment]
I had a similar problem, on a plasma cutting table though, where the z axis was just moving if I gave it a big distance to move. My problem has been that the spindle of the z movement was so hard to turn and had some "flex" (?) in it that it didn't stay in the position it should when moved small steps. Solution for me was always have current running through the stepper to provide a holding torque. Might have nothing to do with your setup. But maybe it's worth checking...

**Comment by c3ntaur** [comment]
by the way it's the "step idle delay", if you put 255 in there, the steppers are always turned on

$1 = 255

**Comment by alfarosi** [comment]
For my problem, it turns out my stepper driver get overheated and now completely dead. Replacing new driver and adding little fan and the problem is gone now.
