### ISSUE TITLE
A homing cycle on the 4th axis 

### ISSUE THREAD

**Issue by Turner66** [grbl/grbl#1778]
Hello,
I have a 4 axis grbl version running on my arduino uno. 
I would like to rewrite the program so that I can also perform a homing cycle on the 4th axis.
My problem is that I don't understand the pin numbering of Grbl.

For example at "#define Z Limit Bit 4 // uno digital pin 12" the z limit bit is at my arduino the pin input 12 but written is 4. 
Now how can i change for example the input to digital pin 13 ?

I am a complete beginner in programming and would appreciate any help.

With kind regards 
Tim

**Comment by langwadt** [comment]
https://components101.com/sites/default/files/component_pin/Arduino-Uno-Pin-Diagram.png

pin 12 in on  PB4, pin 13 in on PB5
