### ISSUE TITLE
getting a confirmation after gcode executed

### ISSUE THREAD

**Issue by Hugoat06** [grbl/grbl#1782]
Hello ! Does GRBL can give a confirmation once an action is done ?

By example : i send the first gcode request, then i'd like to wait for a confirmation once it's done to do something with another device and then send the second gcode request.

Thank you by advance.

**Comment by langwadt** [comment]
use a dwell (e.g. G4 P0.1) https://linuxcnc.org/docs/2.6/html/gcode/gcode.html#sec:G4-Dwell

it replies with ok, once it and everything before it is done

**Comment by Hugoat06** [comment]
> use a dwell (e.g. G4 P0.1) https://linuxcnc.org/docs/2.6/html/gcode/gcode.html#sec:G4-Dwell
> 
> it replies with ok, once it and everything before it is done

Thank you !
