### ISSUE TITLE
How to modify GRBL to keep the dir pin Z in the last state, even if the other axes walk ?

### ISSUE THREAD

**Issue by ClaxClax** [grbl/grbl#1805]
hello, for a very specific installation I would need to modify this in grbl: when the z axis goes up the z axis dir pin is LOW when it goes down the z axis dir pin High, but at the moment that another axis (X or Y) walks , it automatically goes to Low, is there any way to change this so that it stays in the high state until the z axis actually changes it?
Thank you

**Comment by langwadt** [comment]
https://github.com/gnea/grbl/issues/640

**Comment by ClaxClax** [comment]
it worked ! thank you very much !!!!
