### ISSUE TITLE
Couldn't enable/disable the hard limit settings. Couldn't find a setting with key $22 to update.

### ISSUE THREAD

**Issue by dottorepie** [grbl/grbl#1839]
Hi, I am new in the field and I don't know how to solve this problem. I am using an Arduino Uno as a controller and I think I have uploaded the grbl firmware correctly. Can someone direct me on what I am doing wrong regarding the Error mentioned in the title? The Error comes out in the setup wizard when I am trying to enable homing in UGS.

**Comment by breiler** [comment]
Sounds like a UGS issue, close this and head over to https://github.com/winder/Universal-G-Code-Sender and create an issue there.

**Comment by dottorepie** [comment]
thank you!
