### ISSUE TITLE
Pen up/down is not working wit bachin draw software 

### ISSUE THREAD

**Issue by ghost** [grbl/grbl#1863]
I am using grbl 1.1f and bachin draw software, the problem is grbl pen up/down command is M03 Sxx but bachin draw software sends SM03 Sxx the pen up/down is not working please tell me how to solve it I don't want to use other software

**Comment by breiler** [comment]
`SM03 Sxx` is not a valid GCode, it won't work with GRBL.

You should maybe contact the maintainers of Bachin.
