### ISSUE TITLE
Bachin draw software servo problem 

### ISSUE THREAD

**Issue by ghost** [grbl/grbl#1864]
Hi
I am using bachin draw software for CNC pen servo machine. The problem is when we click pen up/down buttons (machine type - pen writing machine with servo) the software send SM03 Sxx but grbl supports M03 Sxx, please help me to solve these 

![Uploading IMG20240114123315.jpg…]()

**Comment by breiler** [comment]
Why do you post yet another issue?

As I already wrote to you in #1863, `SM03 Sxx` is not a valid gcode command. This is not a GRBL problem, contact Bachin.

As a workaround I guess that you can search and replace all `SM03` with `M03`?
