### ISSUE TITLE
grbl 'crashes'

### ISSUE THREAD

**Issue by TomKamphuys** [grbl/grbl#1873]
I have an arduino clone with a CNC shield, drivers and steppers. I'm planning to control them from Octave (Matlab clone), so I wrote some functions. I found that the motors would stop moving either very quickly (motion from first command not completed yet) or always during an endurance test. 
I tried Universal Gcode Sender to rule out Octave, its serial package and my own code. USG at first seemed to be a bit more stable at first, but every endurance test has failed. Note that endurance test is only ~100 moves of 50mm of each axis.

I removed the CNC shield as people blame EMI: same result

I used a different grbl version (0.8c 9600 baud): same result

I used different USB cables with shielding and beads: same result

I used different CH340 drivers: same result

I tried a different port on my windows laptop: same result

I tried my raspberry: unsuccessful, at least up to now

In most of the cases the arduino is sending back a lot of data (nonsense I guess):

`
...
$234 = 250.000   
$235 = 250.000   
$243 = 250.000   
$244 = 250.000   
$245 = 250.000   
$253 = 250.000   
$254 = 250.000   
$255 = 250.000   
$7 = 250.000   
$8 = 250.000   
$9 = 250.000   
$17 = 250.000   
$18 = 250.000   
$19 = 250.000   
$27 = 250.000    (Homing switch pull-off distance, millimeters)
$28 = 250.000   
$29 = 250.000   
$37 = 250.000   
$38 = 250.000   
$39 = 250.000   
$47 = 250.000   
$48 = 250.000   
$49 = 250.000   
$57 = 250.000   
$58 = 250.000 
...  `

and the RX (yes, RX) is lit constantly. The TX LED light up dimly every second or so.

Quite often it comes back to life and I can try again only to have it 'crash' again at some time.

What is going on? What am I doing wrong? What other tests can I do to debug this problem?

**Comment by TomKamphuys** [comment]
I did some more tests. Just the Uno in the laptop; no shield, no motors, no limit switches. Limit switches turned off and not inverted.

`
>>> $$
$0 = 10    (Step pulse time, microseconds)
$1 = 25    (Step idle delay, milliseconds)
$2 = 0    (Step pulse invert, mask)
$3 = 0    (Step direction invert, mask)
$4 = 0    (Invert step enable pin, boolean)
$5 = 0    (Invert limit pins, boolean)
$6 = 0    (Invert probe pin, boolean)
$10 = 1    (Status report options, mask)
$11 = 0.010    (Junction deviation, millimeters)
$12 = 0.002    (Arc tolerance, millimeters)
$13 = 0    (Report in inches, boolean)
$20 = 0    (Soft limits enable, boolean)
$21 = 0    (Hard limits enable, boolean)
$22 = 0    (Homing cycle enable, boolean)
$23 = 0    (Homing direction invert, mask)
$24 = 25.000    (Homing locate feed rate, mm/min)
$25 = 500.000    (Homing search seek rate, mm/min)
$26 = 250    (Homing switch debounce delay, milliseconds)
$27 = 1.000    (Homing switch pull-off distance, millimeters)
$30 = 1000    (Maximum spindle speed, RPM)
$31 = 0    (Minimum spindle speed, RPM)
$32 = 0    (Laser-mode enable, boolean)
$100 = 250.000    (X-axis travel resolution, step/mm)
$101 = 250.000    (Y-axis travel resolution, step/mm)
$102 = 250.000    (Z-axis travel resolution, step/mm)
$110 = 500.000    (X-axis maximum rate, mm/min)
$111 = 500.000    (Y-axis maximum rate, mm/min)
$112 = 500.000    (Z-axis maximum rate, mm/min)
$120 = 10.000    (X-axis acceleration, mm/sec^2)
$121 = 10.000    (Y-axis acceleration, mm/sec^2)
$122 = 10.000    (Z-axis acceleration, mm/sec^2)
$130 = 200.000    (X-axis maximum travel, millimeters)
$131 = 200.000    (Y-axis maximum travel, millimeters)
$132 = 200.000    (Z-axis maximum travel, millimeters)
ok
`

'Nothing' EMI sensitive attached, 'nothing' to cause EMI and yet I get ALARM 1: 

> An error was detected while sending 'G0X50Y50Z50': (ALARM:1) Hard limit has been triggered. Machine position is likely lost due to sudden halt. Re-homing is highly recommended. Streaming has been paused.

And sometimes the streaming of the file just stops. Nothing weird to see. I used a COM port monitoring tool, but I see nothing special.

**Comment by chamnit** [comment]
This certainly is weird. Your hard limits are disabled and shouldn’t give you this error. When I run into weird behavior, I try a n EEPROM restore ($rst=*) and connect direct to Grbl through a serial terminal program.

**Comment by TomKamphuys** [comment]
EEPROM restore did not help.

How do I connect direct to Grbl and what should I do after that? I'm on Windows.

**Comment by chamnit** [comment]
Arduino serial terminal works fine. Connect at 115200 baud and type in commands as you would. Grbl does not echo input.

**Comment by TomKamphuys** [comment]
I tried putty. Now I get the results/errors as in post #1 after a move. Grbl commands $ have not gone wrong, but not tested that extensively.

**Comment by chamnit** [comment]
What version of Grbl are you using and how are you flashing it to your arduino?

**Comment by TomKamphuys** [comment]
I'm mostly using the latest: 1.1 f or h. Can't check now. I'm at work. I've installed this using the arduino ide grbl upload.

I've also tested 0.8 something (c?) that I installed using xloader. Similar results.

**Comment by chamnit** [comment]
Ok. At this point, I’d try flashing the gnea/Grbl official hex build, rather than compiling. Also, I’d rule out your Arduino clone. Any reputable clone with a 328p or genuine should work.

**Comment by TomKamphuys** [comment]
I flashed 1.1h. Doesn't work either. The Arduino clone is a suspect, I agree. I don't have another board, no clone and no original arduino.

Do you havea favorite? Which one would you advice me to buy?

**Comment by TomKamphuys** [comment]
I created a test sketch that sends 10Hz data to the computer. I tested until 18k messages: no problem.

I created a test sketch that sends back what I sent to it: large amount of cycles: no problem.

Whatever I try with grbl: some problem.

**Comment by chamnit** [comment]
Grbl uses literally all available resources on the 328p processor. So simple tests may not uncover all issues. Given we’ve ruled out the compiler (flashing hex) , resetting eeprom, and GUI (direct connection), this only leaves hardware or something specific to your setup. Sorry I don’t have any other suggestions.

**Comment by TomKamphuys** [comment]
I checked whether the hex file is correctly written using avrdude. It reads back the hex file from the UNO and checks it with the original file: OK

On Friday I can borrow an arduino from a colleague.

**Comment by TomKamphuys** [comment]
I bought a real Arduino UNO: Works like a charm.

Thanks for your help!
