### ISSUE TITLE
Next step beyond Grbl?

### ISSUE THREAD

**Issue by chamnit** [grbl/grbl#202]
Here's an excerpt on an off-line discussion about where Grbl is going and what's next:

**chamnit** : This is something I've been thinking about often recently. Is Grbl done? Or have we pushed it about as far as it can go, only to find that it's really not worth the effort to keep cramming things in? 

So, for a long time now, I've been thinking that we should really strip down Grbl to just being a step translator. All it does is the bare minimum of moving the steppers and providing feedback on position, and other minor things. What I mean is that we take out the g-code parsing, planning, and all of the higher level control and place it on the controller, i.e. RPi, which is much faster, more capable, and doesn't need to be real-time per se. I envision that the controller would plan out everything and simply send the stripped down Grbl only small line segments for it to move and have roughly a second or two of execution in its buffer. So, the controller can issue brand new plans with new feed rate overrides on the fly with only a small lag. Anything sent to the Arduino would be considered finished. No need to involve these complicated checks or worry about re-planning anything onboard. 

What do think about this?  I think this would be relatively easy to do.

**jgeisler**: Heavy thoughts, but justified ones. I'd say the answer is yes and no. But "obsolete" is a bit too harsh.
grbl is a charming little tool and it works for thousands (I'd guess) and it will do so for the time to come. The entry barrier is as low as it can be and the video by Elija Insua the other day reminded me that there are also the hard core hackers who like to use the command line and scripts and piping and stuff. And I think grbl is not complete yet. I'm not sure exactly how much resources we have left, but I think most of the stuff we currently have in the pipeline will fit in (including spindle pwm - maybe even for LASERs). And then there is still the mega644 based boards running at 20MHz ... We might even be able to install a 4th axis - maybe even for extruders ... And it's worth the effort to try to cram as much as possible into this little board:
No need for an Arduino plus RPi plus PC, just Arduino plus PC
The GCode interface is the most natural, common and hackable one
The GCode interface is easier to debug for the average user
Light-weight headless setups are easier to put together (to me, a RPi doesn't count as headless because it is a fully developed PC)
Hackers don't have to deal with code on two platforms
Once it's done, grbl is pretty awesome (even more awesome than it already is) and quite complete in my eyes as well
Anything beyond, like canned cycles, can truly be done by the feeder
So, grlb is the hacker tool.
From a product point of view, the move-interface is the more natural choice, and I have seen exactly this been done commercially somewhere. This would be a totally different project and no competitor for grbl - even if it would start of from the same code base. Getting started would be mostly a matter of duty. But you would need a team working closely together on two platforms.
Some issues might ensue from the fact that the controller doesn't always have enough moves buffered to safely come to a full stop. This might be a problem for feed hold. Generally any real time interaction and stuff where the current position needs to be monitored, like e.g. jogging or homing, will be slightly more difficult.
But once these are tackled there are so many possibilities ... One that immediately comes to my mind is the control of BLDC motors in a position feedback loop - something even EMC2 cannot do! 
I know stepper are the tool of choice for hobbyist. But this might be solely due to the fact that out-of-the-box position control is not cheaply available. If the aim of the exercice is to become more "professional" then position control using cheaper and more powerful BLDCs should be considered.

So, my verdict is: stick to the current grbl development path (features and then make-config for diversification) and start a new project if demand and resources are present.

**Comment by luunguyencdt** [comment]
Does anybody change the way Grbl work?
I want to algorithm on PC, i mean i will design GUI (by C#) and algorithm the same as planner.c work. After that, i have just send data to MCU which is receive and control direct Axis.
