### ISSUE TITLE
Grbl + (2 Stepper motor) + (standard servo) = Mugbot.

### ISSUE THREAD

**Issue by EmmanuelAdetutu** [grbl/grbl#220]
Awesome !! Now I have the GRBL flashed and works like a charm controlling my X,Y axis on my mugbot/painter like I want. 
Now I need to make it control a simple standard servo for the penlift  "http://www.adafruit.com/products/155 " . Any info/direction on how to do this will be well appreciated!!.

**Comment by natevw** [comment]
I came across [Z-Axis servo driver](http://www.thingiverse.com/thing:224969) today. It looks like a very simple circuit to wire and uses a cheap ATtiny to convert stepper signals output from GRBL, to servo PWM.

**Comment by DmitryZlato** [comment]
Hello guys! Sorry for stupid question, how to flash the firmware what @derFrickler and @shapeoko says about? I mean this https://github.com/heise/GRBLDRILL/raw/master/GRBL/grbl.hex . I see in a repository archive a bat-file for AVRDude, but it is not working. Of course, I changed com-port name to actual name. I have no any programmer device, just connect my Arduino Uno r3 to PC via USB. Could you help me, please. Oh, I forgot, AVRDude says "avrdude: stk500_getsync(): not in sync: resp=0x00"

**Comment by robottini** [comment]
I write a GRBL 0.9i change to support a servo motor with M03 Sxxx and M05 command. The link is: https://github.com/robottini/grbl-servo

**Comment by afingrut** [comment]
I'm looking into the possibility of diving more than one servo using grbl.  Has anyone encountered this? Is there a straight forward solution?

**Comment by eatyone** [comment]
robttini, i've tried your code, many thnx. I've just have a problem, when i send M03 S010 for exemple, the motor start, but never stop... (uno R3 and a parallax servo). Any idea?

**Comment by eatyone** [comment]
(it was a continous servo, not a servo) have to find a real servo now.

**Comment by aldoeuge** [comment]
hello, i have a problem when using GRBLDRILL, the y axis sometimes moves back and forth , and some other times it only moves one way, and it doesnt really work, ive tried using the regular grbl v.9 and it works perfectly, both axis move perfectly. so its a grbldrill problem, anyone has solved this?? thank you
