### ISSUE TITLE
GRBL Hardware Suggestions

### ISSUE THREAD

**Issue by Protoneer** [grbl/grbl#231]
Hi all....

I working on developing new hardware for GRBL. My question, is there demand for specially developed hardware for GRBL? And if so what are they?

My thoughts were to start with some simple stuff like a spindle controller that can control the speed of a brush-less DC motor.(G-Code : M3-5 and S http://linuxcnc.org/docs/html/gcode/m-code.html#sec:M3-M4-M5)

Anyone know of similar projects that might help speed up my development?

Second goal would be to add a few general purpose relays to control extra components like airflow, dust extracting, lights, cover locks or even warning alarms.(G-Code : M62-65 http://linuxcnc.org/docs/html/gcode/m-code.html#sec:M62-M65)

I am also looking at going down the I2C path connecting the main GRBL arduino with smaller ATMEGA8 or ATTiny85/84 micro-controllers. (The hardware will be in an Arduino Shield form keeping the communication distance close)

**Comment by jverban31** [comment]
> Hi all....
> 
> I working on developing new hardware for GRBL. My question, is there demand for specially developed hardware for GRBL? And if so what are they?
> 
> My thoughts were to start with some simple stuff like a spindle controller that can control the speed of a brush-less DC motor.(G-Code : M3-5 and S http://linuxcnc.org/docs/html/gcode/m-code.html#sec:M3-M4-M5)
> 
> Anyone know of similar projects that might help speed up my development?
> 
> Second goal would be to add a few general purpose relays to control extra components like airflow, dust extracting, lights, cover locks or even warning alarms.(G-Code : M62-65 http://linuxcnc.org/docs/html/gcode/m-code.html#sec:M62-M65)
> 
> I am also looking at going down the I2C path connecting the main GRBL arduino with smaller ATMEGA8 or ATTiny85/84 micro-controllers. (The hardware will be in an Arduino Shield form keeping the communication distance close)

hello, did you end up with GRBL to AATINY85?, cheers, John
