### ISSUE TITLE
Support to CoreXY

### ISSUE THREAD

**Issue by zanderbier** [grbl/grbl#286]
Hello,

Thanks to GRBL I am starting in the CNC world. As I want to build a machine with the CoreXY (http://corexy.com/), I am porting this support from Marlinv1 to GRBLv0.8.

Still has some bugs, but I am working on it.

- [x] Universal GCode Sender or GRBL Controller shows A and B position and not X and Y as expected
- [x] Not tested the limits, because the switches are not installed in my machine yet, so maybe they will not work properly
- [x] Using $6 variable to invert axis do not work as expected to X and Y. Z is not affected.

Here is the preliminar support. With it is possible to send files or GCode and see the correct movement of axis.

```diff
Port from Marlin v1
diff -Naur grbl-master//config.h grbl-v08-corexy//config.h
--- grbl-master//config.h       2013-10-21 19:19:26.000000000 -0700
+++ grbl-v08-corexy//config.h   2013-11-07 03:01:57.000000000 -0800
@@ -171,6 +171,10 @@
 // successful values for certain setups have ranged from 10 to 20us.
 // #define STEP_PULSE_DELAY 10 // Step pulse delay in microseconds. Default disabled.

+// Enable CoreXY kinematics
+// http://corexy.com/
+#define COREXY // Default disabled. Uncomment to enable.
+
 // ---------------------------------------------------------------------------------------

 // TODO: Install compile-time option to send numeric status codes rather than strings.
diff -Naur grbl-master//planner.c grbl-v08-corexy//planner.c
--- grbl-master//planner.c      2013-10-21 19:19:26.000000000 -0700
+++ grbl-v08-corexy//planner.c  2013-10-15 09:57:17.000000000 -0700
@@ -356,13 +356,30 @@

   // Compute direction bits for this block
   block->direction_bits = 0;
-  if (target[X_AXIS] < pl.position[X_AXIS]) { block->direction_bits |= (1<<X_DIRECTION_BIT); }
-  if (target[Y_AXIS] < pl.position[Y_AXIS]) { block->direction_bits |= (1<<Y_DIRECTION_BIT); }
+  #ifndef COREXY
+    if (target[X_AXIS] < pl.position[X_AXIS]) { block->direction_bits |= (1<<X_DIRECTION_BIT); }
+    if (target[Y_AXIS] < pl.position[Y_AXIS]) { block->direction_bits |= (1<<Y_DIRECTION_BIT); }
+  #else
+    if ((target[X_AXIS]-pl.position[X_AXIS]) + (target[Y_AXIS]-pl.position[Y_AXIS]) < 0) {
+      block->direction_bits |= (1<<X_DIRECTION_BIT);
+    }
+    if ((target[X_AXIS]-pl.position[X_AXIS]) - (target[Y_AXIS]-pl.position[Y_AXIS]) < 0) {
+      block->direction_bits |= (1<<Y_DIRECTION_BIT);
+    }
+  #endif
   if (target[Z_AXIS] < pl.position[Z_AXIS]) { block->direction_bits |= (1<<Z_DIRECTION_BIT); }

   // Number of steps for each axis
-  block->steps_x = labs(target[X_AXIS]-pl.position[X_AXIS]);
-  block->steps_y = labs(target[Y_AXIS]-pl.position[Y_AXIS]);
+  #ifndef COREXY
+    // default non-h-bot planning
+    block->steps_x = labs(target[X_AXIS]-pl.position[X_AXIS]);
+    block->steps_y = labs(target[Y_AXIS]-pl.position[Y_AXIS]);
+  #else
+    // corexy planning
+    // these equations follow the form of the dA and dB equations on http://www.corexy.com/theory.html
+    block->steps_x = labs((target[X_AXIS]-pl.position[X_AXIS]) + (target[Y_AXIS]-pl.position[Y_AXIS]));
+    block->steps_y = labs((target[X_AXIS]-pl.position[X_AXIS]) - (target[Y_AXIS]-pl.position[Y_AXIS]));
+  #endif
   block->steps_z = labs(target[Z_AXIS]-pl.position[Z_AXIS]);
   block->step_event_count = max(block->steps_x, max(block->steps_y, block->steps_z));

@@ -371,8 +388,13 @@

   // Compute path vector in terms of absolute step target and current positions
   float delta_mm[3];
-  delta_mm[X_AXIS] = (target[X_AXIS]-pl.position[X_AXIS])/settings.steps_per_mm[X_AXIS];
-  delta_mm[Y_AXIS] = (target[Y_AXIS]-pl.position[Y_AXIS])/settings.steps_per_mm[Y_AXIS];
+  #ifndef COREXY
+    delta_mm[X_AXIS] = (target[X_AXIS]-pl.position[X_AXIS])/settings.steps_per_mm[X_AXIS];
+    delta_mm[Y_AXIS] = (target[Y_AXIS]-pl.position[Y_AXIS])/settings.steps_per_mm[Y_AXIS];
+  #else
+    delta_mm[X_AXIS] = ((target[X_AXIS]-pl.position[X_AXIS]) + (target[Y_AXIS]-pl.position[Y_AXIS]))/settings.steps_per_mm[X_AXIS];
+    delta_mm[Y_AXIS] = ((target[X_AXIS]-pl.position[X_AXIS]) - (target[Y_AXIS]-pl.position[Y_AXIS]))/settings.steps_per_mm[Y_AXIS];
+  #endif
   delta_mm[Z_AXIS] = (target[Z_AXIS]-pl.position[Z_AXIS])/settings.steps_per_mm[Z_AXIS];
   block->millimeters = sqrt(delta_mm[X_AXIS]*delta_mm[X_AXIS] + delta_mm[Y_AXIS]*delta_mm[Y_AXIS] +
                             delta_mm[Z_AXIS]*delta_mm[Z_AXIS]);
```

**Comment by Techrat** [comment]
Hey there,

Thanks for the email.  I have been away from my computer during the
holidays so I apologize for the delayed response.  In any case, I will be
glad to test out the firmware on my coreXY machine however if you can
provide copy of the source so I can compile myself I will  appreciate it.

Thanks,
Jeff

**Comment by metropt** [comment]
Hi @chamnit 
Can you share what you have?

Thank you

**Comment by cri-s** [comment]
http://www.datafilehost.com/d/005634a4
bit7 of report flag ($10) is used to switch between normal or corexy coord display.
check out what work and what not work and i fix it.

**Comment by metropt** [comment]
It has home cycle implemented?

**Comment by cri-s** [comment]
I dont have checked it explitly. 
The coord translation is made inside plan-buffer-line so it should work.

**Comment by cri-s** [comment]
@Techrat 
please send me a email at  corexy@trashmail.com 
In order to get in contact offlist.

**Comment by chamnit** [comment]
@metropt : I'll work on pushing what I have. I've got a few different new versions of Grbl written and need to consolidate some this stuff to figure out what I should push. I know it's been a while, but I've been doing a lot of Grbl-related future planning these past few months. There going to be some exciting new things announced shortly.

**Comment by cmonr** [comment]
@chamnit: Looking forward to the CoreXY consolidation!

I currently have a CoreXY machine up and running well on an Azteeg X3 with Marlin firmware ([video proof](http://www.anomalousmaker.com/updates/2014/12/31/woo-it-works)), but most of what I'm doing isn't 3D Printer related. I'd live to jump ship to GRBL since it has everything that I need, and nothing that I don't.

Is this the best place to be notified of updates on GRBL, or would somewhere else be appropriate?

**Comment by metropt** [comment]
@chamnit thank you :)

@cri-s the link you sent me doesnt work :s

**Comment by chamnit** [comment]
@metropt : Ok. I pushed what I have. I haven't tested it, but it should technically work, especially homing and feed holds. The only thing that I still have to do is figure out the invert direction mask. It probably doesn't work properly, but you shouldn't be messing with it anyway with a CoreXY machine. Let me know how it goes.

**Comment by metropt** [comment]
@chamnit  thank you, just to let you know that the first testes looks very good :)

**Comment by chamnit** [comment]
Any CoreXY users out there? Does it work?

**Comment by metropt** [comment]
Me :) I'm using it with home and it is working but I'm still building my machine and only after will I  be able to do some stress test.

**Comment by Giorgio-Olivero** [comment]
hello, @chamnit @metropt 
Context here and problem/issue at the bottom: we have built an H-Bot plotter that will draw through the use of a ferrous ink (a.k.a. ferrofluid) and a Z-axis that raises a neodymium magnet. So far everything works/moves fine except 'homing'. The machine blueprint lasercut files and the Processing code that sends 'live' Gcode to GRBL will be published under an open license. 

ISSUE: I'm using a version of GRBL 0.8c that doesn't support 'homing'. 
I found this thread while googling for a solution and looks like @chamnit pushed it recently. I'm not familiar with Github so I don't really understand how to get it. Can you point me to the right direction?

[see machine pics here:
https://instagram.com/p/yIXDFxqo_T/?modal=true
https://instagram.com/p/yIWx-2qo-z/?modal=true
https://instagram.com/p/zdf7ezKo0O/?modal=true
https://instagram.com/p/yIW7TDKo_E/?modal=true ]

**Comment by chamnit** [comment]
@Giorgio-Olivero : Grbl v0.9i supports CoreXY. It's in the edge branch as a config.h option.

**Comment by Giorgio-Olivero** [comment]
@chamnit Thanks 

On the edge branch i found 0.9g instead of 0.9i (was it a typo in your message?)

Summarizing, following the instruction from the config.h:

// new homing cycle, substituting with these lines:
#define HOMING_CYCLE_0 (1<<X_AXIS) 
#define HOMING_CYCLE_1 (1<<Y_AXIS)

// and this below goes uncommented
 #define COREXY 

correct?

**Comment by metropt** [comment]
yes

**Comment by Giorgio-Olivero** [comment]
I tried but it doesn't compile

here are the errors:

Arduino: 1.5.5 (Mac OS X), Board: "Arduino Uno"
In file included from sketch_feb25a.ino:2:
/Users/Gio/Documents/Arduino/libraries/GRBL/coolant_control.h:27: error: variable or field 'coolant_set_state' declared void
/Users/Gio/Documents/Arduino/libraries/GRBL/coolant_control.h:27: error: 'uint8_t' was not declared in this scope
/Users/Gio/Documents/Arduino/libraries/GRBL/coolant_control.h:28: error: variable or field 'coolant_run' declared void
/Users/Gio/Documents/Arduino/libraries/GRBL/coolant_control.h:28: error: 'uint8_t' was not declared in this scope
In file included from sketch_feb25a.ino:6:
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:137: error: 'uint8_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:138: error: 'uint8_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:139: error: 'uint8_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:140: error: 'uint8_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:141: error: 'uint8_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:143: error: 'uint8_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:144: error: 'uint8_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:145: error: 'uint8_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:146: error: 'uint8_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:147: error: 'uint8_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:153: error: 'uint8_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:154: error: 'int32_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:159: error: 'uint8_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:169: error: 'uint8_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:170: error: 'int32_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:172: error: 'N_AXIS' was not declared in this scope
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:174: error: 'N_AXIS' was not declared in this scope
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:176: error: 'N_AXIS' was not declared in this scope
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:186: error: 'uint8_t' does not name a type
/Users/Gio/Documents/Arduino/libraries/GRBL/gcode.h:197: error: 'uint8_t' does not name a type

**Comment by chamnit** [comment]
@Giorgio-Olivero : Compiling through the Arduino IDE has change in v0.9i. I haven't written it up yet, but there should be a GrblUpload example that you can open via the File drop down menu. Should only contain one include for grbl.h

**Comment by Giorgio-Olivero** [comment]
homing works! <3
thanks so much!

**Comment by briangonzalezmia** [comment]
@chamnit I also have an H-bot with the g-Shield v5 running Grbl v.9i, however, homing is hit or miss right now. Sometimes it get there and homes perfectly and others it moved in .025mm increments (as per UGS status info). Not sure why, but I was hoping for some advice. Cheers, Brian.

**Comment by texruska** [comment]
Is anybody experiencing strange homing behaviour? I've built a coreXY machine and the hard limits work fine in ordinary use, but what I see happening during a homing cycle is:
* moves quickly to positive X hard limit
* quickly moves in negative X direction for a seemingly arbitrary distance
* very very very slowly moves in the negative Y direction and becomes unresponsive to any hard limits being pressed
