### ISSUE TITLE
Y and Z Axis move in one way only

### ISSUE THREAD

**Issue by gblanco** [grbl/grbl#287]
Hi,

I'm running Grbl on an Arduino uno (tried 0.9a and 0.8c) with the same results. Axis X moves back and forth, Axis Y moves one way only.

Tried already reversing the wiring, reversing one phase, 2 different arduinos....

I can see with my multimeter that Y Dir pin doesn't change it's state (always 0V), I believe is the root of my problem (and Z axis is the same). 
I understand that here lays my problem, any suggestion on why can this be happening?

I have no limit switches at all. 

Switching Driver for X and Y, makes no difference.

Regards

Gustavo

**Comment by Neevan1991** [comment]
hi sir, i am using GRBL laser ver 0.9. when i am controlling the direction in the grbl for X axis. the stepper motor it rotates  in same direction for all axis movement. please help me on this

**Comment by epworth2** [comment]
All this and the driver trans is probably smoked
