### ISSUE TITLE
Homing cycle only x and y axis issues

### ISSUE THREAD

**Issue by philmurp** [grbl/grbl#293]
So I have wired limit switches into my X and Y axis. When I wire my limit switch, and then enable hard limits with $16=1, I cannot move my steppers. No matter what command I input, it will not execute. It seems like my limit switches are freezing my system. My G-Code Sender doesn’t give any alarm or any indication that the limit switch has been triggered. When I try and make a move to say G0 X-2, my X-Axis light flashes for a second then the system doesn’t recognize any commands beyond that point. When I try a soft reset of GRBL at this time, it says ‘wait interrupted by user’. I have tried using just one X-Axis limit switch and all sorts of combinations but I cannot figure out what is causing this issue or even what the issue is. When I close out of my grbl controller and restart the system and input $16=0 then everything works fine so it does appear to be an issue with my limit switches. I am using grbl .8c and wiring my limit switches between pin and ground in NO orientation with a 10K Ohm Resistor between pin and Vcc.

After reading some documentation, it appears that with hard limits enabled, the grbl is locked until there is a homing cycle run. However, I only have X and Y limit switches and when i enter $H, it homes the Z axis. Is there anyway to set grbl so that only the X and Y axis are homed so that this problem can be resolved?

Thanks in advance for any help or suggestions, I am really stuck on this issue and have not been able to find any documentation online that addresses something like this.

**Comment by garthanstey** [comment]
If I can quickly go back to the original Homing issue. Has anybody created a Nano grbl1.1f hex file suitable for an XY only Laser device. I can worry about screening the wires when I get a system that wants to home. I'm sure this would take pride of place in the downloads. Maybe I'm being naïve but couldn't $22 be set up to take the order of priority eg. $22 ZXYA instead of Boolean?
