### ISSUE TITLE
Coordinate transformation

### ISSUE THREAD

**Issue by lukeskymuh** [grbl/grbl#33]
Hi Simen,

Thank you for Grbl, it is realy greate!
I want to build a CNC Router where the stepper axis does not correspond to the x,y,z. So I have to make a coordinate transformation. My plan was to use Grbl and add a "tranformation" function from xyz to the stepper coordinates. But where would be the best place in the code to make this transformation? Do you have an advice how I can implent it in your code?

Thanks in advance!
Luke

**Comment by soswow** [comment]
@simen link is dead. It seems like i do something similar.
