### ISSUE TITLE
Cycle Start/Resume On/Off Spindle

### ISSUE THREAD

**Issue by lilo003** [grbl/grbl#339]
@chamnit ,

It is possible to enable a function in Grbl that when I pause the work I turn off the spindle and restart/resume turn on the spindle again?

**Comment by chamnit** [comment]
Done. New safety door feature installed into Grbl will de-energize the machine after feed holding and re-energize when resumed. Just pushed in v0.9h edge branch.

**Comment by JesseFo** [comment]
Is this possible purely with commands?
I use the @ command to de-energize the spindle on feed hold, but when attempting to resume, the machine remains in door state
