### ISSUE TITLE
QUERY: MIT-licensing for GRBL.

### ISSUE THREAD

**Issue by chamnit** [grbl/grbl#351]
Recently, there has been a lot of off-line conversations between the major contributors and copyright holders of Grbl, @simen, @jgeisler0303, and myself. We are thinking about fully-opening up Grbl and re-releasing it under the unrestrictive MIT-license, rather than keep it on GPLv3.

We understand that there are some risks involved with the unrestrictive MIT-license, where people can easily abuse it (i.e. patents). But, we feel that it could also further encourage development and the proliferation of Grbl. Frankly, we're tired of seeing terrible motion control software in commercial 3D-printer machines and think an unrestricted Grbl firmware can help them out a lot and even the playing field.

At a bare minimum, we feel that the older versions of Grbl (v0.8c and prior) can be immediately re-released under the MIT-license. The newest version of Grbl v0.9 will likely stay under GPL until we can figure the ramifications of this change.

So, to all the minor contributors to Grbl and users, what you do think about this? Does anyone have a strong objection to this?

**Comment by ajprax** [comment]
Hi,

I've read the conversation here and found an announcement (http://bengler.no/blog/grbl-with-permissive-license-mit) that GRBL was moving to the MIT license, and I see that COPYING briefly included MIT, but it was fairly quickly reverted to only GPL3. Was a determination made to stick with only GPL going forward?

I have a commercial application for which GPL may be acceptable (still researching), but for which MIT would definitely work. I appreciate the reasons for using GPL, so if you've decided that's the only license GRBL will be offered under, I'll understand.

Thanks
