### ISSUE TITLE
grbl keeps crashing after some time

### ISSUE THREAD

**Issue by CaptainFeature** [grbl/grbl#384]
Hello there

I have just started playing with grbl v0.8. I am using an arduino uno and the cnc shield from protoneer, version 3.03. I’m currently struggling with two problems (in two separate issues):

1) Crashing during movement:

I first used the grbl version from protoneer and loaded it on my arduino uno using the arduino ide. After having some problems I downloaded the hex version v0.8 from here and burnt it the arduino using avr studio.

Unfortunately I still experience the problem that  the machine stops in the middle of a movement with some alarm stop. This typically happens after some Time (20 Minutes or so?). I am using Universal G-Code sender which is freezing at the moment of the alarm which makes further operation impossible. I then have to reset both the Arduino and the G-Code sender and redo all the work done so far.

What could be the reason for this?

Kind Regards
Marcel

**Comment by miszeli** [comment]
Hello , I have the same problem in my grbl
machine runs and suddenly stop, i hit the close / reset button in the port section of Grbl controller.
The axis finished their last move (like at you) .
First when i run new arduino , all works perfect ( about 5-6 times , the same g-code) and next these problems :( What can i do ?

**Comment by CaptainFeature** [comment]
Hi
Have you switched off the power saving options of your computer?
Regards

**Comment by miszeli** [comment]
Yep , i have maximum performance in power settings

**Comment by CaptainFeature** [comment]
Hi
I had another problem with grbl.
It is slightly different from yours. I mention it anyway, you never know:

Whenever switching on my main spindle grbl brought an limit switch error.
I fixed this by switching off the limit switches temporarily for switching on/off the spindle:

$16=0
G04 P1
M3
G04 P1
$16=1

Kind Regards

**Comment by electrokean** [comment]
@CaptainFeature this will be a coupled noise issue.  Do you have any noise filtering on your limit inputs, such as capacitors or ferrite beads?

**Comment by 109JB** [comment]
In regard to the power saving features: If using windows you have to specifically set the USB settings to prevent suspending USB in power options. Also, depending on the computer, there could be bios settings that affect the USB as well. Also make sure your chipset drivers are up to date.

http://www.techsupportalert.com/content/how-fix-annoying-windows-usb-problem.htm
