### ISSUE TITLE
"ALARM: Hard limit. MPos?" - Suddenly stop switches active on Arduino Nano/UniversalGCodeSender

### ISSUE THREAD

**Issue by Cysign** [grbl/grbl#406]
Hey guys, I don't know what's going on with my machine.
I replaced my Arduino Nano, changed shielded cables, changed opening-switches for closing-switches, tryed newest build of UniversalGcodeSender and GRBL (0.8C dated Dec 2013) but it still happens that UniversalGCodesender (1.0.5, 1.0.6, and 1.0.7) suddenly gets an stop-signal from my machine.

First I thought it might be an issue with the cables or the opening-switches I previously used. But as I changed everything I don't know what I could do.
Any suggestions?
Might it be any static charge?
I couldn't encounter any problems using an HP 3478A multimeter (which seems to be qauged).

Might it be a matter of Arduino Nano?
I have a Sinsmart Arduino Uno right in front of me...but it's not ready to go as I'd need to change all pinconnectors and flash GRBL on it (couldn't get this with ArduinoUploader the way I do with my Nano...).
So do you think that might be an GRBL issue or shall I swap over to my Uno to solve this problem?

**Comment by kenansatir** [comment]
Please use RFI, EMI, EMCi Noise Filters on limit switch cables (near to board) like :
https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20171102041903&SearchText=+RFI+EMI+EMC+Noise+Filter

But try to use big ones... about 2cm diameter....

Also connect your boards GND pin to ground...

Best regards
