### ISSUE TITLE
max step frequency of GRBL Atmega328p

### ISSUE THREAD

**Issue by pauljay** [grbl/grbl#41]
Is there anyone who achieves more than 40KHz step frequency of GRBL Atmega328p ?
I have executed several tests changing microstep level and seekrate of each axis.

The fastest one I have succeeded in is 38.4Hkz for each axis.
If I adjust parameters to get faster speed, then interrupt handler routines went wrong.
So the pulses in my osciloscope shows broken steps.
Also the EEPROM data area is broken to show incorrect values. But it shows correctly after reseting Atmega328p board.

**Comment by mihaisalajan** [comment]
Hi everyone

I have a small issue. please help me.

I just start using GRBL V0.8 firmware, my board is arduino uno the stepper is a nema14 200 steps /revolution the driver is a4988, i am turning a screw with 8mm lead that means 25 steps/ mm
but the motor is making a lot of noise and the speed is slow, if i set the steps at 100 steps/mm the axis is moving just fine without noise and the speed is just right but than when i tell it to move 1 mm it moves 4 mm (!!!obvious!!! ) i tried different speeds ($4 adn $5 from 100-3600) but nothing changes. i need to mention that i am using grbl controller  3.6.1 
i also tried different step pulses ($3) from 3 to 30 still without result 
another question how ca i set the _**tA**_ and **_tB_** from picture below at the value of **1µs**  , I had the impression that this is setup with the speed adjustment

or is it that _**tA**_  is $3 command and _**tB**_ is $4and $5 commands ?

![step a4988](https://cloud.githubusercontent.com/assets/11631805/16109894/cbd06dc2-33b3-11e6-9311-57a1c2d40375.JPG)

PS please excuse my english is not my native language

**Comment by oleometal** [comment]
que tengo que hacer para correr grbl a 100 khz, ?? 
nececito 500 khz para controlar un servomotor yaskawa.

**Comment by ibrahimuslu** [comment]
> que tengo que hacer para correr grbl a 100 khz, ??
> nececito 500 khz para controlar un servomotor yaskawa.

Hello oleometal, 

Did you achieve to run grbl in 100khz? I need to run Hiwin servo drivers at 600khz ? If you have any solution, could you share with us? Thank you. 
Hola oleometal, necesito correr Hiwin servomotors tambien a 600khz. puedes hacer un solucion? Gracias para tu contribucion.
