### ISSUE TITLE
Using Atmel Studio to compile GRBL

### ISSUE THREAD

**Issue by Moffy** [grbl/grbl#424]
First create a new project and select your target processor and give it a name e.g. "grbl328p". Delete the file grbl328p.c. Copy all the grbl .c and .h files into the directory where this file was found. Rename "main.c" to "grbl328p.c". Add all the rest of the .c and .h files to the project. Bingo, you can compile grbl in Atmel Studio with the benefits of an integrated environment.

**Comment by algo1980** [comment]
thank you all. that's been great help. :+1:

**Comment by algo1980** [comment]
why you closed it chamm :(
