### ISSUE TITLE
grbl-arm

### ISSUE THREAD

**Issue by mikejac** [grbl/grbl#469]
Hi,

(I don’t really know what I’m getting into, but here goes … )

As you know, the Arduino Zero is on it’s way. It features an Atmel SAM D21 MCU and Atmels Embedded Debugger. SAM D21 is an ARM Cortex M0+ MCU running at 48MHz.

I don’t have an Arduino Zero but an Atmel SAM D21 Xplained Pro Eval. Kit. It too features an SAM D21 MCU and the Embedded Debugger. It also has an EEPROM. Don’t know if the Zero has EEPROM.

So, what do you think about starting the port from atmega328p to SAM D21, especially if I do it? I’m not saying that I’ll be able to do it all, but at least start on it …

Before you answer, I have these points:

1) I’ll be using Atmel Studio 6.2. It’s only for Windows (it’s based on Microsoft Visual Studio) but at least it’s free.

2) How about getting grbl running on FreeRTOS?

3) And how about networking? This will have to be optional, as the Zero doesn’t have a network controller. I’ll be using the Micrel KSZ8851SNL/SNLI (it uses SPI to communicate with the host MCU) simply because the Atmel Software Foundation already have a driver for it as well as an ip-stack. Up front it could be ChiliPeppr JSON Server compatible so that ChiliPeppr can talk to it directly. MQTT also comes to mind :-)

Thoughts?

/michael

**Comment by sagonzal** [comment]
Hi...I'm planning on porting grbl to the Atmel SAM4S....is anyone still interested ?

**Comment by mschorer** [comment]
I have a version for ti's tiva available ...
I'm doing Hardware Abstraction via preprocessor only ...

markus schorer mobile

**Comment by sagonzal** [comment]
markus, sorry to ask, but what you mean with "preprocessor only ..." ?

**Comment by mschorer** [comment]
Hi, i wasn't too clear either ... :-)

I'm trying to use preprocessor macros to encapsulate The hw-abstraction. I
want to avoid #ifdef-fing Plattform dependent code all over The place - and
make code less readable. Also avoid additional cycles and memory
consumption for The standard arduino/avr case.
This works reasonably well - except for my additions to grbl. But this is
work in progress ...

Just have a look yourself: github.com/mschorer/grbl
<http://github.com/mschorer/grbl-tiva> in The tiva Branch ...

markus schorer mobile

markus, sorry to ask, but what you mean with "preprocessor only ..." ?

—
Reply to this email directly or view it on GitHub
<https://github.com/grbl/grbl/issues/469#issuecomment-125882043>.
