### ISSUE TITLE
Add ability to invert Spindle Enable

### ISSUE THREAD

**Issue by gerritv** [grbl/grbl#479]
when interfacing Grbl to a parallel port type driver, the motor enable triggers the spindle relay. Can we add (perhaps compile time only) option to invert this interface line? Currently it is active high, these boards need active low.

If you give me some guidance I would be happy to do the code myself and then submit it to the repository.

**Comment by natevw** [comment]
xref: https://github.com/grbl/grbl/issues/218#issuecomment-33391830
