### ISSUE TITLE
moving axes with with joystick

### ISSUE THREAD

**Issue by dvdnhm** [grbl/grbl#485]
I was thinking about using a joystick to move axes around for setting 'zero' point or tool change.

I ran some tests and found that X-DIR pins either Low or High based on axis' direction and X-STEP shows 140mV while the axis is moving.

Can I use -DIR and -STEP pins of all there axes to move them without sending a gcode?

**Comment by pfpmeijers** [comment]
Does this also work for the arduino nano?
