### ISSUE TITLE
Some 360 degree arcs are not executed at all

### ISSUE THREAD

**Issue by blinkenlight** [grbl/grbl#495]
Apparently I managed to stumble upon a ludicrously specific / obscure bug, which is nevertheless a quite severe one I think. I was trying to mill eight small full-circle (360 degree, endpoint same as starting point) arcs arranged symmetrically around (0,0) but when the dust settled, only six of them were milled -  two were completely untouched. Expressed in compass terms, the NE and SW circles were simply missing.

After a series of tests, this is the minimal sequence I could always reproduce the bug with:
- power up, without homing, so both machine and work positions are zero
- reposition the origin with "G10 L2 P1 X50 Y-50"
- execute "G0 X30 Y30"
- set feed "F250"
- execute "G03 X30 Y30 I-4.24264 J-4.24264" and... nothing happens at all!
- same thing for "G03 X30 Y30 I4.24264 J4.24264" (the other circle I mentioned)

The funny thing is, the other two quadrants work just fine - both "G03 X30 Y30 I4.24264 J-4.24264" and "G03 X30 Y30 I-4.24264 J4.24264" do get executed. The **really** funny thing though is that even "G03 X30 Y30 I-4.24260 J-4.24260" gets executed ok (only the last digits zeroed). Arcs in the other direction suffer the same problem, but in reverse - with G02, the "bad" arcs now work fine, but the "good" ones fail. Apparently, the bug is present both in the current latest 0.8c and 0.9g firmwares (I tested both).

For reference, this is my settings dump:
>$$
>$0=40 (step pulse, usec)
>$1=25 (step idle delay, msec)
>$2=7 (step port invert mask:00000111)
>$3=2 (dir port invert mask:00000010)
>$4=0 (step enable invert, bool)
>$5=0 (limit pins invert, bool)
>$6=0 (probe pin invert, bool)
>$10=3 (status report mask:00000011)
>$11=0.050 (junction deviation, mm)
>$12=0.002 (arc tolerance, mm)
>$13=0 (report inches, bool)
>$14=1 (auto start, bool)
>$20=0 (soft limits, bool)
>$21=0 (hard limits, bool)
>$22=0 (homing cycle, bool)
>$23=0 (homing dir invert mask:00000000)
>$24=25.000 (homing feed, mm/min)
>$25=500.000 (homing seek, mm/min)
>$26=250 (homing debounce, msec)
>$27=1.000 (homing pull-off, mm)
>$100=400.000 (x, step/mm)
>$101=400.000 (y, step/mm)
>$102=400.000 (z, step/mm)
>$110=1500.000 (x max rate, mm/min)
>$111=1500.000 (y max rate, mm/min)
>$112=1500.000 (z max rate, mm/min)
>$120=80.000 (x accel, mm/sec^2)
>$121=80.000 (y accel, mm/sec^2)
>$122=80.000 (z accel, mm/sec^2)
>$130=200.000 (x max travel, mm)
>$131=200.000 (y max travel, mm)
>$132=200.000 (z max travel, mm)
>ok

**Comment by chamnit** [comment]
@blinkenlight: Finally got to this problem and fixed it. Had to do with machine epsilon (floating point error) and the trig calculation as suspected. Installed a configurable machine epsilon for the problem calculation and verified that it works well and won't effect other arcs. Only took over 6 months to get the time! Better late than never.

**Comment by blinkenlight** [comment]
@chamnit: Glad you got around to fix this. No worries, we're all in this for the long haul... ;)
