### ISSUE TITLE
Huanyang VFD control through RS485 serial

### ISSUE THREAD

**Issue by misan** [grbl/grbl#516]
I have a VFD driver controlled using a serial connection. I am not using grbl at the moment but Marlin. I was told I should submit the code to grbl. I am not sure it can be of use here, but just in case here you have my code http://pastie.org/9660347

I understand it may be a too specific solution (it won't work with any other VFD brand) and it may require more memory than available as it needs an additional serial port (at least a TX line) and TX_enable pin too.  Good thing is spindle speed can be set this way too.

**Comment by Harvie** [comment]
What about some kind of plugin API, so we could compile stuff like this into grbl without need to modify grbl code every time when new version cames out? Just copy the Huanyang RS485 plugin in whatever version of grbl before compiling and have it supported would be great!

**Comment by jahnj0584** [comment]
You can natively control the VFD visa the PWM already

**Comment by Harvie** [comment]
@jahnj0584  i know, but there are several reasons why use RS485 instead (uses less wires, less prone to rf interference, more accurate RPM control, ...).

I don't think that grbl should support every VFD that exists, but it would be nice if there was simple way to write plugins for that.

**Comment by Harvie** [comment]
@misan Can you please send your huanyang VFD RS485 code to this issue? https://github.com/terjeio/grblHAL/issues/69 The pastie link is dead.

**Comment by MeJasonT** [comment]
RS485 wont be as good as you think it will.  Cheap communication drivers and cabling will lead to lots of problems,  I know i have tried it.  That may have somthing to do with why industrial line drivers cost in excess of £300.  The closer your electronics  get to the VFD the worse it gets.  You have to condider that a VFD is just a huge rudimentary amplifier built to drive an imperfect transducer which inherently is noisey as hell,  That great big jocking motor will transmit harminics like they are going out of fashion.  Arduinos have little to no filtering so they just love sucking up any rf noise, connect a loop of wire to it (all be it via a RS485 signal converter) you may end up enjoying your local radio station.  I applaud your enthusiasm but no. dont be tempted.  Dragons be there.

**Comment by MeJasonT** [comment]
There are cheap PWM to voltage converters on ebay which have opto isolation on the incomming signals, this is the route i would have gone had i did it all over again

**Comment by langwadt** [comment]
@MeJasonT I'm surprised you had issues with RS485, except when people leave out the failsafe biasing resistors I've only seen it be very reliable.

**Comment by Harvie** [comment]
@MeJasonT do not worry. i have experience with both PWM and RS485. also i don't think we need to discuss problems of physical layer during firmware development. RS485 is proven bus when properly implemented. Building CNC machines comes with challenges, but RS485 is not to blame.

**Comment by Harvie** [comment]
Now there seems to be quite elegant solution integrating Huanyang RS485 communication directly to GRBL, i would be happy if you can help with testing:
https://github.com/terjeio/grblHAL/issues/68
