### ISSUE TITLE
Machine Position not zeroed after homing...

### ISSUE THREAD

**Issue by iSynaptic** [grbl/grbl#527]
After a running a homing cycle, the machine position is not set to 0,0,0. Rather it is set to -290, -290, 0. I'm assuming it has something to do with the interaction between setting the homing direction and/or direction port masks and the x,y,z maximum travel.  I would expect it to treat the corner it homed to as 0,0,0.  Am I missing something?

Here are my settings:

***\* Connected to COM3 @ 115200 baud ****

Grbl 0.9g ['$' for help]
['$H'|'$X' to unlock]

> > > $$
> > > $0=10 (step pulse, usec)
> > > $1=255 (step idle delay, msec)
> > > $2=0 (step port invert mask:00000000)
> > > $3=7 (dir port invert mask:00000111)
> > > $4=0 (step enable invert, bool)
> > > $5=0 (limit pins invert, bool)
> > > $6=0 (probe pin invert, bool)
> > > $10=3 (status report mask:00000011)
> > > $11=0.050 (junction deviation, mm)
> > > $12=0.002 (arc tolerance, mm)
> > > $13=0 (report inches, bool)
> > > $14=1 (auto start, bool)
> > > $20=0 (soft limits, bool)
> > > $21=0 (hard limits, bool)
> > > $22=1 (homing cycle, bool)
> > > $23=3 (homing dir invert mask:00000011)
> > > $24=25.000 (homing feed, mm/min)
> > > $25=500.000 (homing seek, mm/min)
> > > $26=250 (homing debounce, msec)
> > > $27=1.000 (homing pull-off, mm)
> > > $100=40.000 (x, step/mm)
> > > $101=40.000 (y, step/mm)
> > > $102=320.000 (z, step/mm)
> > > $110=5000.000 (x max rate, mm/min)
> > > $111=5000.000 (y max rate, mm/min)
> > > $112=500.000 (z max rate, mm/min)
> > > $120=250.000 (x accel, mm/sec^2)
> > > $121=250.000 (y accel, mm/sec^2)
> > > $122=50.000 (z accel, mm/sec^2)
> > > $130=290.000 (x max travel, mm)
> > > $131=290.000 (y max travel, mm)
> > > $132=100.000 (z max travel, mm)
> > > ok

**Comment by siliconio** [comment]
find HOMING_FORCE_SET_ORIGIN in file config.h and read you selection & recompile...
