### ISSUE TITLE
Small pauses between code lines

### ISSUE THREAD

**Issue by designr47** [grbl/grbl#549]
I'm trying to use grbl with styrofoam cutting machine with hot wire, but i have a problem. I'm using gcodetools to create gcodes from my 2d drawings. I load and run the gcode and there is small pauses between codes when codes come to some detailed parts like hand of an angel. Those pauses causing melt of styrofoam because of hotwire. Is there a way to prevent pausing the machine. I'm uploading my gcode and I will upload a video that shows what i mean.

Gcode - > http://pastebin.com/LJwn3PQ2
Video - > http://www.youtube.com/watch?v=-civVR0H7LY

**Comment by StefanoImpellizzeri** [comment]
> Sto cercando di usare grbl con la tagliatrice di polistirolo con filo caldo, ma ho un problema. Sto usando gcodetools per creare gcodes dai miei disegni 2D. Carico ed eseguo il gcode e ci sono piccole pause tra i codici quando i codici arrivano ad alcune parti dettagliate come la mano di un angelo. Quelle pause che causano lo scioglimento del polistirolo a causa del filo caldo. C'è un modo per impedire di mettere in pausa la macchina. Sto caricando il mio gcode e caricherò un video che mostra cosa intendo.
> 
> Gcode -> http://pastebin.com/LJwn3PQ2
> Video -> http://www.youtube.com/watch?v=-civVR0H7LY

help me, I have the same and identical problem, but I haven't solved it

**Comment by winder** [comment]
@StefanoImpellizzeri try a different gcode sender. bCNC, cncjs and Universal Gcode Sender are all very popular

**Comment by StefanoImpellizzeri** [comment]
> @StefanoImpellizzeri try a different gcode sender. bCNC, cncjs and Universal Gcode Sender are all very popular

I use grbl, today I tried ugb, but the result is identical
