### ISSUE TITLE
Probing issues with inverted probe pin, $6 = 1 (0.9g)

### ISSUE THREAD

**Issue by zentoolworks** [grbl/grbl#559]
Hi, 

I have been testing probing with grbl 0.9g lately and I am having issues with inverted probe pin, or set $6=1.

When I am using $6=0, (normally open), the process went through fine, but when I set $6=1, (normally closed, especially useful for using a CNC probe for non metal surface), I always got an alarm says probe failed and requires a reset. Anyone else having the same experience. 

Thanks

Xin

**Comment by chamnit** [comment]
@zentoolworks : I'll check it when I get a chance, but it should be working ok.

**Comment by chamnit** [comment]
@zentoolworks : Had some time today to check this. It's working as intended, at least on v0.9h.
