### ISSUE TITLE
There are some official project to port GRBL on Arduino Mega with RAMPS

### ISSUE THREAD

**Issue by onekk** [grbl/grbl#561]
I have found some project on internet but they are not much in sync with GRBL, it was a pity not to use/support the widespread and cheap electronics from the reprap to use with CN.
I know that there are more project to use it but the fragmentation on efforts is the hell of the opensource project.

Regards

Carlo D. (onekk)

**Comment by EliteEng** [comment]
Please see my repo https://github.com/EliteEng/grbl master branch.

I have added the ability to have the step and direction pins on different port which will allow the use of the RAMPS board.

I have started adding the RAMPS board to the cpu_map.h but it still needs a bit of work to get all the pins in the correct location.

**Comment by onekk** [comment]
Many thanks for the reply, when I receive the boards and the machine (eShapeoko didn't answer me yet and didn't know when) I will try your solution. As the moderator told me this tread is becoming too long and tend to be off-topic there is another manner to comunicate?

Regards

Carlo D.
