### ISSUE TITLE
On updating grbl 0.8, i have seen this error , if it is.

### ISSUE THREAD

**Issue by cri-s** [grbl/grbl#563]
void gc_set_current_position(int32_t x, int32_t y, int32_t z)
{
  gc.position[X_AXIS] = x/settings.steps_per_mm[X_AXIS];
  gc.position[Y_AXIS] = y/settings.steps_per_mm[Y_AXIS];
  gc.position[Z_AXIS] = z/settings.steps_per_mm[Z_AXIS];
}

gc.position is float, mm presuming, and x/y/z is steps .

Theoreaof is should be 
  gc.position[X_AXIS] = x*settings.steps_per_mm[X_AXIS];
  gc.position[Y_AXIS] = y*settings.steps_per_mm[Y_AXIS];
  gc.position[Z_AXIS] = z*settings.steps_per_mm[Z_AXIS];

even if it makes no sense.
If hitting the limit switches usually means, that the cnc has lost his position or wrong code was
used. Whatever, the actual position should not be trusted and homing is required, if machine have homing. 
Annother reason for not using steps position to machine position is backlash compensation.
If doing backlash compensation, then the step position is basically wrong, because backlash was added.
The same code is present on the 0.9 release named gc_sync_position()

**Comment by chamnit** [comment]
@cri-s : You sure about that? steps/(steps/mm) = mm
