### ISSUE TITLE
Define accel on edge branch

### ISSUE THREAD

**Issue by metropt** [grbl/grbl#571]
How will be accel defined on the new version?

Thank you

**Comment by metropt** [comment]
It doesn't show on the options but it is possible to change.

**Comment by chamnit** [comment]
@metropt : Not sure what you mean by it doesn't show on options. It prints out fine when issuing a '$$' command.

**Comment by metropt** [comment]
that strange, on my system it jumps from $112 to $130 :s

**Comment by chamnit** [comment]
@metropt : That is strange. Try wiping your EEPROM with the Arduino IDE clear eeprom library. THere's instructions on the wiki on how to modify it to do it. (Note to self, add this to the Grbl source).

**Comment by chamnit** [comment]
@metropt : If that doesn't work, try reflashing the optiboot boot loader onto your board. I had a weird problem once, where nothing made sense. When I did reflashed boot loader, it worked fine. It happened when the firmware was getting close to about 30k, which is about the size of it with the CoreXY additions.

**Comment by metropt** [comment]
clear the eeprom doesn't seem to work. BTW I didn't flash the bootloader. I directly load the grbl.hex file using the avr programmer.
