### ISSUE TITLE
Spindle Speed In $G Report

### ISSUE THREAD

**Issue by jarretluft** [grbl/grbl#572]
Hey Sonny,
I noticed in the wiki for 0.9g you mention the $G report will return tool, spindle and feedrate.  however I'm not seeing a spindle speed in this report.  Is this a typo in the wiki? Or is there some specific condition (or compile-time build option) needed for the spindle speed to be reported here?
Thanks!

**Comment by chamnit** [comment]
@jarretluft : Yeah. I forgot it in the general release. It's in edge branch, but only shows if you have variable spindle speed enabled. I could set it to always display, but there isn't a reason to if it doesn't do anything. that's my thinking anyways.
