### ISSUE TITLE
VARIABLE SPINDLE stop working on 0.9h

### ISSUE THREAD

**Issue by GabeHC** [grbl/grbl#573]
update from 0.9g variable spindle function stop working, D11 stay 0V all time.
I am using UNO + CNC Shield, Is there something I miss?

**Comment by EliteEng** [comment]
@chamnit @GabeHC I can confirm it gets stuck at line 116 of spindle_control.c and does not enter spindle_set_state to set either the Spindle enable or direction pins.

I will have a look into it ( I need to get my head around the new states anyway )

**Comment by EliteEng** [comment]
@chamnit I believe it is an error with the logic.
Am I right that line 116 of spindle_control.c
```if (sys.state != STATE_CHECK_MODE) { return; }```
should be
```if (sys.state == STATE_CHECK_MODE) { return; }```

**Comment by chamnit** [comment]
@EliteEng : Nice catch Rob. Fixed and pushed update this morning.
