### ISSUE TITLE
stepper.c     st.step_count--

### ISSUE THREAD

**Issue by younew** [grbl/grbl#574]
(steppper.c   line404  )
" 
 st.step_count--; // Decrement step events count 
  if (st.step_count == 0) {
    // Segment is complete. Discard current segment and advance segment indexing.
    st.exec_segment = NULL;
    if ( ++segment_buffer_tail == SEGMENT_BUFFER_SIZE) { segment_buffer_tail = 0; }
  }
"----------------------------------
should be modified to:?????????????

if(st.step_count > 0){
  st.step_count--;
}
........
......

**Comment by chamnit** [comment]
@younew : Nope. Works fine as is.
