### ISSUE TITLE
Grbl misses coordinate when started

### ISSUE THREAD

**Issue by Erik46** [grbl/grbl#578]
I found an effect on my Grbl 0.9 when I start my machine from cold

If I start up my machine it does not take the 2nd coordinate (0,0,0 is the first coordinate) into consideration but travels to the 3rd coordinate at the first passage, it does travel correctly in the 2nd passage. 
After powering down for 5 minutes it performs flawlessly. After two days the first passage goes wrong.

I documented my findings in a post http://www.shapeoko.com/forum/viewtopic.php?f=3&t=5056

My guess is that the actual position is undefined when the machine is powered for the first time but I owe you a beer if you prove me wrong.

The effect can only be reproduced on a cold machine once, therefore difficult to find.

**Comment by chamnit** [comment]
Closing. Working on this issue at shapeoko.com forums.
