### ISSUE TITLE
Refuse unlock if reset pin still active (low)

### ISSUE THREAD

**Issue by natevw** [grbl/grbl#580]
Got Grbl working today, and quite excited! I had been using my new CNC 3040T ("YooCNC" controller) with Mach3 and an old PC but now I'll be able to use it over USB from laptop, and not have to leave any computer in the garage. Not to mention extending with a laser, etc. etc. ;-)

Anyway, one thing I noticed after rigging up the E-Stop button is that I am able to `$X` and reset even while the button is still latched down! (It requires a twist to pop it back out.)

So what this means is if I notice the tool heading towards a clamp or the Z-axis buzzing against its mechanics (still waiting for limit switches to arrive) or whatnot, I press the E-Stop and it works great. But then I might $X to reset, and go along just fine…until I need to reset it again. Now the button is probably still down because I forgot to twist it back out. Grbl lets me proceed without putting the button back, so now in my panic I can't just mash it down again!

Hopefully this would be an easy change, so that if I command $X but it detects that the `PIN_RESET` is still in activate state and refuses to unlock?

**Comment by chamnit** [comment]
@natevw : An e-stop switch should interrupt power, rather than control the reset pin. This ensures nothing happens as long as the e-stop switch is active.
