### ISSUE TITLE
question status report Buf

### ISSUE THREAD

**Issue by villamany** [grbl/grbl#582]
Hello, i'm creating a windows application for control my laser engraver. I am trying to mantain the 127 bytes rx buffer as high as possible as reccomended on wiki page. When i get the status report message i can only see Buf:0 and Buf:1 messages, Is this ok or it should be more high values?

**Comment by chamnit** [comment]
'Buf:' is the number of motions queued in grbl's planner. You are looking for 'RX:'. I think it's in the wiki pages, if not, I'll try to post what they are soon.

**Comment by villamany** [comment]
Yes i read it, but with full rx buffer the planner buffer should be also about full?

Also read as recomended trying to mantain the rx buffer full but also said for 0.9+ the reccomended is simple send and wait response one by one? Whatis the best way for smooth transitions on v0.9?
