### ISSUE TITLE
how to generate G2/G3 code from mc_arc call

### ISSUE THREAD

**Issue by cri-s** [grbl/grbl#601]
How to convert this back to G2/G3 code ?
void mc_arc(float *position, float *target, float *offset, uint8_t axis_0, uint8_t axis_1,
  uint8_t axis_linear, float feed_rate, uint8_t invert_feed_rate, float radius, uint8_t isclockwise)

Same for this
void mc_line(float x, float y, float z, float feed_rate, uint8_t invert_feed_rate)

Is there something special with invert_feed_rate , or just pass feed_rate and
pass G94 and G95 Gcode and that is ?

Reason for this question is that for some thing  from annother question, 
i have used the Gcode parser and made sceleton for gcode translator.
Actually it emits only code for dwell spindle_run coolant_run mc_line ,
but after that mc_line and mc_arc is fixed, it can be modified well.

**Comment by chamnit** [comment]
@cri-s : I suggest reading the linux cnc g-code descriptions. Grbl follows these very very closely.
