### ISSUE TITLE
Strange square

### ISSUE THREAD

**Issue by dorucazan** [grbl/grbl#603]
Hi,
I have used this test gcode to 'draw' a rectangle:
<i>
G21
F5
G90 G94 G54
M03
G01 X10 Y0 Z0
G01 X10 Y10 Z0
G01 X0 Y10 Z0
G01 X0 Y0 Z0
M05
</i>
After moving in XY plan for first and second sides, on the approximately 1/3 of 3rd side the tool started to descent (see attached picture). I am using Arduino Duemilanove with 328 processor and grbl 9. Is it something I did wrong?
Thanks a lot,
Doru Cazan

![sketch](https://cloud.githubusercontent.com/assets/3524861/6262912/4e15fbfa-b816-11e4-921f-a6a5fe1bad61.png)

settings:

Grbl 0.9g ['$' for help]
$0=10 (step pulse, usec)
$1=255 (step idle delay, msec)
$2=7 (step port invert mask:00000111)
$3=5 (dir port invert mask:00000101)
$4=1 (step enable invert, bool)
$5=0 (limit pins invert, bool)
$6=0 (probe pin invert, bool)
$10=15 (status report mask:00001111)
$11=0.020 (junction deviation, mm)
$12=0.002 (arc tolerance, mm)
$13=0 (report inches, bool)
$14=1 (auto start, bool)
$20=0 (soft limits, bool)
$21=0 (hard limits, bool)
$22=0 (homing cycle, bool)
$23=0 (homing dir invert mask:00000000)
$24=25.000 (homing feed, mm/min)
$25=500.000 (homing seek, mm/min)
$26=250 (homing debounce, msec)
$27=1.000 (homing pull-off, mm)
$100=200.000 (x, step/mm)
$101=200.000 (y, step/mm)
$102=200.000 (z, step/mm)
$110=700.000 (x max rate, mm/min)
$111=700.000 (y max rate, mm/min)
$112=700.000 (z max rate, mm/min)
$120=10.000 (x accel, mm/sec^2)
$121=10.000 (y accel, mm/sec^2)
$122=10.000 (z accel, mm/sec^2)
$130=241.000 (x max travel, mm)
$131=152.000 (y max travel, mm)
$132=102.000 (z max travel, mm)
ok

**Comment by chamnit** [comment]
@dorucazan : That seems strange. Is Grbl actually moving the machine like this or this is a problem with the GUI that you are using? GUI's sometimes use their own g-code parsers and it may not resemble what Grbl actually does. Secondly, try downloading the source from the edge branch, Grbl v0.9h. There was a critical bug fix for particular motions, but this isn't one of them. It doesn't hurt to try though,.

**Comment by dorucazan** [comment]
I will close this until testing new version. Thanks, Doru Cazan
