### ISSUE TITLE
Limit switch inversion wrong?

### ISSUE THREAD

**Issue by morres83** [grbl/grbl#605]
Hi,

maybe I am wrong, but in limits.c ISR function it is written:

 if (bit_istrue(settings.flags,BITFLAG_INVERT_LIMIT_PINS)) { bits ^= LIMIT_MASK; }

Shouldn't it be bit_isfalse instead, consindering the standard is an normally open switch which connects to GND?

Otherwise (bits & LIMIT_MASK) will be fulfilled due to the pull-up in normal operating state... The alarm will be issued as long as you don't touch all limit swiches exactly the same time (what I guess is impossible), but not due to the correct reason (the pull-ups are reason for the alarm). 

Regards,
morres83

**Comment by chamnit** [comment]
@morres83 : Yes, that should be bit_isfalse(). That part of the code, the software debounce routine for the hard limit pins, was going to be removed and hasn't been updated. I'll change it on the next push, just so that it's done.
