### ISSUE TITLE
grbl 9h - Arduino Duemilanove - spindle always on

### ISSUE THREAD

**Issue by dorucazan** [grbl/grbl#606]
Hi,

I have tested grbl edge version 9h on my Arduino Duemilanove. The spindle is always on. With master version 9g the spindle can be stop using M05 command.

Thanks,
Doru Cazan

**Comment by chamnit** [comment]
@dorucazan: Please check if VARIABLE SPINDLE is enabled in config.h. This will be the default going forward. This means the pins have changed according to the pin map in the Wiki.
