### ISSUE TITLE
Just 1 endstop pin

### ISSUE THREAD

**Issue by Snebajer1** [grbl/grbl#625]
On my machine, the three limit switches are wired together, so i can't tell, which endpoint is triggered.
Q1: Will this affect homing abilities ?
Q2: Di i just edit cpu_map.h defining all three endstops to the same pin, which would the be common to all three axis ?

Thanks !

**Comment by chamnit** [comment]
@Snebajer1 : Grbl was written to allow using just one limit pin on multiple axes, but I haven't tested it in a while. Theoretically, all you need to do is updated the cpu_map.h, as you already have, and then update the homing cycles in config.h to only home one axis at a time.

**Comment by Snebajer1** [comment]
Thanks !
Really quick response.
Den 15/03/2015 00.15 skrev "Sonny Jeon" <notifications@github.com>:

**Comment by Snebajer1** [comment]
Still works beatifully !
