### ISSUE TITLE
no text file ?

### ISSUE THREAD

**Issue by waricap** [grbl/grbl#627]
I followed the instructions
https://github.com/grbl/grbl/wiki/Compiling-Grbl
"4. Open the GrblUpload Arduino example.
Click the File down-down menu, navigate to Examples->Grbl, and select GrblUpload."

There is no code in the file. 
https://github.com/grbl/grbl/blob/master/grbl/examples/grblUpload/grblUpload.ino
Where is the correct file (with code)?
Thanks!

**Comment by chamnit** [comment]
There should only be one include. No code.

**Comment by waricap** [comment]
Sketch  grblUpload.ino shows error during compilation because there is no code. 
What should I do next?

**Comment by waricap** [comment]
instruction
5. Compile and upload Grbl to your Arduino.
Connect your Arduino Uno to your computer......

**Comment by chamnit** [comment]
@waricap : Make sure that you imported the grbl library correctly. You may have this problem if you select the entire repo folder (has a build and doc folder in it), rather than the 'Grbl' folder that contains only the source code.

**Comment by waricap** [comment]
https://github.com/grbl/grbl/blob/master/grbl/examples/grblUpload/grblUpload.ino

link this file ?
