### ISSUE TITLE
Download GRBL release

### ISSUE THREAD

**Issue by Scott216** [grbl/grbl#632]
Are the hex files for each release available or do we have to compile it ourselves with the Arduino IDE? It's a little confusing what release is the active one on gitbub; I think it would be nice if you used the release feature in github.  It's super easy to use, just click on the release link, add a new release, you can give it a version number (like 0.9g) and a description.

**Comment by chamnit** [comment]
@Scott216 : I've been ask to do that before, but github releases came about only two years ago. I may eventually start using them, but for now, releases are ONLY what you see on the front page. This keeps it really clear what's stable. HEX links are available on the front page for the stable build, if you need a HEX, but you can compile it yourself very easily with the new Artduino IDE methodology written in the wiki.
