### ISSUE TITLE
About spindle control.

### ISSUE THREAD

**Issue by Dikabro** [grbl/grbl#636]
Hello. I'm making laser engraver cnc (with only two axes X and Y) and wanted to ask - how I could disable Z axis and make on Digital Pin 12 Spindle enable / disable function and on Digital Pin 11 variable (PWM) spindle control?

**Comment by chamnit** [comment]
@Dikabro : There isn't a way to do it now, but you could hack the spindle control.c source code to do what you want. I'm mulling a compile option to use the digital pin D13 as spindle enable disable and get rid of the spindle direction.

**Comment by Dikabro** [comment]
Could you help me with this?

**Comment by cri-s** [comment]
You could define z dir and step bit as 8 and use the unused z dir and step
output as any other output pin.

Il mercoledì 25 marzo 2015, Dikabro <notifications@github.com> ha scritto:

**Comment by Dikabro** [comment]
@cri-s could you help me? I'm not a programmer, for me it's too difficult. Please I nees someones help.

**Comment by cri-s** [comment]
contact me at otm254824@54.33mail.com

2015-03-25 21:57 GMT+01:00, Dikabro <notifications@github.com>:

**Comment by chamnit** [comment]
@Dikabro : I just finished writing up a compile option to have spindle speed PWM on pin D11 and spindle enable on pin D13 (instead of spindle direction). Spindle direction will be replaced if you enable this option and you'll lose the M4 spindle enable counter-clockwise command, since there is no direction pin. M3 spindle enable clockwise and M5 spindle disable will still work.

**Comment by Dikabro** [comment]
Ok. Thank you @chamnit!
I think it would be very useful for people who makes laser cnc. As I use laser I dont need to control any spindle direction. For me best option would be enable/disable spindle (laser) with D12 pin and control its PWM with D11 (as it was on 0,8c GRBL version). :)
When I will download your new compile option I will add there some codes from 0,8c version to control laser PWM instantly.

**Comment by Dikabro** [comment]
@chamnit how are things going? :)

**Comment by chamnit** [comment]
@Dikabro : The updates were posted last night to the master branch. Download the source and install through the Arduino IDE method. You'll need to alter the config.h file in the library directory where the Arduino IDE has copied the source code.
