### ISSUE TITLE
Spindle on causes hard/soft limit alarm

### ISSUE THREAD

**Issue by tkur** [grbl/grbl#648]
Hello,
I'm having an issue where my spindle causes a hard/soft limit alarm.  I have spindle control enabled, hard limits enabled, and soft limits disabled.  Seems that when my spindle starts rotating fast enough (via program control or manually turned up spindle speed) I get this alarm.  Has anyone else experienced something like this?

**Comment by chamnit** [comment]
@tkur : This a very common problem caused by electrical noise from your spindle. Solutions really depend on your setup and even home wiring. Many install low-pass RC circuits on the limit pins and some even have reported problems from the spindle and computer sharing the same surge protector. The Arduino is bare metal electronics and problems like this are pretty standard.

**Comment by jeferson-simoes** [comment]
I solved this problem in a machine with a spindle + VFD this way.

Ferrite everywhere. Endstop cable, Spindle cable, USB cable and all AC cables.
A low-pass RC circuit like Chamnit said.
Shielded twisted pair cables to endstop. It's hard to get this cable here, so I used shielded Lan cable.
I used a resistor about 300 ohm. Anyone know what is the ideal value? I hadn't the 1komh that was told me to use:
![end-stop-emi](https://cloud.githubusercontent.com/assets/11801991/6995195/c87deee0-db0f-11e4-8285-3d351fc0c785.png)

**Comment by tkur** [comment]
Perfect! Low pass did the trick.  Thank you.

**Comment by himijendrix24** [comment]
That didn't solve the problem for me. Eventually I used an optocoupler (LTV847) on the limit switches 
and (very important!) a diode + capacitor across the motor. That really stopped an alarm being triggered, when the spindle was turned off.

Here is the wiring. The switch cables don't need to be shielded now. 
Just Make sure that the cables from the optocoupler to the GRBL CNC shield don't run with the servo/motor cables or use a shielded cable there.

![limit_wiring](https://user-images.githubusercontent.com/8920593/35182573-f9860da4-fdd7-11e7-9495-9cbee39df82d.PNG)

**Comment by jahnj0584** [comment]
Is your machine frame grounded, and to the right location?

**Comment by himijendrix24** [comment]
No, didn't do that because of the low voltage. The body of my spindle is also not grounded.
Maybe i will do it when using the z-probe.

**Comment by jahnj0584** [comment]
A spindle is 110+V. Not low. You must ground the frame directly to the spindle powers ground (wall) to properly eliminate all the noise. You're machine is just a giant EMI antennae now.

**Comment by himijendrix24** [comment]
Yes, some use +110V, mine is using +12V (mini cnc from china). Yes, that makes sense the spindle case should be grounded.
