### ISSUE TITLE
New GRBL Front-End SerialComCNC

### ISSUE THREAD

**Issue by UlrichAM** [grbl/grbl#657]
Hi there,
I like to introduce my freeware GRBL front-end for Windows "SerialComCNC".
If you are interested you will find more information here:
http://www.serialcominstruments.com/cnc.php

A short video about new comming features (EasyJob):
https://www.youtube.com/watch?v=PAm-B0i21cY 

For the newest downloads look at the bottom of following thread:
http://www.mikrocontroller.net/topic/345380#new

![bild09 website](https://cloud.githubusercontent.com/assets/11962409/7160046/ec2aa174-e386-11e4-8870-ea97b55f5e7d.jpg)

The software itself provides english and german language panel, but the description and help file are still in german only. This will be changed in future.

Greetings
Ulrich Albert M.

**Comment by cri-s** [comment]
It is possible that you release linux version too, or as alternative
optionally allows disabling video camera, because this is presumibly
the reason it don't work under wine.

2015-04-15 15:50 GMT+02:00, UlrichAM <notifications@github.com>:

**Comment by Scott216** [comment]
That looks really nice, I can't wait to try it.

**Comment by UlrichAM** [comment]
@cri-s 
The software is built with Delphi/Pascal. Linux version is not possible. The video interface is always disabled before explicit starting it. I doubt that the software will run under Wine, some people tried it but were not successfull establishing ComConnection.

**Comment by csdexter** [comment]
@UlrichAM said:
  > The software is built with Delphi/Pascal. Linux version is not possible. (...)

On the contrary :-) Lazarus (powered by FPC) can compile Delphi (Object Pascal) code just fine and if you really try, you can dust off a copy of Kylix (Borland's former "Delphi for Linux") and re-compile.

Nothing is impossible, unless you make up your mind that way.

**Comment by UlrichAM** [comment]
@csdexter 
I am sorry to say that I am using some quite expensive Components not available for Lazarus / Kylix. So no way for a Linux version of SerialComCNC.

**Comment by UlrichAM** [comment]
A new version 0.9d is out today. Software download at the bottom of following thread:
http://www.mikrocontroller.net/topic/345380#new

**Comment by UlrichAM** [comment]
Newest versionSerialComCNC 0.9f is available.
Enhanced video functions:
Estimate drill points with the cross of the video (WebCam). All drill points will be converted to a g-code list. The list is then transfered to the main window for direct use.
The software is in english and German language. You will find a download link here:
http://www.serialcominstruments.com/cnc.php
![videodrillpoints1](https://cloud.githubusercontent.com/assets/11962409/10286964/df58a0b2-6b90-11e5-830f-a995d6a9a549.png)
![videodrillpoints2](https://cloud.githubusercontent.com/assets/11962409/10286965/e12ea38c-6b90-11e5-92e1-0edd2f95abc4.png)
![img_5923a](https://cloud.githubusercontent.com/assets/11962409/10286972/eae2e62c-6b90-11e5-83e8-b365e39c6a32.jpg)
