### ISSUE TITLE
Z or L axis for control a pwm laser output.

### ISSUE THREAD

**Issue by campe89** [grbl/grbl#662]
Hi all,
someone wants to make a fork of the last version of grbl (with corexy support), changing the Z or L axis?
These axis control the pmw output from 0 to 255 for the laser intensity.
The gcode will be like this:
X98.04 Y16.68 Z151

Thanks!

**Comment by chamnit** [comment]
@campe89 : This is next on my list of things to do. I'm wrapping up something now and should be able to start on it soon.

**Comment by campe89** [comment]
Great news! 
Maybe L command is better; some machine have also Z axis.

**Comment by chamnit** [comment]
@campe89 : It'll use the standard S spindle speed command and update the PWM as it executes the appropriate gcode block.
