### ISSUE TITLE
Z Limit pin conntected to ground when powered up

### ISSUE THREAD

**Issue by zentoolworks** [grbl/grbl#671]
I am having this wired issue. When arduino uno board gets powered up, pin 11 is connected to ground already, so z limit is not functioning (found that while test homing). Pin 9 and 10 are not behave the same way. I am using 0.9i, did I do anything wrong?

Thank you

Xin

**Comment by chamnit** [comment]
The z limit and spindle enable pins switched to support variable spindle speed. You can revert it back to the original pin layout with a define in config.h.
