### ISSUE TITLE
Response 'ok' at the beginning of a command G0, G1 ?

### ISSUE THREAD

**Issue by LETARTARE** [grbl/grbl#674]
hello,

In Wiki 0.9i  (Grbl Interface) :
*Grbl will then process the string, __execute__ it accordingly, 
and then __reply back__ with a response to tell you how it went.
These strings include sending Grbl: a G-code __block to execute__, ...*

Test with Vista Pro Pack 2, UGS 1.08, Arduino 328p with Grbl 0.9i ( march 29, 2015) :

With G2, G3 is received 'ok' at the **END** of motion, that's okay.
Example :
if X=Y=Z=0.0
G02 F1000 X0 Y0 Z-20 I0 J20

With G0, G1 is received 'ok' at the **BEGINNING** of motion, it does not match the wiki ?
Exemple :
if X=Y=Z=0.0
G1 F1000 X100

Could you give me an explanation ?

Kind Regards

**Comment by chamnit** [comment]
@LETARTARE : Grbl replies when it is ready to accept a new command. This is primarily due to the motion planner buffer being full. Arcs inject lots of line segments into it and will usually reply right before the motion is completed.
