### ISSUE TITLE
Metal contactor to check spindle tool position & feed hold deceleration

### ISSUE THREAD

**Issue by tchepperz** [grbl/grbl#676]
Hi
I'm working on a mill using a wood router and grbl. I'm trying to set up a way to get  Z coordinate when the router bit contacts a metal part positionned at a reference point.. Aim is to calibrate Z axis depending on bit size.
Problem is feed hold deceleration, I need Z axis stop moving as soon as contact is done.
Is there a kind of way to remove feed hold deceleration, or to minimize deceleration distance to 1mm max, without loose any step? I don't need much speed for this, I'll just run it once after mounting bit on router.
thanks !

**Comment by chamnit** [comment]
No there isn't, because Grbl is open-loop control. It has to decelerate to maintain position. You need to use the G38.x probing command to perform the touch off. You can control the feed rate at which it does the probe. The slower you go, the less overshoot when it detects the switch triggering.
