### ISSUE TITLE
Homing ($H) moves only z and y Axis to Limit Switch

### ISSUE THREAD

**Issue by thomasgieser** [grbl/grbl#679]
Homing ($H) moves only z and y Axis to Limit Switch(seek speed ). After y Limit Switch was found both (y and x) are doing Homing feed and the pull-off

**Comment by chamnit** [comment]
@thomasgieser : It's a bit hard to understand what the issue is. Could you be a bit more elaborate? Thanks.

**Comment by thomasgieser** [comment]
Hi, sorry... I try to explain:
The issue is that I send the homing command.
Then z moves as expected. Then only y seeks for the end switch. After it is found both, x and y are moving to the pull off position. (1mm in my setup)
This has the effect that x is traveling 1mm away every time I send $H.
Hope this explains the situation

**Comment by twforeman** [comment]
Sounds like your X switch is not working as expected. Is it wired correctly? It sounds like the X switch is wired to the normally closed terminals.

**Comment by thomasgieser** [comment]
I've already checked the funktion ( electrical )--> works
Btw
Sometimes it works without problems

**Comment by twforeman** [comment]
If it works sometimes and doesn't work other times then you probably have a loose connection somewhere. Double check all your connections and switches for function.

**Comment by thomasgieser** [comment]
Ok,
The switch is normally open. If it would be a loose connection it would travel "over" the switch but it is not starting to move

**Comment by chamnit** [comment]
@thomasgieser : Grbl will only behave like this if your Y-axis switch is low(closed) upon the beginning of the homing cycle. Please check your wiring and switch.

**Comment by thomasgieser** [comment]
No, it's not...
Could it be a problem with the cable length?

**Comment by chamnit** [comment]
@thomasgieser : Possibly. The most common problems like yours is caused by electrical interference, like an unshielded cable or improperly buffered signal (low-pass filter). Please do a process of elimination test on your setup. Start by removing as much as you can from your Arduino, especially the limit switches. Operate them by a simple jumper wire connected to ground. You should see everything working properly.
