### ISSUE TITLE
Where the drive motor running program

### ISSUE THREAD

**Issue by blunsmith** [grbl/grbl#685]
Cursory read program and did not find a program to control the motor running the place, only to find in the stepper.c

   #ifdef STEP_PULSE_DELAY
     st.step_bits = (STEP_PORT & ~ STEP_MASK) | st.step_outbits;
   #else // Normal operation
     STEP_PORT = (STEP_PORT & ~ STEP_MASK) | st.step_outbits;
   #endif

Just called here STEP_PORT can achieve the role of control several motors yet? I want to learn to control the motor according to body details.
Please help me!

**Comment by chamnit** [comment]
All of the stepper execution is done in stepper.c. All of the source code is well commented. I suggest starting at main.c and go from there.
