### ISSUE TITLE
grbl v.9 config wiki on setting up spindle min max

### ISSUE THREAD

**Issue by tklus** [grbl/grbl#687]
I don't see any info on setting up the spindle min max rpm and enableing the spindle to use the PWM. I have been searching high and low and can't find info on it.

**Comment by Scott216** [comment]
Go here:
https://github.com/grbl/grbl/blob/master/grbl/config.h#L252

**Comment by tklus** [comment]
Thank you
 
Date: Fri, 8 May 2015 09:31:53 -0700
