### ISSUE TITLE
 grblUpload.ino:27:18: fatal error: grbl.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by Dmawzx** [grbl/grbl#688]
Arduino: 1.6.1 (Windows 7), Плата"Arduino Uno"

grblUpload.ino:27:18: fatal error: grbl.h: No such file or directory

compilation terminated.

Ошибка компиляции.

**Comment by chamnit** [comment]
@Dmawzx : When you import Grbl, make sure you select only the `grbl` folder inside the downloaded one. It only contains the source files.

**Comment by Dmawzx** [comment]
Thank you!
