### ISSUE TITLE
Can change the speed in motion？

### ISSUE THREAD

**Issue by younew** [grbl/grbl#691]
Can change the speed in motion

**Comment by 109JB** [comment]
When you say speed are you referring to spindle speed or Axis feed rate? In either case you are talking about feed override, or spindle speed override, Neither of which are currently supported in GRBL V0.9.

From the GRBL WIKI describing the planned updates for V1.0:

Overrides: Real-time adjustment of the feedrates, spindle speed, and coolant during a cycle. We've solved it and just need to figure out some small details before installing it.

**Comment by younew** [comment]
I want change Axis feed rate.look like :
![Uploading speed.png…]()
