### ISSUE TITLE
Homing fail after 0.9i upgrade

### ISSUE THREAD

**Issue by Scott216** [grbl/grbl#693]
I just upgraded from 0.9g to 0.9i.  I installed 0.9i via the Arduino IDE.  It uploads fine and I can jog around, but when I try to home it doesn't move and I get an error:  In config.h I commented out 
#define VARIABLE_SPINDLE.

Here's the output from terminal
```
$N
$N0=G90G20G54G17
$N1=
ok
$H
ALARM: Homing fail
ok
Grbl 0.9i ['$' for help]
['$H'|'$X' to unlock]
```

I posted my config settings here: http://pastebin.com/TNvDHpnc

**Comment by chamnit** [comment]
Your z max travel is zero. This value needs to be greater than zero and close to actual travel.

**Comment by Scott216** [comment]
That was easy, thanks.
