### ISSUE TITLE
Spindle doesn't work

### ISSUE THREAD

**Issue by MichielD99** [grbl/grbl#707]
I updated my self-made laser engraver with the latest version of grbl v0.9i and now my laser (pin 12) doesn't want to be turned on and off.
Can I do something about that?

**Comment by chamnit** [comment]
It's been switched to pin 11. Z limit is now on pin 12.

**Comment by MichielD99** [comment]
On pin 11, it doesn't work either.

**Comment by chamnit** [comment]
Variable spindle is default enabled. Pin 11 works with a PWM based on spindle speed S. IF you want to revert it to just on/off on pin12, disable VARIABLE_SPINDLE in the config,h, compile, and flash.

**Comment by MichielD99** [comment]
sorry, but i don't find where I can disable VARIABLE_SPINDLE in the config.h.

**Comment by chamnit** [comment]
Line 238 of config.h
