### ISSUE TITLE
PWM Spindle S command range

### ISSUE THREAD

**Issue by Protoneer** [grbl/grbl#714]
I am trying to use the PWM spindle control feature with a laser diode. 

What I have tested:
* M3/M4 turns it on
* M5 turns it off
* S?? sets the PWM.

Is there some kind of range for the S command?

If I have the range I will be able to translate it to a percentage that works easier a laser.

(Thanks)

**Comment by chamnit** [comment]
Look at the config.h file. Range is set there.
