### ISSUE TITLE
M30 issue

### ISSUE THREAD

**Issue by Jibeji** [grbl/grbl#720]
Hi,
Everything works fine with Grbl 0.9i, except the M30 command.
Grbl answers OK but looks frozen after a M30 is sent, the spindle is still running and the job is not considered as done:

>>> G0X0.0000Y0.0000
>>> M30
ok
ok
ok
ok
ok
ok
ok

**Comment by chamnit** [comment]
Update to the current v0.9i build. This problem has been fixed.
