### ISSUE TITLE
Status report mask $10 (last 0.9i)

### ISSUE THREAD

**Issue by LETARTARE** [grbl/grbl#722]
in file 'config.h' some directives used to change the 'status report'
- #define USE_LINE_NUMBERS
- #define REPORT_REALTIME_RATE
- #define REPORT_CONTROL_PIN_STATE

It would be useful to group them in the variable '$ 10 status report mask'
What do you think?

**Comment by chamnit** [comment]
Not at the moment. Right now is like to keep them out for flash and overhead reasons.
