### ISSUE TITLE
Location of code to plan move in XYZ space ?

### ISSUE THREAD

**Issue by maaadbob** [grbl/grbl#730]
Hi all,

Have 4th axis running just fine on my machine (circular), but can only operate three axis at a time.
So can move XYZ or XYC or YZC etc.
Can someone point me to the code section that handles the cartesian planning.

Cheers,
Bob.

**Comment by chamnit** [comment]
@maaadbob : Grbl doesn't support 4th axis. Planning is done in the planner code.

**Comment by maaadbob** [comment]
You mean to write, GRBL doesn't support concurrent motion on four axis ?
It can support a 4th axis as my machine is running with a 4th.  :)

Br,
Bob.

On 09/06/2015 15:18, Sonny Jeon wrote:
> @maaadbob <https://github.com/maaadbob> : Grbl doesn't support 4th axis. Planning is done
> in the planner code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grbl/grbl/issues/730#issuecomment-110371374>.
>

-- 

Southern Assemblies Ltd
Mob: +447758256558
Email: info@southern-assemblies.co.uk
G+: https://plus.google.com/113190327999615741877
Twitter: @SA__Ltd
Registered in England and Wales: 08149202
VAT registration No. GB183 8073 87

**Comment by chamnit** [comment]
@maaadbob : No. I meant that Grbl doesn't support 4th axis. Never has officially. Other forks/users have add this. It will soon though.

**Comment by mkeyno** [comment]
@maaadbob  what if we use the X axis for A axis to simulate X&Y planar to A&Y cylindrical space

**Comment by brakthehun** [comment]
How soon will this be supported. I just need XY and C axis. The "Spindle" pin will run then plunge knife solenoid.
I'd like C to be automatically calculated so I just have to give it XY coordinates and it point the knife the right direction.
