### ISSUE TITLE
Bad number format with #5063 variable

### ISSUE THREAD

**Issue by Jibeji** [grbl/grbl#731]
Hi,
I'am trying to automatize the Z-probe procedure with 0.9i:
G21
G91 G38.2 F50 Z-45
G90 G0 Z[#5063+0.5]
G91 G38.2 F10 Z-1
G92 Z[#5063]

But I got the following error:
>>> G90 G0 Z[#5063+0.5]
error: Bad number format

**Comment by chamnit** [comment]
Grbl doesn't support macros, variables, or subroutines.
