### ISSUE TITLE
How to count steps/mm

### ISSUE THREAD

**Issue by Lexander24** [grbl/grbl#749]
Hello all, i'm new in using GrBl Firmware. 
I downlaod and try Grbl v0.9i

i confused how to set up the steps/mm, can you give me example?
motor 1
1,8" 200 Steps/revolution
motor driver TB660T1 (1/16)

i just know, 1 revolution can move my position 55mm. i dont understand how to use this http://prusaprinters.org/calculator/ 

an one can help me?

**Comment by 109JB** [comment]
since you have a 200 step/rev motor and are set to 1/16 microstepping you have 200*16 = 3200 step counts per rev. Then 3200 / 55 = 58.1818 steps/mm.

**Comment by Lexander24** [comment]
Thank you
