### ISSUE TITLE
Losing of steps

### ISSUE THREAD

**Issue by JSalda** [grbl/grbl#753]
I have a small machine that sometimes losses steps. I found problem and demonstrate it in video (45th second).

http://youtu.be/QKoBGNVYRNA

I set very small acceleration for demonstration. Problem is at 45th second. X axis is quickly stopped but max. acceleration is only 0.1 mm/s2!

G Code: (Initial position is X=0 Y=0)
G90
G21
G17
F100

G0 X100
G0 Y100
M2

Parameters:

$0=10 (step pulse, usec)
$1=255 (step idle delay, msec)
$2=0 (step port invert mask:00000000)
$3=0 (dir port invert mask:00000000)
$4=0 (step enable invert, bool)
$5=0 (limit pins invert, bool)
$6=0 (probe pin invert, bool)
$10=3 (status report mask:00000011)
$11=3000.000 (junction deviation, mm)
$12=0.002 (arc tolerance, mm)
$13=0 (report inches, bool)
$20=0 (soft limits, bool)
$21=0 (hard limits, bool)
$22=0 (homing cycle, bool)
$23=0 (homing dir invert mask:00000000)
$24=25.000 (homing feed, mm/min)
$25=50.000 (homing seek, mm/min)
$26=50 (homing debounce, msec)
$27=50.000 (homing pull-off, mm)
$100=1066.667 (x, step/mm)
$101=1066.667 (y, step/mm)
$102=1066.667 (z, step/mm)
$110=1680.000 (x max rate, mm/min)
$111=1680.000 (y max rate, mm/min)
$112=1680.000 (z max rate, mm/min)
$120=0.100 (x accel, mm/sec^2)
$121=0.100 (y accel, mm/sec^2)
$122=0.100 (z accel, mm/sec^2)
$130=200.000 (x max travel, mm)
$131=200.000 (y max travel, mm)
$132=200.000 (z max travel, mm)

Build: [0.9i.20150620:]

Where is problem?

Thanks a lot.

**Comment by chamnit** [comment]
@JSalda : Your junction deviation setting is way too high. It should be about 0.02 or 0.01mm.
