### ISSUE TITLE
About Real-time adjustable feedrates

### ISSUE THREAD

**Issue by lilo003** [grbl/grbl#754]
I'm reading in Development Path and Future Needs (https://github.com/grbl/grbl/wiki/Development-Path-and-Future-Needs). The implementation Has Been solved at this point, but just needs to be installed and bugs to be worked in October

How can I test this version?

**Comment by chamnit** [comment]
I'll announce a test version when it's ready to be released for testing.

**Comment by lilo003** [comment]
hi @chamnit!

please, some information about Real-time adjustable feed rates?

**Comment by chamnit** [comment]
@lilo003 : It will be out very soon! I had a very busy last few months with my day job. I'm finally in the clear as of today.

**Comment by lilo003** [comment]
ok, I'm waiting. 

thank you

**Comment by lilo003** [comment]
@chamnit, good Morning.

Excuse me again the question, but how is the Real-time adjustable feedrates development?

I am wondering why in Brazil our company developed an interface to control GRBL made to run in the cloud.

And I believe that your firmware is the right choice!

Thank you

**Comment by lilo003** [comment]
If you are interested in knowing, be happy.

The link is https://chrome.google.com/webstore/detail/c37-controlador/iodomfcbclgacbhdjmpjfcgdjecdkdhn

And we are preparing to improve the errors that are finding, however, it is already functional

Thank you

**Comment by chamnit** [comment]
@lilo003 : Feed and rapids overrides are complete and are working great. But I will not be releasing the source code publicly until I'm closer to a full release. There are multiple reason for this that I won't get into.
