### ISSUE TITLE
Moving PIN assignments and compatibility?

### ISSUE THREAD

**Issue by chamnit** [grbl/grbl#77]
I'd like to see if anyone needs to have the PIN re-assigned in any particular way to accommodate hardware/shields better., since a lot of them use the higher number digital pins for SD cards or a 4th axis. As far as I understand, most people need to have the Arduino's first 9 digital pins set in the same place (0-8) for serial comm, stepper pulse, direction, and enable. Right now, the higher pins (9-13) have been allocated for spindle and limits/homing.

There has been some discussion on another issue thread about moving the pins to analog side. Namely the spindle and limit pins, and reducing the limit pins down to one pin rather than one for each axis. We would also add pin outs for the runtime commands for people that want to have physical buttons for feed hold, cycle start (aka resume), and abort. 

For example, here's a proposed pin layout.

```
D0: RX Serial (Same)
D1: TX Serial (Same)
D2: X Step (Same)
D3: Y Step (Same)
D4: Z Step (Same)
D5: X Dir (Same)
D6: Y Dir (Same)
D7: Z Dir (Same)
D8: Stepper Enable (Same)
D9: A Step (New. Reserved for 4th axis)
D10: A Dir (New. Reserved for 4th axis)
D11: (Reserved for users/shields?)
D12: (Reserved for users/shields?)
D13: (Reserved for users/shields?)

A0: Cycle Start (New)
A1: Feed Hold (New)
A2: Abort (New)
A3: Limit/Homing (Condensed to One Pin)
A4: Spindle Enable (Moved)
A5: Spindle Dir (Moved)
```

Here's another proposal with adding jogging pin outs.:

```
D0: RX Serial (Same)
D1: TX Serial (Same)
D2: X Step (Same)
D3: Y Step (Same)
D4: Z Step (Same)
D5: X Dir (Same)
D6: Y Dir (Same)
D7: Z Dir (Same)
D8: Stepper Enable (Same)
D9: A Step (New. Reserved for 4th axis)
D10: A Dir (New. Reserved for 4th axis)
D11: Limit/Homing (Condensed to one pin)
D12: Spindle Enable (Same)
D13: Spindle Dir (Same)

A0: Cycle Start (New)
A1: Feed Hold (New)
A2: Abort (New)
A3: Jogging Toggle?
A4: Jogging Dir?
A5: (Misc user command?)
```

**Comment by MarqueIV** [comment]
Not sure if this is still active, but I'd love to see/play with an example of a port expander used with this. Trying to add some extra functionality to my GRBL setup: SD card, display, jog/shuttle dial, axes selection, etc.
