### ISSUE TITLE
Status Reporting & Advanced Character-Counting

### ISSUE THREAD

**Issue by rfcaldas** [grbl/grbl#774]
Hi!

First of all, I would like to show my appreciation for this outstanding work. Grbl is great!

I'm trying to build a CNC with a custom GUI and I'm encounter a "problem" communicating with arduino.

The advanced character counting it's a realy clever way to keep the comunications running, but the status report interferes with it.
In my understanding, as soon the '?' character is send to arduino, is removed from buffer and executed. That's ok, but the arduino also reply a 'ok' message, and that 'ok' message is being used to subtract the count from the oldest code sent. So, my questions are:

The 'ok' message right after the status message always belongs to the status report, or in some pure chance cases, the ok could be a ok from the code being processed?

Is there any way of disabling the 'ok' message from the '?' command? (easiest solution)

Thank you for your time and effort.

If you want to see my DIY cnc visit https://instagram.com/explore/tags/suziecnc/

**Comment by chamnit** [comment]
There is no 'ok' with any realtime command like the '?' status report.  'Ok's are only for normal commands. There is no problem here.
