### ISSUE TITLE
End of Line Confusion

### ISSUE THREAD

**Issue by AlexHolden** [grbl/grbl#780]
Grbl always sends DOS-style two-character EOL sequences (i.e. '\r\n') in its replies, however it seems to expect to receive a single character EOL at the end of each command (either '\r' or '\n' alone will work). If you send it a command that ends with '\r\n' it interprets the '\n' as a blank line and replies with an extra 'ok'. Is that what's supposed to happen?

**Comment by JohnKnit** [comment]
I can't tell if its supposed to happen, but can confirm it does. Maybe that is something to add in the wiki as it only says there grbl answers with 'ok' to every successfully completed line.

**Comment by chamnit** [comment]
@AlexHolden : Yes. It's supposed to happen this way. Changing it will likely break a lot of GUIs, as they all expect this behavior.
