### ISSUE TITLE
grbl 4 axis Arduino UNO (not really an issue)

### ISSUE THREAD

**Issue by nomadsoul68** [grbl/grbl#809]
Hello,
Grbl is great for cnc machine but now i have a 3d printer. I want to keep grbl because it run fine.
I would like to add an axis on pin 8  and 9 ( not use for my machine). I have try to understand the source code and succeed to implement a new axis. I have a problem to put the new Gcode (E for my axis) in grbl: like G1 E40 F100. E is not understood but set it in grbl.

I am allowed to post my  code part directly here to help me?

Thanks

**Comment by chamnit** [comment]
It's best to create your own fork of grbl and make code changes there. Let us know of any major developments.
