### ISSUE TITLE
Any thoughts on how servo pwm will be implemented

### ISSUE THREAD

**Issue by goopyplastic** [grbl/grbl#825]
I am curious if you have thought about how the spindle direction pin will behave when servo pwm support is added.

Will M3 SXXX set spindle direction pin low?
Will M4 SXXX set spindle direction pin high?
Will M5 alter spindle direction pin value?

Will USE_SPINDLE_DIR_AS_ENABLE_PIN be default?
if so will INVERT_SPINDLE_ENABLE_PIN work?

I am making a shield that has a mosfet connected to D13 so that you can enable / disable power to the hobby sero (to prevent jittering).

**Comment by chamnit** [comment]
Grbl on the Uno will not support servos. But it may at a later point in time on a different processor.
