### ISSUE TITLE
hex files

### ISSUE THREAD

**Issue by rolfee** [grbl/grbl#848]
hello i am new to grbl and am trying to update to the latest version and cant find the hex files to download your help would be appreciated

**Comment by Protoneer** [comment]
Very easy!!! Its on the main Github page.... under the "Master Branch" heading.
[This is the latest HEX](http://bit.ly/1I8Ey4S)

**Comment by sascha35** [comment]
Search for Arduino Mega 2560 grbl 0.9f with latest update

**Comment by sascha35** [comment]
Sorry Search grbl 0.9j

**Comment by sascha35** [comment]
other grbl 1.0 Arduino mega 2560

**Comment by chamnit** [comment]
@sascha35 is incorrect. No search necessary.

Please just go to Grbl's Github front page for a link to a pre-compiled hex file, but I recommend downloading and compiling Grbl instead. Go to the Grbl wiki (link on front page) and read the compiling grbl page on how to do it through the Arduino IDE. It's very easy.
