### ISSUE TITLE
MEGA2560 and pin 'Hold'

### ISSUE THREAD

**Issue by LETARTARE** [grbl/grbl#850]
With svn1829 and Mega2560  :
1- config.h ->  "#define ENABLE_SAFETY_DOOR_INPUT_PIN" ,
2- pin 'Hold' (A9) is different from 'Door' (A11),
So pin 'Hold' no longer works, you must use 'Door'.

We must change 'Door' -> (A9) to have the same behavior as the UNO.

**Comment by chamnit** [comment]
@LETARTARE : Thanks, but the Mega2560 is not officially supported. That said, on the Mega, the intent is to have separate DOOR and HOLD pins, and it won't operate like the Uno.
