### ISSUE TITLE
Touch plate error.

### ISSUE THREAD

**Issue by candelo** [grbl/grbl#851]
Hi, 
I have an error using GRBL0.9j touch plate function. It´s only go down Z axis 2.978mm always. I have not connected probe pin, the probe pin have 5V.﻿

**Comment by candelo** [comment]
why did you close my issue?

**Comment by chamnit** [comment]
This was double posted.

**Comment by candelo** [comment]
Could you please give me the first post?
Thanks.

On Wed, Nov 18, 2015 at 10:36 AM, Sonny Jeon <notifications@github.com>
wrote:

> This was double posted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grbl/grbl/issues/851#issuecomment-157751132>.
>



-- 
______________________________________________________________________
Por favor, no me envíe documentos adjuntos en formato Word o PowerPoint.
Lea http://www.gnu.org/philosophy/no-word-attachments.es.html
