### ISSUE TITLE
How multiple G0 are handeled ? (Not Issue)

### ISSUE THREAD

**Issue by ledahu** [grbl/grbl#853]
G0 are using MaxSpeed 

Does it mean G0 cant receive a Fxxxx Parameters ? 

Does it mean that a generic Fxxxx command is the parameter for G0 or does G0 use the GRBL accel/speed param ? 

Consecutiv G0 seems to be proceeded as  one by one : G0(Accelerate -> Desselerate)-> G0 (Accelerate -> Desselerate) . 

Thank you for your answer

**Comment by chamnit** [comment]
G0 is always a rapid motion at max speed based on direction and axes limits. Grbl will not decelerate as long it has another motion after it and doesn't have to slow down into a change of direction
