### ISSUE TITLE
Z Home Zero

### ISSUE THREAD

**Issue by tompropst** [grbl/grbl#854]
I need the Z home position to be a value of zero. When the homing cycle completes, the z-value is the negative of my max z travel value (z = -1500.000 for example).  My homing switch is in the low direction so I have the z homing direction inverted ($23=4).

This issue began after an update from build 0.9j.20150717 to build 0.9j.20150930.  I reverted back to 0.9j.20150717 and the behavior remains.  It is possible I originally had a slightly different commit.

I'm not concerned about variations between builds (unless they are unexpected) but mainly just want to know how to get a zero position at my home position.

Thank you.

**Comment by chamnit** [comment]
@tompropst : Grbl's default origin after a homing cycle is to set everything into the negative machine space. So depending on where the limit switch is, the machine position may show a position around -max travel for some axes. This is traditional CNC operation and Grbl has always been this way. Not sure why you didn't run into this problem before.

That said, Grbl does have an option to force the machine origin to wherever the homing cycle finishes no matter how a user sets up their limit switches. To enable this, simply uncomment the HOMING_FORCE_ORIGIN line in config.h. Recompile and flash.
