### ISSUE TITLE
probing: probable bug / risk: type mismatch in memcpy

### ISSUE THREAD

**Issue by MoonCactus** [grbl/grbl#855]
By chance the bug is harmless for now, ... as long as sizeof(float)=sizeof(int32_t). But a change in types would provoke it.

in mc_probe_cycle() in motion_control.c, line ~312
```C
    if (is_no_error) { memcpy(sys.probe_position, sys.position, sizeof(float)*N_AXIS); }
```
should probably be written
```C
    if (is_no_error) { memcpy(sys.probe_position, sys.position, sizeof(sys.position)); }
```
It would certainly be much safer to use sizeof(position) in the first place, as the types do mismatch (position is a int32_t, NOT a float!)
Note: I did not check elsewhere but it can probably be assumed there are other occurrences of this risky practice (imho).

(sorry for not forking all of it just to submit a pull request -- it is just too time consuming for such a small fix).

**Comment by chamnit** [comment]
@MoonCactus : Thanks! I recently found this minor bug upstream and fixed it there. I'll apply it downstream in the master branch later this week.
