### ISSUE TITLE
preprocessor abstraction implementing more axes without annoing #ifdef

### ISSUE THREAD

**Issue by cri-s** [grbl/grbl#857]
Hi, i have used the latest master and made some preprocessor abstractions.
Now is possible to add more axis, just by defining
  #define DEFAULT_AXIS  X,Y,Z,U,V,W
inside the default.h file/folder. 
This is done using some  preprocessing, some details below.
I need to add instrumentation and time the code, and actually it's untested in hw.
It's more usefull on mega2560, but at least 6 Axis are possible on 328p too.
Is such type of modification interesting to be included officially ?

 
I have used a grep of the things that i have changed using this preprocessing, the result is here.

gcode.c:	  MAP(check_letter,DEFAULT_AXIS);
nuts_bolts.h:enum { FOREACH(AXIS_ID, , _AXIS) };	// build X_AXIS constants
report.c:  const uint8_t axis[] = { FOREACH(AXIS_ID,AXIS_QUOTE_,) };
settings.c:	FOREACH(DEFAULT,settings.steps_per_mm,STEPS_PER_MM+FLT_EPSILON);
settings.c:	FOREACH(DEFAULT,settings.max_rate,MAX_RATE);
settings.c:	FOREACH(DEFAULT,settings.acceleration,ACCELERATION);
settings.c:	FOREACH(DEFAULT,settings.max_travel,MAX_TRAVEL);
settings.c:	FOREACH(AXIS) settings.steps_to_mm[idx]=1.0/settings.steps_per_mm[idx];
settings.c:	unsigned char axis[]={ FOREACH(AXIS_BIT, ,_STEP_BIT) };
settings.c:	unsigned char axis[]={ FOREACH(AXIS_BIT, ,_DIRECTION_BIT) };
settings.c:	unsigned char axis[]={ FOREACH(AXIS_BIT, ,_LIMIT_BIT) };
stepper.c:  uint32_t FOREACH(AXIS_ID,counter_,);
stepper.c:        FOREACH(AXIS_IDs, st.counter_, (=) ,) 
stepper.c:	FOREACH(AXIS) 
stepper.c:  MAP(calc_step,DEFAULT_AXIS);
stepper.c:  FOREACH(AXIS) {
stepper.c:	FOREACH(AXIS)
stepper.c:	FOREACH(AXIS)
system.c:   FOREACH(AXIS)

Example of definition are here:
#define FOREACH_AXIS_IDs(pre,sep,post)  CONCAT(MAP_,AXIS_N)(sep,map_PrePost,pre,post,DEFAULT_AXIS)
#define FOREACH_AXIS_ID(pre,post)       CONCAT(MAP_,AXIS_N)( (,) ,map_PrePost,pre,post,DEFAULT_AXIS)
#define FOREACH_AXIS_BIT(pre,post)      CONCAT(MAP_,AXIS_N)( (,) ,map_callBit,pre,post,DEFAULT_AXIS)

where MAP_ is basically defined as
#define MAP_(n,f,a,b,x...)      f(NTH(n,x),a,b)
 and NTH:
#define NTH_(n,x...)            CONCAT(NTH,n)(x,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
#define NTH(x...)               NTH_(x)
#define NTH0(DEFAULT_AXIS...)   CAR(DEFAULT_AXIS)
#define NTH1(DEFAULT_AXIS...)   CAR(CDR(DEFAULT_AXIS))
#define NTH2(DEFAULT_AXIS...)   CAR(CDR(CDR(DEFAULT_AXIS)))
#define NTH3(DEFAULT_AXIS...)   CAR(CDR(CDR(CDR(DEFAULT_AXIS))))
#define NTH4(DEFAULT_AXIS...)   CAR(CDR(CDR(CDR(CDR(DEFAULT_AXIS)))))
#define NTH5(DEFAULT_AXIS...)   CAR(CDR(CDR(CDR(CDR(CDR(DEFAULT_AXIS))))))
#define NTH6(DEFAULT_AXIS...)   CAR(CDR(CDR(CDR(CDR(CDR(CDR(DEFAULT_AXIS)))))))
#define NTH7(DEFAULT_AXIS...)   CAR(CDR(CDR(CDR(CDR(CDR(CDR(CDR(DEFAULT_AXIS))))))))
#define NTH8(DEFAULT_AXIS...)   CAR(CDR(CDR(CDR(CDR(CDR(CDR(CDR(CDR(DEFAULT_AXIS)))))))))
#define NTH9(DEFAULT_AXIS...)   CAR(CDR(CDR(CDR(CDR(CDR(CDR(CDR(CDR(CDR(DEFAULT_AXIS))))))))))

**Comment by chamnit** [comment]
@cri-s : Thanks for the abstraction note, but I personally don't find #ifdefs annoying. They usually clearly indicate out what code can be removed or involve that particular #define directly in the code. I have a general rule that macros should be as simple as possible. No recursion and such. I'm not arguing what's there now is optimal, but it's not as hard to read and decipher as these FOREACH and NTH defines you posted.
