### ISSUE TITLE
Grbl 0.9j auto-cycle start

### ISSUE THREAD

**Issue by skytravel** [grbl/grbl#866]
Hello. I would like to disabled auto cycle start in grbl v0.9j. In v0.8  it has been in setting $14. But i can not find it in this version. 
Please help me. 
Thak you. 
Martin

**Comment by chamnit** [comment]
@skytravel : Auto-cycle start is now part the standard operation of Grbl. It was redundant to allow auto-cycle start to be disabled since a GUI just needs to start or stop streaming to control this. Feed holds also do something similar.
