### ISSUE TITLE
Recommendation: tagging of offical versions

### ISSUE THREAD

**Issue by BjoernKellermann** [grbl/grbl#870]
Thanks first for your great work and the efforts you spend.

Might it be possible to use tags to identify versions of grbl?
I tagged on a clone the versions I dentified. It is a one minute job, pleease see the screenshot.

When starting tagging, I recommend usind semantic versioning: http://semver.org/
Which means 0.9.j becomes 0.9.10
The logic is:
The first digit names major release, which is _NOT_ compatible to the previos.
The second digit is a minor release, which is fullys compatible to the previous release / API, but may inlcude additonal features. I case of grbl addiontal G-codes...
The third and last digit are bug fices wihtout API cahnge.

I have noticed the "build_version", like 20150620.
You could create and tag officials builds with additional build_version and use for beta testing.
v0.9i 20150620 becomes 0.9.9.20150620
If that version passed all tests and becomes the official release, it gets a second tag: 0.9.9 (v0.9i).

With this common logic of build identifiers, tools can use the identifier to check compatibility and users can identify which software is within each build.

Very kind regards

BTW: You can use TravisCI to build the code within the cloud and and give feedback to GitHub and even push the successful build (hex-file) anywhere.

Bjoern

![grbl_tags](https://cloud.githubusercontent.com/assets/6324993/11964673/90e522d8-a8ef-11e5-8aee-621bccc1e2c8.PNG)

**Comment by chamnit** [comment]
@BjoernKellermann : Thanks for the comment. I'm aware of semantic versioning. In general, I don't want change how things are in any significant capacity until v1.0.
