### ISSUE TITLE
m7/m8/m9 listed wrong in config.h?

### ISSUE THREAD

**Issue by goopyplastic** [grbl/grbl#873]
config.h says:

// Enables a second coolant control pin via the mist coolant g-code command M7 on the Arduino Uno
// analog pin 5. Only use this option if you require a second coolant control pin.
// NOTE: The M8 flood coolant control pin on analog pin 4 will still be functional regardless.
// #define ENABLE_M7 // Disabled by default. Uncomment to enable.

However, M7 is working on Analog4 not 5, and M8 on Analog3 not 4

I think it should read:

// Enables a second coolant control pin via the mist coolant g-code command M7 on the Arduino Uno
// analog pin 4. Only use this option if you require a second coolant control pin.
// NOTE: The M8 flood coolant control pin on analog pin 3 will still be functional regardless.
// #define ENABLE_M7 // Disabled by default. Uncomment to enable.

**Comment by chamnit** [comment]
@goopyplastic : Thanks. I'll correct this typo in v1.0.
