### ISSUE TITLE
Stopping stepper

### ISSUE THREAD

**Issue by cri-s** [grbl/grbl#876]
If on Stop/Alarm whatever the stepper needs to stops, it should ramp down instead of only stopping
generating steps and idle for certain type. If there is considerable speed involved and the stepper
don't get ramped down, there can be two issues. Damage of driver if no external diodes are used,
and damage or at least bending of mechanic because of excess of kinetic energy.
This is only a issue at high speeds and bigger inertia. How it's doable to address this issue.
Example, the speed is 1mt/sec , weight is 1kg , step speed = 66.66khz at 16x microstepping and
  20.833 rounds per seconds and one step pulse is generated every 15 uS during cruise.
What is the best way to calc a table/planner/... that spin down the motors until cut-off speed
on the fastest way.

**Comment by chamnit** [comment]
@cri-s : True, but conversely, a stop/alarm should stop as quick as possible. If a user has set a very low acceleration, you can run into a situation where you will still crash your machine into something, as it can take several centimeters of travel to slow a machine down to a stop.

A better solution is to make this a configurable option to determine stop behavior. I'll think about it adding this, but it's not high priority.
