### ISSUE TITLE
Variable spindle speed

### ISSUE THREAD

**Issue by athulsnair** [grbl/grbl#877]
Hi,
  I need someone's help in setting up variable spindle in GRBL. I like to use this feature for controlling laser output.
Thanks

**Comment by asm7100** [comment]
How about M3 Sxxxx Where xxxx is a number.I use this to control my laser :-) CNC Shiel modyifyd to use 0.9j :-)

**Comment by athulsnair** [comment]
@asm7100 
thanks for the reply.
I already fixed it, changed #define MA from 1000 to 255 so I could get max laser for s255 command.

Which software are you using to generate gcode, for cutting and engraving?
Any recommendations?

**Comment by chamnit** [comment]
@athulsnair : Grbl will have a special laser mode in v1.0 so it doesn't have to pause between 'S' spindle speed changes. Out very soon.

**Comment by athulsnair** [comment]
@chamnit I couldn't finga software that generate proper gcode for grbl to use with laser, do you know any?

 I tried to generate g code using standard generators for CNC, but if I run my laser with that code,  (say gcode for a circle and then a rectangle), laser will be on when machine moves from circle to rectangle and making unnecessary cuts since spindle need not to be turned OFF during tool paths.

**Comment by schlotzz** [comment]
I'm using InkScape with the LaserEngraver plugin. A short description with links to InkScape and the plugin can be found on my github project page https://github.com/schlotzz/CoreBeam

**Comment by asm7100** [comment]
@athulsnair Hi sorry for the late replay
I Use f-engrave-151 For text and in a combine with https://github.com/vlachoudis/bCNC A nice program :-)

**Comment by prcdslnc13** [comment]
Hey Guys Im working on the same thing right now. Check out LaserWeb for your code generation and machine control software by Peter Van Der Walt : 
https://github.com/openhardwarecoza/LaserWeb

Are you controlling a diode or a Co2 laser?

**Comment by athulsnair** [comment]
@prcdslnc13 I already tried laserWeb to run the machine, but I couldn't generate gcode for DXF files using laserweb(are you having the same issue?). Seems like it's having several other  issues. I did engraving using LaserWeb by uploading a B/W png image.

I'm using a 60W CO2 laser.
