### ISSUE TITLE
Tangential A Axis

### ISSUE THREAD

**Issue by jackjameshoward** [grbl/grbl#878]
Does anyone know how hard it would be to add a forth A axis for use with a tangential knife. 
I wouldn't not need the spindle anymore so that should free up the pins I guess.

**Comment by cri-s** [comment]
https://github.com/openpnp/grbl


2016-01-07 12:38 GMT, jackjameshoward <notifications@github.com>:

**Comment by jackjameshoward** [comment]
I noticed that in the file nuts_bolts.h the following is commented out
// #define A_AXIS 3
Has there been some effort to incorporate an A axis before in the grbl branch.

**Comment by chamnit** [comment]
@jackjameshoward : Grbl will support fourth axis in v1.0. Coming out very soon.

**Comment by cri-s** [comment]
Why not more then 4 axis ?


2016-01-11 21:06 GMT+01:00, Sonny Jeon <notifications@github.com>:

**Comment by jackjameshoward** [comment]
@chamnit thanks for the response. Any chance of a heads up if the pin configuration is changing? I'm just about to buy a shield

**Comment by hilam8899** [comment]
The 4 axis  millI I have finished!Now I want to do  4th axis cutter.  how I do tangential for 4th axis?my 4th AXIS is C (banlance Z AXIS  ),Thank you!

**Comment by 109JB** [comment]
There are already some forks of Grbl that support 4 to 6 axes.

https://github.com/UncleRus/grbl-mega-clean-6-axis
https://github.com/LETARTARE/grblQ-Mega-4axes
https://github.com/dguerizec/grbl-Mega-4axis/tree/0046fa9d386b0c5fa219a0cede47b5c339ea9cc8
https://github.com/gcobos/grbl4axis (This one eliminates spindle and adds 4th axis E for 3D printing. Could work for OP's application)
