### ISSUE TITLE
Stuck with CoreXY setup

### ISSUE THREAD

**Issue by nccwarp9** [grbl/grbl#879]
Hello, 

I tryng to build a corexy machine (without z). Went over the code and enabled ifdef COREXY and changed homing as described in commented sections of code. But when I try to run it is still works like Cartesian setup. Im using universal gcode sender for testing. 

any ideas what I missed to check ?

**Comment by cri-s** [comment]
Probably you must enable homing on xy for homingcycle2.
If you da homing on z for first cycle.
Il 07/gen/2016 19:22 "nccwarp9" <notifications@github.com> ha scritto:

**Comment by nccwarp9** [comment]
config.h file is setup as

#define HOMING_CYCLE_0 (1<<X_AXIS) 
#define HOMING_CYCLE_1 (1<<Y_AXIS)

#define HOMING_CYCLE_2                         // OPTIONAL: Uncomment and add axes mask to enable

still no joy.

**Comment by cri-s** [comment]
try this:

#define HOMING_CYCLE_0 (1<<X_AXIS)|(1<<Y_AXIS)
//#define HOMING_CYCLE_1 (1<<Y_AXIS)

//#define HOMING_CYCLE_2 // OPTIONAL: Uncomment and add axes mask to enable


2016-01-07 18:46 GMT, nccwarp9 <notifications@github.com>:

**Comment by nccwarp9** [comment]
Works! Thanks !!
