### ISSUE TITLE
grbl 0.9j homing issue

### ISSUE THREAD

**Issue by smikey** [grbl/grbl#887]
At first: Thanks for grbl, it works very well for me exept one thing:

I have a x-y-z machine but limit switches only on x and y. I want grbl homing on these axes but there is one problem:

i changed the code in config.h to
#define HOMING_CYCLE_0 (1<<Y_AXIS)  
#define HOMING_CYCLE_1 (1<<X_AXIS)

so at first the y axis is homed and then the x axis. y works very well, it drives back until it hits the switch and goes forward a little bit. after this the x axis should be homed but the only thing happening is the x axis moves forward a couple of steps two times. no backward moving and searching for the limit switch.

I don't think it's a wiring problem because the same happens if I switch the wires from X and Y. Then X works and Y doesn't.

Do you have any idea what to do?

**Comment by jahnj0584** [comment]
has to be wiring. Do you have them both set to NO or NC?

**Comment by chamnit** [comment]
@smikey : Yes. It has to be wiring or the switch. Please let us know if you resolve this issue, so I can close it.

**Comment by smikey** [comment]
Sorry for the late answer! I thought it could be the wiring or the switch, too. 

But if I check it with the multimeter both switches seem to be ok. The switches are hall sensors which connect to GND if they are hit.

I'll get new cables and test it again.

**Comment by auditofi** [comment]
@smikey could u tell me how u connect x & y switches to the board?? what pin and how.
thanks

**Comment by smikey** [comment]
Obviously I managed to get this thing to work. I use a little PCB with an optocoupler between the Arduino and the mill. I think I had some problems with a proper GND-connection between the board and the switches. I'm doing some tests now.

**Comment by chamnit** [comment]
@smikey : Thanks for letting us know.
