### ISSUE TITLE
Feature Request: Hours Meter for the Motor Enable

### ISSUE THREAD

**Issue by shmorgan** [grbl/grbl#894]
I just had to replace a DWP611 Router after only 11 months of use, the brushes where completely worn down. I am not sure how many hours the router ran, but it would be useful to have this kind of data for tracking spindle hours and bit hours. Maybe one that is non-resetable and one that is resetable.

**Comment by chamnit** [comment]
@shmorgan : IMHO, this type of feature isn't something that Grbl needs to track, but rather the GUI/sender. A GUI would just need to record run time and keep track of it.
