### ISSUE TITLE
G2 and G3 errors. 

### ISSUE THREAD

**Issue by timryder** [grbl/grbl#897]
I've created my own cad cam software which for the most part has been really good! I'm having some faults which generate however while using a G2 and G3 command. i've been getting a lot of ID:33 Invalid Targets.  So I looked through the grbl code and found the few instances that the error was generated at and I made them each unique error ID's to try and help diagnose what the cause of the error is.  

`// Compute difference between current location and target radii for final error-checks.
            float delta_r = fabs(target_r-gc_block.values.r);
            if (delta_r > 0.005) { 
              if (delta_r > 0.5) { FAIL(STATUS_GC0DE_RADIUS_39); } // [Arc definition error] > 0.5mm
              if (delta_r > (0.001*gc_block.values.r)) { FAIL(STATUS_GC0DE_RADIUS_40); } // [Arc definition error] > 0.005mm AND 0.1% radius
            }`

That section comes from line 797 for me from the gcode.c 

I seem to be getting more error 39's from the above code but i'm having difficultly trying to interpret what is the reason they're generating.  can someone help me understand the above two errors so I can improve my code?

Thanks

**Comment by chamnit** [comment]
@timryder : Please look at the linuxcnc description on G2/3. It describes the failure cases to check for. Unfortunately, the g-code G2/3 arc command is horribly mathematically posed. Meaning that it's really sensitive to error. Changing a single value by significant digit can cause it throw an error.

**Comment by timryder** [comment]
@chamnit: Thanks will do.  Do you recommend using the IKJ functionality or is it more stable to rely on the radius format.

**Comment by chamnit** [comment]
@timryder : Only use the IJK offset arc. Radius format is by far the worst offender. IJK offset arcs are less sensitive, but aren't perfect either though.
