### ISSUE TITLE
! vs M0

### ISSUE THREAD

**Issue by auhopu** [grbl/grbl#906]
As described on the wiki "the feed hold command will bring the active cycle to a stop via a controlled deceleration, so as not to lose position".

I was wondering what the exact effect of M0 is in GRBL. Will it also trigger a feed hold so as to prevent skipping steps during tool change?

I am asking after reading about [this change in bCNC](
https://github.com/vlachoudis/bCNC/issues/234) .

**Comment by chamnit** [comment]
@auhopu : Essentially yes. When Grbl receives an M0 program pause command, it'll complete any remaining motions in its queue, all prior to the M0 command, and then place the system in a suspend state. It's the same suspend state that feed hold uses, but the difference is that a feed hold will immediately decelerate and suspend the job once the deceleration is complete. Both M0 and feed hold are resumed with a cycle start character.
