### ISSUE TITLE
H level not present on D11, causes Z limit issue

### ISSUE THREAD

**Issue by eduardsik** [grbl/grbl#909]
Trying to find the problem, why my Z limit switch why not working perfect. Has to trigger multiple times to give a hard limit error. I measured everything, the noise and pull up is ok, but there is no high level signal on D11. Uploaded a simple blinking led to measure the pin, and its ok, gives me H level and L also.  
so, there is not about the switch, or noise, debounce or else, I try to figure out what causes the problem. Help me is you have a clue. 

Thanks.

**Comment by PicEngraver** [comment]
D11 is PWM output, not Z limit, on later versions of GRBL.
https://github.com/grbl/grbl
