### ISSUE TITLE
NO and NC combined limit switch support

### ISSUE THREAD

**Issue by jhapke** [grbl/grbl#913]
I have hall sensors on X and Y which are active low. Z has optical limits which are active high.  Seems like the $5 setting should be a bit mask so a single axis can be inverted. 
I don't see an option in config.h to deal with inverting only one axis limit switch.
This should be a config option. 
Thanks

**Comment by chamnit** [comment]
@jhapke : Thanks. I did something along the lines of an invert mask for the control pins, so you can mix NC and NO switches. I'll do the same thing with the limit pins shortly.

**Comment by chamnit** [comment]
@jhapke : Finally got around to this. You will now see a new config.h option that will allow you mask the limit pins, such that you can have mixed NO and NC switches. Just know that the $5 invert limit pins still applies to all of the limit pins. This mask just toggles the ones you specify.

**Comment by thejojk** [comment]
How do I mask different switches? On X+- Y+- and Z+ I have NC switches. On Z- I want a touch plate (NO).

**Comment by jahnj0584** [comment]
Check the grbl wiki

**Comment by thejojk** [comment]
Sorry, I have looked but can't find anything...

**Comment by jahnj0584** [comment]
Many guides on working NC switches. Probe should be NO by default anyways.

**Comment by electrokean** [comment]
@thejojk You need to adjust your $5 and $6 config options - https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration
Also look at the different types of G38 probe commands - http://linuxcnc.org/docs/html/gcode/g-code.html#gcode:g38
