### ISSUE TITLE
@@ hold command

### ISSUE THREAD

**Issue by DEF7** [grbl/grbl#923]
It's not in the documentation but the command '@@' also puts the machine into hold mode, doing the equivalent of the '!' command.

 And, as expected, the machine comes out of hold when you execute the start cycle command, '~'

**Comment by chamnit** [comment]
@DEF7 : That's right. The '@' command character is relatively new. Probably in the last year and enables a safety door state (and parking if enabled with the edge branch). Basically the difference is that it'll turn off all of the energized components of a machine like the spindle. A normal feed hold does not do this.
