### ISSUE TITLE
 The PWM output is not turned off completely with the order M3 S0.

### ISSUE THREAD

**Issue by tabata2008** [grbl/grbl#939]
Hello everyone .... my name is Javier and I am from Madrid (Spain).
I have a problem with GRBL v0.9i related to PWM and control the laser. It turns out that when placing the order M3 S0 the laser does not go out at all, so I tried it with a diode LED and looks like this very faint but still on. To completely shut down I have to use the M5 order. This causes me serious problems when positioning the laser because I mark the material.
With another firmware GRBL didstinto to me this does not happen.

Using Arduino UNO and GRBL v 0.9i.

Could you help me? What is due?

Thank you very much.

**Comment by chamnit** [comment]
Please use the most recent version of Grbl. This issue has been fixed already.
