### ISSUE TITLE
Hard limit appearing random

### ISSUE THREAD

**Issue by Kochchri** [grbl/grbl#943]
I'm using grbl 0.9 and the grbl controller 3.6.1. When I start homing, it seems to work correctly.

But when I want to use the Axis Control to drive my axis, after at least one step, a Hard-Limit-Alarm is fired. 

But the limit-switcher are not triggered. And they work, as the homing shows. I also read both of my switches with an simple arduino sketch which showed that they work correctly wothout any distursion.

My switches are configured as pull-ups and pull the signal to GND when activated. 
```
$21 = 1 (enabled hard-limit)
$5 = 0 (disabled invert limit pin)
```

**Comment by chamnit** [comment]
@Kochchri : This is a very common issue and the fix is to limit electrical interference in the limit pins. Wire in a low-pass filter RC circuit on each pin, shield the limit cables, place them away from any powered wires, etc,etc.

**Comment by Kochchri** [comment]
I solved it by soldering in a .47µf capacitor between GND and my switches. Workes fine.
