### ISSUE TITLE
Where is grbl heading?

### ISSUE THREAD

**Issue by rwensley** [grbl/grbl#946]
Greetings,

Having used grbl for a few months now I am looking to use it in larger applications.  Now in the planning stage I am looking to see what the future holds for grbl or is it time to look else where.

Will the platform remain on UNO?
Will a higher speed platform be used?
Will the PWM clock go above 30KHz reliably?
Will there be additional axis? (6, 9, more)
Will there be room/timing available for end user custom programming?
What kind of time frame for these plans?
Any other plans for the future release of grbl?

Thank you for your response and for the great work you are doing with this application.

Ron Wensley

**Comment by chamnit** [comment]
@rwensley : I think i've answered these questions several times over the last year. In short, after v1.0, I'll be working on an ARM version that will feature better motion control (that actually works).
