### ISSUE TITLE
What is the Gcode for Subroutine in Grbl

### ISSUE THREAD

**Issue by pubalan12** [grbl/grbl#958]
Hye guys. 

I don't know gcode for the subroutine in Grbl. Anyone Please Help Me!!

Thanks

**Comment by csdexter** [comment]
Grbl doesn't support subprograms because it only supports streaming GCode (i.e. doesn't have a global view of the entire program so that it could seek back and forth).

**Comment by pubalan12** [comment]
Thanks csdexter.

**Comment by cri-s** [comment]
if you need haas M97 M99 code on internal/external eeprom, i have it
on old 0.9 version,
but it should be easy adaptable. I run it from mega2560 , but untested
sw can run from
external i2c eeprom

2016-04-14 14:20 GMT, pubalan12 <notifications@github.com>:
