### ISSUE TITLE
Adding an Arduino library to grbl 

### ISSUE THREAD

**Issue by ib101** [grbl/grbl#964]
I have installed a w2812b led strip and I would like to add the code to drive that to the grbl code. I tried two led libraries (neopixel and the poplolu one) both did not compile with them added to the main section. My question is, where do I add the library and how?

**Comment by chamnit** [comment]
@ib101 : Grbl is completely separate from the Arduino IDE libraries and is not compatible with any of them. It only uses the Arduino IDE as a way to easily compile and upload it.
