### ISSUE TITLE
I want to change that code

### ISSUE THREAD

**Issue by atakanzey** [grbl/grbl#967]
Hi, I am doing tinkernut's mini Arduino CNC. but I want to use a servo motor for z axis. So I have to change the code .How i can do it .I can not convert that hexadecimal code into text code.Please Help Me thank you.

**Comment by electrokean** [comment]
All the source code for grbl you need is right here on github under the Code tab
https://github.com/grbl/grbl/tree/master/grbl

**Comment by atakanzey** [comment]
Ok but, How I can change the .hex code. Or which code will be converted into .hex file.

**Comment by cheton** [comment]
Just check out the wiki:
https://github.com/grbl/grbl/wiki/Compiling-Grbl#via-the-arduino-ide-all-platforms
https://github.com/grbl/grbl/wiki/Flashing-Grbl-to-an-Arduino

You can change the source code in Arduino IDE and upload Grbl to your Arduino.

**Comment by cheton** [comment]
This might help you: https://github.com/robottini/grbl-servo
