### ISSUE TITLE
Error: Invalid statement (for G1 F250)

### ISSUE THREAD

**Issue by lachap1234** [grbl/grbl#968]
Hey a got this problem when I create a .nc file with inkscape and I lunch it in grbl. Is there a way to fix that? Or maybe an other program instead of inkscape?

**Comment by Norwegian-Gadgetman** [comment]
Just the one line?
Could you post the code up until the error appears?

**Comment by lachap1234** [comment]
https://gyazo.com/d1274d450c82d488550c92d6d6bdf1bb

look at the third last line

**Comment by maaadbob** [comment]
So the command is move at feed rate (250) to a position XY, but where are your XY co-ords ?
Correct usage would be:
  G1 X100 Y125 F250

Bob.

On 20/04/2016 13:49, lachap1234 wrote:
> Hey a got this problem when I create a .nc file with inkscape and I lunch it in grbl. Is
> there a way to fix that? Or maybe an other program instead of inkscape?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/grbl/grbl/issues/968>
>

-- 

Southern Assemblies Ltd
Mob: +447758256558
Email: info@southern-assemblies.co.uk
G+: https://plus.google.com/113190327999615741877
Twitter: @SA__Ltd
Registered in England and Wales: 08149202
VAT registration No. GB183 8073 87

**Comment by maaadbob** [comment]
>...Or maybe an other program instead of inkscape?

I'm looking at Fusion360; a combined modeller, simulation and CAM program.
Have not tried its output with GRBL, but GRBL follows the CNC standard and I'm sure 
Autodesk do the same.

Bob.

**Comment by chamnit** [comment]
@lachap1234 : I recall making the `G1 Fxxx` command valid for Grbl a while ago. It also looks like you are using a very old version of Grbl, based on the settings printout in your link. I suggest that you update Grbl to the version posted here on this site.

**Comment by lachap1234** [comment]
Where is the update version on the website? Do you have the link to the good direction?

**Comment by tklus** [comment]
Fusion 360 works great with grbl. There is a grbl post and it works well. I have been using fusion 360 for over a year now. And it's free to hobbyists!

Sent from my iPhone

On Apr 20, 2016, at 6:39 AM, MadBob <notifications@github.com<mailto:notifications@github.com>> wrote:

>...Or maybe an other program instead of inkscape?

I'm looking at Fusion360; a combined modeller, simulation and CAM program.
Have not tried its output with GRBL, but GRBL follows the CNC standard and I'm sure
Autodesk do the same.

Bob.

-
