### ISSUE TITLE
DQ542MA Drivers+ arduino

### ISSUE THREAD

**Issue by gokhandilek** [grbl/grbl#984]
Hi,
I was wondering if I can use grbl with DQ542MA driver?
& can I use grbl for simple 1 axis movement? (travel to a specific length etc...)

**Comment by 109JB** [comment]
yes and yes

**Comment by lalo-uy** [comment]
I see no problem with this driver. Use the ying conection with R=0

Just wire the X signals and adapt G code to move only in X direction.
Some change in config will be needed to use homing.
