### ISSUE TITLE
Meaning of "Door : x"

### ISSUE THREAD

**Issue by LETARTARE** [grbl/grbl#986]
Hello,
what will be the use of
- "Door:x"   x in [0,1,2,3] ?
- "Hold:x"  x in [0,1] ?
- "Sleep:x"  x in [0,1] ?

Thanks

**Comment by chamnit** [comment]
@LETARTARE : The ':x' values indicate sub-states, like holding and ready to resume. There will be an API document written up prior to the v1.0 release to master. While in beta, it's still subject to change, depending on feedback from the community.

**Comment by LETARTARE** [comment]
@chamnit ,
thank you very much.
A little more detail, would provide an opinion.

**Comment by chamnit** [comment]
@LETARTARE : Obviously you read the source code. Comments on what they are are there.

**Comment by splitn2** [comment]
@chamnit I like this mention of 1.0 ,  bring it on !!! I am not pushing just very interested, keep up the good work mate! My next wee project includes a GRBL small 3 axis cnc to drill skis , its mentioned on my Git as a very preliminary start, I need to get some young brains on the project to do some programming for the project next...... https://github.com/splitn2/DrillSki
