### ISSUE TITLE
 Pen Lift

### ISSUE THREAD

**Issue by Shakeel15** [grbl/grbl#999]
Hello, I am also working on some sort of pen cnc myself, and I need some help figuring out how to lift the pen with a stepper motor and not a servo because of the stepper motor GRBL Shield I have.

**Comment by jahnj0584** [comment]
just do your cam as a trace operation and it will do it itself.

**Comment by OldSalt1945** [comment]
CNC NYC did this in a youtube video using springs.  Watch the video at: 
https://www.youtube.com/watch?v=gzLYNSQEPDk

The method he used is heavy on machining because that's what he does, but you could take the idea and make something to suit your needs.

John
